using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using BlackCube.CombatSimulation;
using UnityEditor;
using UnityEngine;

namespace BlackCube.BalanceWorkbench
{
    [Serializable] public sealed class CombatLabRequest
    {
        public PlayerBuildSnapshot player=new();public string enemyArchetypeId;public string bossId;public bool useBoss;public int enemyLevel=50,fightCount=100,corruption;public EnemyAI.EnemyRarity rarity=EnemyAI.EnemyRarity.Normal;public long seed=51001;public EnemySamplingMode samplingMode;public CombatSimulationConfig config=new();
    }
    [Serializable] public sealed class CombatDistribution
    {public double mean,stdDev,p01,p05,p10,p25,p50,p75,p90,p95,p99;public static CombatDistribution From(IEnumerable<double> values){var a=values.Where(double.IsFinite).OrderBy(x=>x).ToArray();if(a.Length==0)return new();double mean=a.Average(),variance=a.Select(x=>(x-mean)*(x-mean)).Average();double P(double q){double n=(a.Length-1)*q;int lo=(int)Math.Floor(n),hi=(int)Math.Ceiling(n);return a[lo]+(a[hi]-a[lo])*(n-lo);}return new(){mean=mean,stdDev=Math.Sqrt(variance),p01=P(.01),p05=P(.05),p10=P(.1),p25=P(.25),p50=P(.5),p75=P(.75),p90=P(.9),p95=P(.95),p99=P(.99)};}}
    [Serializable] public sealed class CombatBatchResult
    {
        public CombatLabRequest request;public string fingerprint;public int fights,wins,losses,timeouts,errors;public double winRate,lossRate,timeoutRate;public CombatDistribution duration=new(),playerLifeOnWin=new(),enemyLifeOnLoss=new(),playerDps=new(),manaStarvation=new();public long fastestWinSeed,slowestWinSeed,closestWinSeed,worstLossSeed,randomLossSeed;public List<double> durationSamples=new(),playerLifeSamples=new(),enemyLifeSamples=new();public List<CombatContribution> damage=new(),damageByType=new(),healing=new(),phaseTime=new();public List<CombatAilmentMetric> ailments=new();public List<CombatSkillMetric> skills=new(),enemySkills=new();public List<CombatSimulationResult> samples=new();public List<string> errorArtifacts=new();
    }
    [Serializable] public sealed class CombatMatrixCell{public string player,enemy;public double winRate,medianDuration,medianPlayerLife,timeoutRate;public long seed;}
    [Serializable] public sealed class CombatMatrixResult{public List<CombatMatrixCell> cells=new();public string fingerprint;}
    [Serializable] public sealed class CombatCurvePoint{public int level;public double winRate,p50Duration,p90Duration,remainingLife,manaStarvation,ailmentShare;}
    [Serializable] public sealed class CombatCurveResult{public string name,fingerprint;public List<CombatCurvePoint> points=new();}
    [Serializable] public sealed class CombatErrorArtifact{public CombatLabRequest request;public CombatantSnapshot player,enemy;public CombatSimulationResult result;public string fingerprint,createdUtc;}

    public static class CombatLabAdapters
    {
        public static CombatantSnapshot PlayerSnapshot(PlayerBuildSnapshot build)
        {
            using var evaluation=new PlayerBuildEvaluation(build);var stats=evaluation.Stats;var metrics=evaluation.Metrics;var hit=evaluation.Player.BuildNonCriticalAttackContext();var p=new CombatantSnapshot{id="player",name=$"{build.classId} {build.subclassId}",player=true,classId=build.classId,subclassId=build.subclassId,weaponTypeId=build.weaponTypeId,maximumLife=(float)metrics.life,maximumMana=(float)metrics.mana,attackSpeed=(float)metrics.attacksPerSecond,critChance=(float)metrics.critChance,critMultiplier=(float)metrics.critMultiplier,hitTwiceChance=(float)metrics.hitTwiceChance,armour=(float)metrics.armour,fireResistance=(float)metrics.fireResistance,coldResistance=(float)metrics.coldResistance,lightningResistance=(float)metrics.lightningResistance,voidResistance=(float)metrics.voidResistance,lifeRegeneration=(float)metrics.lifeRegen,manaRegeneration=(float)metrics.manaRegen,lifeOnHit=(float)metrics.lifeOnHit,manaOnHit=(float)metrics.manaOnHit,lifeOnKill=(float)metrics.lifeOnKill,manaOnKill=(float)metrics.manaOnKill,poisonChance=stats.GetStat(StatTypes.PoisonChance),bleedChance=stats.GetStat(StatTypes.BleedChance),igniteChance=stats.GetStat(StatTypes.IgniteChance),shockChance=stats.GetStat(StatTypes.ShockChance),chillChance=stats.GetStat(StatTypes.ChillChance),poisonMagnitude=(float)metrics.poisonMagnitude,bleedMagnitude=(float)metrics.bleedMagnitude,igniteMagnitude=(float)metrics.igniteMagnitude,shockEffect=(float)metrics.shockEffect,chillEffect=(float)metrics.chillEffect,projectileCount=Mathf.Max(1,(int)Math.Round(metrics.projectileCount)),projectileTravelTime=(float)metrics.projectileTravelTime,precisionChance=(float)metrics.precisionChance,precisionMultiplier=(float)metrics.precisionMultiplier,rageGeneration=(float)metrics.rageGeneration,rageEffect=(float)metrics.rageEffect,rageDecayReduction=stats.GetStat(StatTypes.RageDecayReduction),auraEffect=(float)metrics.auraEffect,physicalPenetration=stats.GetStat(StatTypes.PhysPenetration),firePenetration=stats.GetStat(StatTypes.FirePenetration),coldPenetration=stats.GetStat(StatTypes.ColdPenetration),lightningPenetration=stats.GetStat(StatTypes.LightPenetration),voidPenetration=stats.GetStat(StatTypes.VoidPenetration),poisonSpeed=stats.GetStat(StatTypes.PoisonSpeed),hasRageFinisher=build.passiveStableIds.Contains(PassiveTreeDefinition.Node(PassiveTreeDefinition.RageFinisherNodeId).StableId),maximumShockInstances=build.subclassId==SubclassIds.MageStorm?SubclassBalanceProfile.StormShockMaximum:1};
            p.basicDamage=Damage(hit);var definitions=Resources.Load<PlayerSkillCatalog>("PlayerSkills")?.skills??PlayerSkillDefinition.CreateProductionDefaults();var ids=WeaponSkillBindings.For(build.weaponTypeId);foreach(var id in ids){var x=definitions.FirstOrDefault(y=>y!=null&&y.id==id);if(x==null)continue;int level=PlayerSkillController.CalculateEffectiveSkillLevel(stats.GetRawStat(PlayerSkillController.SkillLevelStat(x.id)));float cost=Mathf.Round(Mathf.Max(0,x.manaCost)*PlayerSkillController.ManaCostLevelFactor(level));int hits=Mathf.Max(1,x.baseHitCount);if(x.effect==WeaponSkillEffect.RapidFlurry)hits=WeaponMechanicProfile.RapidFlurryHits(stats.GetStat(StatTypes.AttackSpeed));int projectiles=x.projectile?p.projectileCount:1;if(x.effect==WeaponSkillEffect.DoubleProjectiles)projectiles*=2;p.skills.Add(new CombatSkillSnapshot{id=x.stableId,name=x.displayName,castMode=x.castMode,effect=x.effect,manaCost=cost,cooldown=x.castMode==PlayerSkillCastMode.QueuedAttackReplacement?0:Mathf.Max(PlayerSkillController.MinimumAutoCooldown,x.baseCooldown/(1+Mathf.Max(0,stats.GetStat(StatTypes.CooldownReduction)))),hitMultiplier=x.hitDamageMultiplier*PlayerSkillController.SkillDamageLevelFactor(level),secondaryMultiplier=x.secondaryMultiplier,ailmentBasisMultiplier=x.ailmentBasisMultiplier,hits=hits,projectiles=projectiles,projectile=x.projectile,supportsPrecision=x.supportsPrecision,conversionElement=x.conversionElement,conversion=x.nonMatchingConversion,specializedAilment=x.specializedAilment,guaranteedAilmentApplications=x.guaranteedAilmentApplications,guaranteedAdditionalChill=x.guaranteedAdditionalChill});}return p;
        }

        public static CombatantSnapshot EnemySnapshot(string archetypeId,int level,EnemyAI.EnemyRarity rarity,int corruption,long seed)
        {var preview=EnemyAuthoringAdapters.PreviewEnemy(archetypeId,level,rarity,corruption,seed);return EnemySnapshot(preview,null);}
        public static CombatantSnapshot EnemySnapshot(EnemyPreviewSnapshot preview,BossDefinition boss)
        {
            var db=WorldContentCatalog.Reference;var x=preview.sample;var enemy=new CombatantSnapshot{id=preview.archetypeId,name=preview.displayName,player=false,boss=boss!=null,challengeBoss=boss?.challengeBoss??false,maximumLife=(float)x.life,attackSpeed=(float)x.attackSpeed,critChance=Mathf.Clamp01((float)x.critChance),critMultiplier=CombatCalculator.BaseCriticalMultiplier+(float)x.critMultiplier,armour=(float)x.armour,fireResistance=(float)x.fireResistance,coldResistance=(float)x.coldResistance,lightningResistance=(float)x.lightningResistance,voidResistance=(float)x.voidResistance,lifeRegeneration=(float)x.lifeRegeneration,behaviorProfileId=preview.behaviorProfileId,behavior=Clone(db.BehaviorProfile(preview.behaviorProfileId)),phases=boss==null?null:Clone(db.BossPhase(boss.phaseProfileId))};Set(enemy.basicDamage,ParseElement(x.primaryDamage),(float)x.damagePerHit);var loadout=db.SkillLoadout(preview.loadoutId);foreach(string id in loadout?.skillIds??new()){var s=db.EnemySkill(id);if(s!=null)enemy.enemySkills.Add(new CombatEnemySkillSnapshot{id=s.stableId,name=s.displayName,kind=s.kind,element=s.element,damageMultiplier=s.damageMultiplier,hits=Mathf.Max(1,s.hitCount)});}return enemy;
        }
        public static EnemyPreviewSnapshot BossPreview(string bossId,int level,int corruption,long seed)
        {
            var db=WorldContentCatalog.Reference;var boss=db.Boss(bossId)??throw new InvalidOperationException("Boss not found: "+bossId);var fallback=BlackCube.BalanceSimulationRunner.DiscoverEnemies();var prefab=boss.prefab!=null?boss.prefab:fallback.FirstOrDefault();if(prefab==null)throw new InvalidOperationException("No production enemy prefab is available for boss simulation: "+bossId);using var session=new WorkbenchSession();var actor=UnityEngine.Object.Instantiate(prefab);actor.hideFlags=HideFlags.HideAndDontSave;try{var ai=actor.GetComponent<EnemyAI>();var tier=db.corruptionTiers.OrderBy(x=>Math.Abs(x.percentage-corruption)).FirstOrDefault();var biome=db.biomes[Mathf.Clamp(boss.biomeIndex,0,db.biomes.Count-1)];var location=boss.locationIndex>=0&&boss.locationIndex<biome.locations.Count?biome.locations[boss.locationIndex]:biome.locations.LastOrDefault();ai.ConfigureWorldContent(db,null,boss,tier,location);ai.GenerateIsolatedBuild(level,session.Roller,EnemyAI.EnemyRarity.Legendary,new SeededSimulationRandomSource(seed));var stats=actor.GetComponent<StatsComponent>();var health=actor.GetComponent<HealthComponent>();var hit=ai.BuildNonCriticalAttackContext();double amount=hit.Hits?.Sum(h=>(double)h.Amount)??0;var sample=new EnemySample{level=level,archetype=boss.displayName,rarity=(int)ai.CurrentRarity,primaryDamage=ai.WeaponMainElement.ToString(),life=health.MaxLife,damagePerHit=amount,attackSpeed=ai.GetFinalAttackSpeed(),dps=amount*ai.GetFinalAttackSpeed(),armour=stats.GetStat(StatTypes.FlatArmour),fireResistance=stats.GetStat(StatTypes.FireRes),coldResistance=stats.GetStat(StatTypes.ColdRes),lightningResistance=stats.GetStat(StatTypes.LightRes),voidResistance=stats.GetStat(StatTypes.VoidRes),lifeRegeneration=stats.GetStat(StatTypes.LifeRegeneration),critChance=stats.GetStat(StatTypes.CritChance),critMultiplier=stats.GetStat(StatTypes.CritMult),equipment=string.Join(" | ",ai.EquippedItems.Select(g=>g.ItemType+":"+g.ItemRarity))};return new EnemyPreviewSnapshot{archetypeId=boss.stableId,displayName=boss.displayName,level=level,rarity=ai.CurrentRarity,corruption=corruption,seed=seed,sample=sample,behaviorProfileId=boss.behaviorProfileId,loadoutId=boss.skillLoadoutId};}finally{UnityEngine.Object.DestroyImmediate(actor);}}
        public static CombatSimulationResult Single(CombatLabRequest request)
        {var p=PlayerSnapshot(request.player);EnemyPreviewSnapshot preview=request.useBoss?BossPreview(request.bossId,request.enemyLevel,request.corruption,request.seed):EnemyAuthoringAdapters.PreviewEnemy(request.enemyArchetypeId,request.enemyLevel,request.rarity,request.corruption,request.seed);var e=EnemySnapshot(preview,request.useBoss?WorldContentCatalog.Reference.Boss(request.bossId):null);request.config.seed=request.seed;request.config.retainTrace=true;var r=HeadlessCombatSimulator.Run(p,e,request.config);r.fingerprint=ProductionBalanceAdapters.DataFingerprint();if(r.outcome==CombatOutcome.SimulationError)WriteErrorArtifact(request,p,e,r);return r;}
        public static CombatSimulationResult Replay(CombatLabRequest request,long seed){var copy=Clone(request);copy.seed=seed;copy.config.seed=seed;return Single(copy);}
        public static CombatBatchResult Batch(CombatLabRequest request,Action<float> progress=null,Func<bool> cancelled=null)
        {
            var result=new CombatBatchResult{request=Clone(request),fingerprint=ProductionBalanceAdapters.DataFingerprint()};var p=PlayerSnapshot(request.player);EnemyPreviewSnapshot representative=request.useBoss?BossPreview(request.bossId,request.enemyLevel,request.corruption,request.seed):EnemyAuthoringAdapters.PreviewEnemy(request.enemyArchetypeId,request.enemyLevel,request.rarity,request.corruption,request.seed);var representativeState=EnemySnapshot(representative,request.useBoss?WorldContentCatalog.Reference.Boss(request.bossId):null);var durations=new List<double>();var winLife=new List<double>();var lossLife=new List<double>();var dps=new List<double>();var starved=new List<double>();var all=new List<CombatSimulationResult>();int count=Math.Max(1,request.fightCount);
            for(int i=0;i<count;i++){if(cancelled?.Invoke()==true)break;long seed=CombatDeterministicRules.DeriveSeed(request.seed,i);var cfg=Clone(request.config);cfg.seed=seed;cfg.retainTrace=false;CombatantSnapshot enemy=representativeState;if(request.samplingMode==EnemySamplingMode.Population&&!request.useBoss){var preview=EnemyAuthoringAdapters.PreviewEnemy(request.enemyArchetypeId,request.enemyLevel,request.rarity,request.corruption,seed);enemy=EnemySnapshot(preview,null);}var fight=HeadlessCombatSimulator.Run(p,enemy,cfg);fight.fingerprint=result.fingerprint;all.Add(fight);durations.Add(fight.duration);double dealt=fight.damage.Where(x=>x.id.StartsWith("Player/")).Sum(x=>x.total);dps.Add(dealt/Math.Max(.001,fight.duration));starved.Add(fight.timeAtZeroMana/Math.Max(.001,fight.duration));if(fight.outcome==CombatOutcome.PlayerWin){result.wins++;winLife.Add(fight.playerLife);}else if(fight.outcome==CombatOutcome.PlayerLoss){result.losses++;lossLife.Add(fight.enemyLife);}else if(fight.outcome==CombatOutcome.Timeout)result.timeouts++;else{result.errors++;result.errorArtifacts.Add(WriteErrorArtifact(request,p,enemy,fight));}Merge(result.damage,fight.damage);Merge(result.damageByType,fight.damageByType);Merge(result.healing,fight.healing);Merge(result.phaseTime,fight.phaseTime);MergeAilments(result.ailments,fight.ailments);MergeSkills(result.skills,fight.skills);MergeSkills(result.enemySkills,fight.enemySkills);if((i&31)==0)progress?.Invoke((i+1f)/count);}
            result.fights=all.Count;result.winRate=result.fights==0?0:result.wins/(double)result.fights;result.lossRate=result.fights==0?0:result.losses/(double)result.fights;result.timeoutRate=result.fights==0?0:result.timeouts/(double)result.fights;result.duration=CombatDistribution.From(durations);result.playerLifeOnWin=CombatDistribution.From(winLife);result.enemyLifeOnLoss=CombatDistribution.From(lossLife);result.playerDps=CombatDistribution.From(dps);result.manaStarvation=CombatDistribution.From(starved);result.durationSamples=durations;result.playerLifeSamples=winLife;result.enemyLifeSamples=lossLife;result.fastestWinSeed=all.Where(x=>x.Won).OrderBy(x=>x.duration).FirstOrDefault()?.seed??0;result.slowestWinSeed=all.Where(x=>x.Won).OrderByDescending(x=>x.duration).FirstOrDefault()?.seed??0;result.closestWinSeed=all.Where(x=>x.Won).OrderBy(x=>x.playerLife).FirstOrDefault()?.seed??0;result.worstLossSeed=all.Where(x=>x.outcome==CombatOutcome.PlayerLoss).OrderByDescending(x=>x.enemyLife).FirstOrDefault()?.seed??0;result.randomLossSeed=all.FirstOrDefault(x=>x.outcome==CombatOutcome.PlayerLoss)?.seed??0;result.samples=all.Take(10).ToList();return result;
        }

        public static List<string> ValidatePolicy(CombatLabRequest request)
        {var e=new List<string>();if(request?.player==null)e.Add("Player build is missing.");if(!request.useBoss&&string.IsNullOrEmpty(request.enemyArchetypeId))e.Add("Enemy archetype is missing.");if(request.useBoss&&string.IsNullOrEmpty(request.bossId))e.Add("Boss is missing.");if(request.config.maximumDuration<=0)e.Add("Maximum duration must be positive.");if(request.config.maximumEvents<=0)e.Add("Maximum events must be positive.");if(request.config.manaReserve<0||request.config.manaReserve>1)e.Add("Mana reserve must be 0–100%.");if(request.config.rageTargetThreshold<0||request.config.rageTargetThreshold>1)e.Add("Rage target threshold must be 0–100%.");return e;}
        static CombatDamageSnapshot Damage(DamageContext x){var d=new CombatDamageSnapshot();foreach(var h in x.Hits??new())Set(d,h.Element,h.Amount);return d;}static void Set(CombatDamageSnapshot d,Element e,float v){switch(e){case Element.Phys:d.physical+=v;break;case Element.Fire:d.fire+=v;break;case Element.Cold:d.cold+=v;break;case Element.Light:d.lightning+=v;break;default:d.voidDamage+=v;break;}}
        static string WriteErrorArtifact(CombatLabRequest request,CombatantSnapshot player,CombatantSnapshot enemy,CombatSimulationResult result){Directory.CreateDirectory("Logs/CombatSimulationErrors");string path=$"Logs/CombatSimulationErrors/combat_error_{DateTime.UtcNow:yyyyMMdd_HHmmss_fff}_{result.seed}.json";var artifact=new CombatErrorArtifact{request=Clone(request),player=player,enemy=enemy,result=result,fingerprint=ProductionBalanceAdapters.DataFingerprint(),createdUtc=DateTime.UtcNow.ToString("O")};File.WriteAllText(path,JsonUtility.ToJson(artifact,true));return path;}
        static Element ParseElement(string s)=>Enum.TryParse(s,true,out Element e)?e:Element.Phys;static T Clone<T>(T x)=>x==null?default:JsonUtility.FromJson<T>(JsonUtility.ToJson(x));
        static void Merge(List<CombatContribution> target,List<CombatContribution> source){foreach(var x in source){var y=target.FirstOrDefault(z=>z.id==x.id);if(y==null){y=new CombatContribution{id=x.id};target.Add(y);}y.total+=x.total;y.effective+=x.effective;y.overheal+=x.overheal;y.count+=x.count;}}
        static void MergeAilments(List<CombatAilmentMetric> target,List<CombatAilmentMetric> source){foreach(var x in source){var y=target.FirstOrDefault(z=>z.id==x.id);if(y==null){y=new CombatAilmentMetric{id=x.id};target.Add(y);}y.applications+=x.applications;y.maxStacks=Math.Max(y.maxStacks,x.maxStacks);y.damage+=x.damage;y.uptime+=x.uptime;y.magnitudeTotal+=x.magnitudeTotal;y.stackTime+=x.stackTime;y.maximumEffect=Math.Max(y.maximumEffect,x.maximumEffect);}}
        static void MergeSkills(List<CombatSkillMetric> target,List<CombatSkillMetric> source){foreach(var x in source){var y=target.FirstOrDefault(z=>z.id==x.id);if(y==null){y=new CombatSkillMetric{id=x.id};target.Add(y);}y.activations+=x.activations;y.resolves+=x.resolves;y.manaFailures+=x.manaFailures;y.cooldownBypasses+=x.cooldownBypasses;y.queuedRepeats+=x.queuedRepeats;y.damage+=x.damage;y.intervalTotal+=x.intervalTotal;y.readyStarvedTime+=x.readyStarvedTime;}}
    }
}
