using System;
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace BlackCube.BalanceWorkbench
{
    public sealed partial class BalanceWorkbenchWindow
    {
        enum HeatmapMode{ImmediateObjective,PrimaryMetric,SecondaryMetric,PathAdjusted,SelectedPath}
        PlayerBuildSnapshot playerBuild=new();OptimizationObjective objective=new();OptimizationConstraints playerConstraints=new();PlayerBuildMetrics playerMetrics,compareA,compareB;List<BuildAblationContribution> contributions=new();GearOptimizationResult gearResult;PassiveOptimizationResult passiveResult;List<PassiveMarginalResult> marginal=new();ScenarioSweepResult playerSweep;PlayerGearProfileSO gearProfile;int passivePoints=50,passiveBeamWidth=100;bool passiveBeam,scenarioPassives,scenarioProgressive,scenarioFreeRespec=true,showConstraints;string curveMetric="basic_dps";Vector2 heatPan;float heatZoom=.09f;HeatmapMode heatmapMode;PassiveMarginalResult selectedMarginal;

        void BuildInputs()
        {
            playerBuild.playerLevel=EditorGUILayout.IntSlider("Player Level",playerBuild.playerLevel,1,100);playerBuild.combatLevel=EditorGUILayout.IntSlider("Combat Level",playerBuild.combatLevel,1,360);playerBuild.seed=EditorGUILayout.LongField("Simulation Seed",playerBuild.seed);
            string[] classes=PlayerClassCatalog.All.Select(x=>x.Id).ToArray();int ci=Mathf.Max(0,Array.IndexOf(classes,playerBuild.classId));playerBuild.classId=classes[EditorGUILayout.Popup("Class",ci,PlayerClassCatalog.All.Select(x=>x.DisplayName).ToArray())];var subs=SubclassCatalog.ForClass(playerBuild.classId);string[] subIds=new[]{""}.Concat(subs.Select(x=>x.Id)).ToArray();string[] subNames=new[]{"None"}.Concat(subs.Select(x=>x.DisplayName)).ToArray();int subi=Mathf.Max(0,Array.IndexOf(subIds,playerBuild.subclassId));playerBuild.subclassId=subIds[EditorGUILayout.Popup("Subclass",subi,subNames)];string[] weapons=WeaponTypeCatalog.All.Select(x=>x.Id).ToArray();int wi=Mathf.Max(0,Array.IndexOf(weapons,playerBuild.weaponTypeId));playerBuild.weaponTypeId=weapons[EditorGUILayout.Popup("Weapon",wi,WeaponTypeCatalog.All.Select(x=>x.DisplayName).ToArray())];if(playerBuild.subclassId==SubclassIds.RangerProjectile)playerBuild.projectileMode=(SubclassProjectileMode)EditorGUILayout.EnumPopup("Projectile Mode",playerBuild.projectileMode);
        }
        void ObjectiveInputs()
        {
            string[] names=OptimizationMetricCatalog.All.Select(x=>x.Name).ToArray();int p=Mathf.Max(0,OptimizationMetricCatalog.All.ToList().FindIndex(x=>x.Id==objective.primary));objective.primary=OptimizationMetricCatalog.All[EditorGUILayout.Popup("Primary Objective",p,names)].Id;int s=Mathf.Max(0,OptimizationMetricCatalog.All.ToList().FindIndex(x=>x.Id==objective.secondary));objective.secondary=OptimizationMetricCatalog.All[EditorGUILayout.Popup("Secondary Objective",s,names)].Id;objective.mode=(OptimizationMode)EditorGUILayout.EnumPopup("Objective Mode",objective.mode);if(objective.mode==OptimizationMode.Weighted)objective.primaryWeight=EditorGUILayout.Slider("Primary Weight",objective.primaryWeight,0,1);EditorGUILayout.HelpBox("Optimization Score is scenario-relative, not a canonical power rating. Weighted mode uses signed log-relative change with a 5% baseline floor; lexicographic mode prioritizes Primary and uses Secondary only as the deterministic second priority.",MessageType.None);
        }
        void ConstraintInputs()
        {
            showConstraints=EditorGUILayout.Foldout(showConstraints,"Optional Optimization Constraints",true);if(!showConstraints)return;
            playerConstraints.minimumLifeEnabled=EditorGUILayout.Toggle("Minimum Life",playerConstraints.minimumLifeEnabled);if(playerConstraints.minimumLifeEnabled)playerConstraints.minimumLife=EditorGUILayout.FloatField("Life Threshold",playerConstraints.minimumLife);
            playerConstraints.minimumArmourEnabled=EditorGUILayout.Toggle("Minimum Armour",playerConstraints.minimumArmourEnabled);if(playerConstraints.minimumArmourEnabled)playerConstraints.minimumArmour=EditorGUILayout.FloatField("Armour Threshold",playerConstraints.minimumArmour);
            playerConstraints.minimumFireResistanceEnabled=EditorGUILayout.Toggle("Minimum Fire Resistance",playerConstraints.minimumFireResistanceEnabled);if(playerConstraints.minimumFireResistanceEnabled)playerConstraints.minimumFireResistance=EditorGUILayout.Slider("Fire Threshold",playerConstraints.minimumFireResistance,-.75f,.9f);
            playerConstraints.maximumOffClassPoints=EditorGUILayout.IntField("Maximum Off-Class Points (-1 disables)",playerConstraints.maximumOffClassPoints);
        }
        void PlayerBuildLab()
        {
            Heading("PLAYER BUILD SNAPSHOT","Generated and manual snapshots evaluate without entering Play Mode.");BuildInputs();ObjectiveInputs();ConstraintInputs();using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("EVALUATE BUILD",GUILayout.Height(30)))Run("Player build evaluation",_=>{playerMetrics=PlayerBuildEvaluator.Evaluate(playerBuild);contributions=PlayerBuildContributionAnalyzer.Analyze(playerBuild,objective);});if(GUILayout.Button("CLEAR GEAR")){playerBuild.equipment.Clear();playerMetrics=null;}if(GUILayout.Button("CLEAR PASSIVES")){playerBuild.passiveStableIds.Clear();playerMetrics=null;}if(GUILayout.Button("EXPORT JSON"))status=WorkbenchExports.SaveJson("player_build",playerBuild);if(playerMetrics!=null&&GUILayout.Button("EXPORT CSV"))status=WorkbenchExports.SaveBuildCsv(playerBuild,playerMetrics);}
            Heading("MANUAL / GENERATED EQUIPMENT");gearProfile=(PlayerGearProfileSO)EditorGUILayout.ObjectField("Generation Profile",gearProfile,typeof(PlayerGearProfileSO),false);if(gearProfile==null)gearProfile=AssetDatabase.LoadAssetAtPath<PlayerGearProfileSO>("Assets/Balance/Profiles/SO_PlayerGearProfile_Mid.asset");if(GUILayout.Button("GENERATE COMPLETE GEARSET"))Run("Gear optimization",_=>{gearResult=PlayerGearsetOptimizer.Optimize(playerBuild,gearProfile,objective,gearProfile.selectionStrategy==PlayerGearSelectionStrategy.FullGearsetBeamSearch,playerConstraints,Progress("Gear search"),()=>cancelled);playerBuild=gearResult.build;playerMetrics=gearResult.metrics;contributions=PlayerBuildContributionAnalyzer.Analyze(playerBuild,objective);});foreach(var g in playerBuild.equipment.OrderBy(x=>x.slot))using(new EditorGUILayout.HorizontalScope(EditorStyles.helpBox)){GUILayout.Label(g.Description,GUILayout.MinWidth(400));bool locked=playerConstraints.lockedSlots.Contains(g.slot);if(GUILayout.Button(locked?"Unlock":"Lock",GUILayout.Width(55))){if(locked)playerConstraints.lockedSlots.Remove(g.slot);else playerConstraints.lockedSlots.Add(g.slot);}if(GUILayout.Button("Clear",GUILayout.Width(55))){playerBuild.equipment.Remove(g);break;}if(GUILayout.Button("Inspect",GUILayout.Width(60)))EditorUtility.DisplayDialog(g.slot.ToString(),g.Description,"Close");}
            if(playerMetrics!=null){MetricsPanel(playerMetrics);Heading("BUILD A vs BUILD B");using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("Capture as A"))compareA=playerMetrics;if(GUILayout.Button("Capture as B"))compareB=playerMetrics;}if(compareA!=null&&compareB!=null)Compare(compareA,compareB);}
            Heading("SEND THIS BUILD TO ANALYSIS");using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SENSITIVITY")){sensitivity.build=playerBuild.Clone();tab=Tab.Sensitivity;}if(GUILayout.Button("AFFIX ANALYZER")){affixRequest.build=playerBuild.Clone();tab=Tab.AffixAnalyzer;}if(GUILayout.Button("LOOT PROGRESSION")){lootRequest.build=playerBuild.Clone();tab=Tab.LootProgression;}if(GUILayout.Button("BREAKPOINT FINDER"))tab=Tab.BreakpointFinder;if(GUILayout.Button("COMBAT LAB")){combatRequest.player=playerBuild;tab=Tab.CombatLab;}}
        }
        void MetricsPanel(PlayerBuildMetrics m)
        {
            Heading("AUTHORITATIVE ANALYTICAL METRICS");EditorGUILayout.LabelField("Average hit / Basic DPS",$"{m.averageHit:0.##} / {m.basicDps:0.##}");EditorGUILayout.LabelField("APS / Crit / Crit Multi",$"{m.attacksPerSecond:0.###} / {m.critChance:P2} / {m.critMultiplier:0.###}x");EditorGUILayout.LabelField("Physical · Fire · Cold · Lightning · Void",$"{m.physicalOutput:0.#} · {m.fireOutput:0.#} · {m.coldOutput:0.#} · {m.lightningOutput:0.#} · {m.voidOutput:0.#}");EditorGUILayout.LabelField("Poison · Bleed · Ignite DPS",$"{m.poisonDps:0.#} · {m.bleedDps:0.#} · {m.igniteDps:0.#}");EditorGUILayout.LabelField("Life / Armour / Mana",$"{m.life:0.#} / {m.armour:0.#} / {m.mana:0.#}");EditorGUILayout.LabelField("EHP Phys · Fire · Cold · Lightning · Void",$"{m.ehpPhysical:0.#} · {m.ehpFire:0.#} · {m.ehpCold:0.#} · {m.ehpLightning:0.#} · {m.ehpVoid:0.#}");foreach(var skill in m.skills)EditorGUILayout.LabelField(skill.name,$"{skill.averageDamagePerUse:0.#}/use · {skill.effectiveCooldown:0.##}s · {(skill.sustainable?"sustainable":"Mana pressure")}");foreach(string assumption in m.assumptions)EditorGUILayout.HelpBox(assumption,MessageType.None);
            Heading("DAMAGE CONTRIBUTION TRACE");EditorGUILayout.LabelField("Base weapon average",m.baseWeaponAverage.ToString("0.###"));EditorGUILayout.LabelField("Attribute / level increased",$"{m.weaponAttributeIncreased:P2} / {m.playerLevelIncreased:P2}");EditorGUILayout.LabelField("Generic / Physical increased",$"{m.genericIncreased:P2} / {m.physicalIncreased:P2}");EditorGUILayout.LabelField("Generic / Physical more",$"{m.genericMore:P2} / {m.physicalMore:P2}");EditorGUILayout.LabelField("Crit / Hit Twice expectation",$"{m.critContribution:0.###} / {m.hitTwiceContribution:0.###}");
            if(contributions.Count>0){Heading("MARGINAL / ABLATION CONTRIBUTION");foreach(var x in contributions)EditorGUILayout.LabelField(x.source,$"Primary {x.primary:+0.###;-0.###;0} · Secondary {x.secondary:+0.###;-0.###;0}");EditorGUILayout.HelpBox("Interacting source categories do not necessarily sum to the full metric.",MessageType.None);}
            if(gearResult!=null){Heading("SCENARIO-RELATIVE ITEM CONTRIBUTIONS");foreach(var x in gearResult.selected)EditorGUILayout.LabelField(x.item.slot.ToString(),$"Objective {x.score:+0.####;-0.####;0} · Primary {x.primaryDelta:+0.##;-0.##;0} · Secondary {x.secondaryDelta:+0.##;-0.##;0}");EditorGUILayout.LabelField("Gear search debug",$"Generated {gearResult.debug.generated}; retained {gearResult.debug.retained}; states {gearResult.debug.statesEvaluated}; pruned {gearResult.debug.statesPruned}; beam {gearResult.debug.beamWidth}");if(GUILayout.Button("EVALUATE FINAL GEARSET WITH COMBAT LAB")){playerBuild=gearResult.build.Clone();combatRequest.player=playerBuild;tab=Tab.CombatLab;}}
        }
        void GearCurves()
        {
            Heading("PLAYER GEAR CURVES");BuildInputs();ObjectiveInputs();SweepInputs(100);MetricPopup();var profiles=LoadProfiles();if(GUILayout.Button("RUN LOW / MID / OPTIMIZED GEAR CURVES",GUILayout.Height(30)))Run("Gear curves",_=>{playerSweep=PlayerScenarioSweep.Run(playerBuild,profiles,objective,sweepStart,sweepEnd,sweepIncrement,false,false,true,1,Progress("Gear curves"),()=>cancelled);curves=playerSweep.Curves(curveMetric);});DrawPlayerCurves();
        }
        void PassiveOptimizer()
        {
            Heading("PRODUCTION PASSIVE OPTIMIZER");BuildInputs();ObjectiveInputs();ConstraintInputs();passivePoints=EditorGUILayout.IntSlider("Passive Point Budget",passivePoints,0,100);passiveBeam=EditorGUILayout.Toggle("Beam Search",passiveBeam);if(passiveBeam)passiveBeamWidth=EditorGUILayout.IntSlider("Beam Width",passiveBeamWidth,10,2000);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("OPTIMIZE",GUILayout.Height(30)))Run("Passive optimization",_=>{passiveResult=PassiveTreeOptimizer.Optimize(playerBuild,passivePoints,objective,passiveBeam,passiveBeamWidth,playerConstraints,Progress("Passive depth"),()=>cancelled);playerBuild=passiveResult.build;playerMetrics=passiveResult.metrics;});if(GUILayout.Button("ANALYZE LEGAL NEXT NODES",GUILayout.Height(30)))Run("Marginal analysis",_=>marginal=PassiveTreeOptimizer.Analyze(playerBuild,objective,playerConstraints,false));if(passiveResult!=null&&GUILayout.Button("EXPORT CSV"))status=WorkbenchExports.SavePassiveCsv(passiveResult);}
            if(passiveResult!=null){Heading("OPTIMAL LEGAL ALLOCATION");EditorGUILayout.LabelField("Algorithm / Score",$"{passiveResult.algorithm} / {passiveResult.score:0.######}");EditorGUILayout.LabelField("Points / Stable IDs",$"{passiveResult.build.passiveStableIds.Count} / {string.Join(", ",passiveResult.build.passiveStableIds)}");foreach(var x in passiveResult.sequence)using(new EditorGUILayout.HorizontalScope()){GUILayout.Label($"{x.point}. {x.name}",GUILayout.Width(260));GUILayout.Label($"Primary {x.primaryDelta:+0.###;-0.###;0}",GUILayout.Width(150));GUILayout.Label($"Secondary {x.secondaryDelta:+0.###;-0.###;0}",GUILayout.Width(160));GUILayout.Label($"Objective {x.scoreDelta:+0.#####;-0.#####;0}");}if(passiveResult.debug.Count>0){var d=passiveResult.debug[^1];EditorGUILayout.LabelField("Search debug",$"Depth {d.depth}; candidate {d.candidateStates}; unique {d.uniqueStates}; retained {d.retainedStates}; diversity {d.diversityGroups}");}if(GUILayout.Button("EVALUATE OPTIMIZED PASSIVES WITH COMBAT LAB")){playerBuild=passiveResult.build.Clone();combatRequest.player=playerBuild;tab=Tab.CombatLab;}}
            if(marginal.Count>0){Heading("IMMEDIATE MARGINAL VALUE");foreach(var x in marginal.Take(30))using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button(x.name,GUILayout.Width(220)))selectedMarginal=x;GUILayout.Label(x.branch,GUILayout.Width(150));GUILayout.Label($"P {x.primaryDelta:+0.##;-0.##;0}",GUILayout.Width(100));GUILayout.Label($"S {x.secondaryDelta:+0.##;-0.##;0}",GUILayout.Width(100));GUILayout.Label($"Obj {x.objectiveDelta:+0.#####;-0.#####;0}");}if(selectedMarginal!=null&&GUILayout.Button("PING NODE DATA"))PingNode(selectedMarginal.nodeId);}
        }
        void PassiveHeatmap()
        {
            Heading("PASSIVE HEATMAP — ACTUAL AUTHORED LAYOUT");EditorGUILayout.HelpBox("Editor-only overlay. It reads PassiveTreeDefinition.LayoutPosition and never changes node sprites, authored colors, or Branch assets.",MessageType.Info);
            heatmapMode=(HeatmapMode)EditorGUILayout.EnumPopup("Heatmap Mode",heatmapMode);if(marginal.Count==0&&GUILayout.Button("CALCULATE CURRENT BUILD HEATMAP"))Run("Heatmap analysis",_=>marginal=PassiveTreeOptimizer.Analyze(playerBuild,objective,playerConstraints,heatmapMode==HeatmapMode.PathAdjusted));
            heatZoom=EditorGUILayout.Slider("Zoom",heatZoom,.03f,.18f);Rect r=GUILayoutUtility.GetRect(700,700,GUILayout.ExpandWidth(true));EditorGUI.DrawRect(r,new Color(.035f,.04f,.055f));DrawTreeHeatmap(r);
            if(selectedMarginal!=null){EditorGUILayout.HelpBox($"{selectedMarginal.name}\n{selectedMarginal.effect}\nLegal now: {selectedMarginal.immediatelyLegal}\nPrimary {selectedMarginal.primaryDelta:+0.###;-0.###;0}; Secondary {selectedMarginal.secondaryDelta:+0.###;-0.###;0}; Objective {selectedMarginal.objectiveDelta:+0.#####;-0.#####;0}; Path cost {selectedMarginal.pathCost}; Path-adjusted {selectedMarginal.pathAdjustedValue:+0.#####;-0.#####;0}",MessageType.None);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SELECT OWNING BRANCH SO"))PingNode(selectedMarginal.nodeId);if(GUILayout.Button("WHY THIS NODE?"))EditorUtility.DisplayDialog("Why this node?",$"Immediate Primary: {selectedMarginal.primaryDelta:+0.###;-0.###;0}\nImmediate Secondary: {selectedMarginal.secondaryDelta:+0.###;-0.###;0}\nObjective: {selectedMarginal.objectiveDelta:+0.#####;-0.#####;0}\nMinimum legal package: {selectedMarginal.pathCost} point(s)\nPath-adjusted value: {selectedMarginal.pathAdjustedValue:+0.#####;-0.#####;0}","Close");}}
            EditorGUILayout.LabelField("Legend","Blue: no measured value · Yellow: moderate · Red: strongest value · White: optimizer-selected path");
        }
        void ScenarioSweep()
        {
            Heading("END-TO-END PLAYER SCENARIO SWEEP");BuildInputs();ObjectiveInputs();SweepInputs(100);MetricPopup();scenarioPassives=EditorGUILayout.Toggle("Optimize Passives",scenarioPassives);scenarioProgressive=EditorGUILayout.Toggle("Progressive Character",scenarioProgressive);if(scenarioProgressive)scenarioFreeRespec=EditorGUILayout.Toggle("Allow Free Respec",scenarioFreeRespec);passiveBeamWidth=EditorGUILayout.IntSlider("Passive Beam Width",passiveBeamWidth,1,500);if(GUILayout.Button("RUN PROFILE COMPARISON",GUILayout.Height(30)))Run("Scenario sweep",_=>{playerSweep=PlayerScenarioSweep.Run(playerBuild,LoadProfiles(),objective,sweepStart,sweepEnd,sweepIncrement,scenarioPassives,scenarioProgressive,scenarioFreeRespec,passiveBeamWidth,Progress("Scenario"),()=>cancelled);curves=playerSweep.Curves(curveMetric);});DrawPlayerCurves();
        }
        void PlayerVsEnemy()
        {
            Heading("PLAYER vs ENEMY — NEUTRAL ANALYTICAL RATIOS");EditorGUILayout.HelpBox("TTK and TTD are neutral analytical estimates, not simulated encounter duration. Combat Lab will own real fight sequencing.",MessageType.Info);if(playerMetrics==null)playerMetrics=PlayerBuildEvaluator.Evaluate(playerBuild);if(enemyResult==null){EditorGUILayout.HelpBox("Run Enemy Gear Lab first; the comparison reuses that exact generated dataset.",MessageType.Warning);return;}var enemies=enemyResult.samples.OrderBy(x=>x.gearScore).ToList();EnemySample p50=enemies[Mathf.Clamp((int)Math.Round((enemies.Count-1)*.5),0,enemies.Count-1)],p90=enemies[Mathf.Clamp((int)Math.Round((enemies.Count-1)*.9),0,enemies.Count-1)];EditorGUILayout.LabelField("P50 expected TTK",PlayerScenarioSweep.AnalyticalTtk(playerMetrics,p50).ToString("0.###")+" s-equivalent");EditorGUILayout.LabelField("P90 expected TTK",PlayerScenarioSweep.AnalyticalTtk(playerMetrics,p90).ToString("0.###")+" s-equivalent");EditorGUILayout.LabelField("P50 expected TTD",PlayerScenarioSweep.AnalyticalTtd(playerMetrics,p50).ToString("0.###")+" s-equivalent");EditorGUILayout.LabelField("P90 expected TTD",PlayerScenarioSweep.AnalyticalTtd(playerMetrics,p90).ToString("0.###")+" s-equivalent");if(playerSweep!=null){Heading("NORMALIZED CURVE MODE (FIRST POINT = 100)");var normalized=playerSweep.Curves(curveMetric);foreach(var series in normalized){double baseValue=series.points.FirstOrDefault()?.mean??1;if(Math.Abs(baseValue)<1e-9)baseValue=1;foreach(var point in series.points)point.mean=point.mean/baseValue*100;}Rect r=GUILayoutUtility.GetRect(200,420,GUILayout.ExpandWidth(true));chart.Draw(r,normalized,"Player Level","Growth index");}
        }
        void DrawPlayerCurves(){if(playerSweep==null)return;var series=playerSweep.Curves(curveMetric);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("EXPORT SWEEP CSV"))status=WorkbenchExports.SaveSweepCsv(playerSweep,objective);if(GUILayout.Button("EXPORT CURVE PNG"))status=chart.ExportPng(series,"player_"+curveMetric);if(GUILayout.Button("EXPORT RESULT JSON"))status=WorkbenchExports.SaveJson("player_sweep",playerSweep);}Rect r=GUILayoutUtility.GetRect(200,440,GUILayout.ExpandWidth(true));chart.Draw(r,series,"Player Level",OptimizationMetricCatalog.Get(curveMetric).Name);Heading("CLICK-TO-INSPECT DATA");foreach(var p in playerSweep.points)if(GUILayout.Button($"L{p.playerLevel} / CL{p.combatLevel} / {p.profile}: {OptimizationMetricCatalog.Get(curveMetric).Value(p.metrics):0.###}")){playerBuild=p.build.Clone();playerMetrics=p.metrics;tab=Tab.PlayerBuildLab;}}
        void MetricPopup(){string[] names=OptimizationMetricCatalog.All.Select(x=>x.Name).ToArray();int i=Mathf.Max(0,OptimizationMetricCatalog.All.ToList().FindIndex(x=>x.Id==curveMetric));curveMetric=OptimizationMetricCatalog.All[EditorGUILayout.Popup("Curve Metric",i,names)].Id;}
        List<PlayerGearProfileSO> LoadProfiles()=>new[]{"Low","Mid","Optimized"}.Select(x=>AssetDatabase.LoadAssetAtPath<PlayerGearProfileSO>($"Assets/Balance/Profiles/SO_PlayerGearProfile_{x}.asset")).Where(x=>x!=null).ToList();
        void DrawTreeHeatmap(Rect rect)
        {
            double Value(PassiveMarginalResult x)=>heatmapMode switch{HeatmapMode.PrimaryMetric=>x.primaryDelta,HeatmapMode.SecondaryMetric=>x.secondaryDelta,HeatmapMode.PathAdjusted=>x.pathAdjustedValue,HeatmapMode.SelectedPath=>0,_=>x.objectiveDelta};
            var lookup=marginal.ToDictionary(x=>x.nodeId);double max=Math.Max(1e-9,marginal.Select(x=>Math.Abs(Value(x))).DefaultIfEmpty(0).Max());var chosen=new HashSet<string>(passiveResult?.build?.passiveStableIds??playerBuild.passiveStableIds??new());Vector2 center=rect.center+heatPan;
            Handles.BeginGUI();foreach(var e in PassiveTreeDefinition.Edges){Vector2 a=center+PassiveTreeDefinition.Node(e.A).LayoutPosition*heatZoom,b=center+PassiveTreeDefinition.Node(e.B).LayoutPosition*heatZoom;Handles.color=new Color(.25f,.28f,.34f,.45f);Handles.DrawLine(a,b);}Handles.EndGUI();
            foreach(var n in PassiveTreeDefinition.Nodes){Vector2 p=center+n.LayoutPosition*heatZoom;if(!rect.Contains(p))continue;Color c=new(.12f,.24f,.42f);string tip=n.DisplayName;if(lookup.TryGetValue(n.Id,out var v)){double value=Value(v);float t=(float)Math.Clamp(Math.Abs(value)/max,0,1);c=Color.Lerp(new Color(.2f,.45f,.75f),Color.Lerp(Color.yellow,Color.red,t),Mathf.Sqrt(t));tip+=$"\n{heatmapMode}: {value:+0.#####;-0.#####;0}\nPath {v.pathCost}";}if(chosen.Contains(n.StableId))c=Color.white;Rect nr=new(p.x-5,p.y-5,10,10);EditorGUI.DrawRect(nr,c);EditorGUI.LabelField(nr,new GUIContent("",tip));if(Event.current.type==EventType.MouseDown&&nr.Contains(Event.current.mousePosition)){lookup.TryGetValue(n.Id,out selectedMarginal);Event.current.Use();Repaint();}}
        }
        static void PingNode(int id){var n=PassiveTreeDefinition.Node(id);UnityEngine.Object asset=n.IsClassRoute?PassiveTreeDefinition.Database.ClassBranches.FirstOrDefault(x=>x.ClassId==n.RouteClassId):PassiveTreeDefinition.Database.WeaponBranches.FirstOrDefault(x=>x.WeaponId==n.RouteWeaponId);if(asset!=null){Selection.activeObject=asset;EditorGUIUtility.PingObject(asset);}}
        static void Compare(PlayerBuildMetrics a,PlayerBuildMetrics b){foreach(var m in OptimizationMetricCatalog.All){double av=m.Value(a),bv=m.Value(b),pct=Math.Abs(av)<1e-9?0:(bv-av)/Math.Abs(av);EditorGUILayout.LabelField(m.Name,$"A {av:0.###} · B {bv:0.###} · Δ {bv-av:+0.###;-0.###;0} ({pct:+0.##%;-0.##%;0%})");}}
    }
}
