using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using BlackCube.CombatSimulation;
using UnityEditor;
using UnityEngine;

namespace BlackCube.BalanceWorkbench
{
    public sealed partial class BalanceWorkbenchWindow
    {
        CombatLabRequest combatRequest=new();CombatSimulationResult combatSingle;CombatBatchResult combatBatch,combatComparison;CombatMatrixResult combatMatrix;CombatCurveResult combatCurve;List<CombatBatchResult> policyComparisons=new();CombatTraceFilter combatFilter=CombatTraceFilter.All;int timelinePage,curveFightCount=100,curveStart=10,curveEnd=100,curveStep=10,matrixEnemyCount=3;string combatFingerprint;PlayerCombatPolicySO combatPolicy;
        void EnsureCombat()
        {
            EnsureEnemySelection();combatRequest.player=playerBuild;if(string.IsNullOrEmpty(combatRequest.enemyArchetypeId))combatRequest.enemyArchetypeId=EnemyDb.enemyArchetypes[0].stableId;if(string.IsNullOrEmpty(combatRequest.bossId))combatRequest.bossId=EnemyDb.bosses[0].stableId;combatRequest.config??=new CombatSimulationConfig();
        }
        void CombatInputs(bool bossOnly=false)
        {
            EnsureCombat();Heading("PLAYER",$"Tooling 2 snapshot: {combatRequest.player.classId} / {combatRequest.player.subclassId} / {combatRequest.player.weaponTypeId}");EditorGUILayout.LabelField("Build",$"L{combatRequest.player.playerLevel} · CL{combatRequest.player.combatLevel} · {combatRequest.player.equipment.Count} gear · {combatRequest.player.passiveStableIds.Count} passives");if(GUILayout.Button("OPEN PLAYER BUILD"))tab=Tab.PlayerBuildLab;
            Heading("ENEMY");combatRequest.useBoss=bossOnly||EditorGUILayout.Toggle("Boss / Challenge Boss",combatRequest.useBoss);if(combatRequest.useBoss)combatRequest.bossId=PopupValue("Boss",combatRequest.bossId,EnemyDb.bosses.Select(x=>x.stableId).ToArray());else combatRequest.enemyArchetypeId=PopupValue("Archetype",combatRequest.enemyArchetypeId,EnemyDb.enemyArchetypes.Select(x=>x.stableId).ToArray());combatRequest.enemyLevel=EditorGUILayout.IntSlider("Enemy Level",combatRequest.enemyLevel,1,360);combatRequest.rarity=(EnemyAI.EnemyRarity)EditorGUILayout.EnumPopup("Rarity",combatRequest.rarity);combatRequest.corruption=EditorGUILayout.IntSlider("Corruption",combatRequest.corruption,0,100);combatRequest.samplingMode=(EnemySamplingMode)EditorGUILayout.EnumPopup("Enemy Sampling",combatRequest.samplingMode);
            Heading("SIMULATION POLICY");combatRequest.seed=EditorGUILayout.LongField("Base Seed",combatRequest.seed);combatRequest.fightCount=EditorGUILayout.IntField("Fight Count",Mathf.Max(1,combatRequest.fightCount));combatRequest.config.maximumDuration=EditorGUILayout.FloatField("Maximum Duration",combatRequest.config.maximumDuration);combatRequest.config.maximumEvents=EditorGUILayout.IntField("Maximum Events",combatRequest.config.maximumEvents);combatRequest.config.maximumSameTimestampEvents=EditorGUILayout.IntField("Same-Time Event Limit",combatRequest.config.maximumSameTimestampEvents);combatRequest.config.actionPolicy=(PlayerActionPolicy)EditorGUILayout.EnumPopup("Player Action Policy",combatRequest.config.actionPolicy);combatRequest.config.ragePolicy=(RageFinisherPolicy)EditorGUILayout.EnumPopup("Rage Finisher Policy",combatRequest.config.ragePolicy);if(combatRequest.config.actionPolicy==PlayerActionPolicy.ManaConservative)combatRequest.config.manaReserve=EditorGUILayout.Slider("Minimum Mana Reserve",combatRequest.config.manaReserve,0,1);if(combatRequest.config.ragePolicy==RageFinisherPolicy.TargetBelowThreshold)combatRequest.config.rageTargetThreshold=EditorGUILayout.Slider("Finisher Target Life",combatRequest.config.rageTargetThreshold,0,1);
            combatPolicy=(PlayerCombatPolicySO)EditorGUILayout.ObjectField("Policy Preset",combatPolicy,typeof(PlayerCombatPolicySO),false);using(new EditorGUILayout.HorizontalScope()){if(combatPolicy!=null&&GUILayout.Button("APPLY POLICY PRESET")){combatPolicy.ApplyTo(combatRequest.config);status="Applied simulation-only combat policy.";}if(GUILayout.Button("SAVE POLICY AS ASSET"))SaveCombatPolicy();}var errors=CombatLabAdapters.ValidatePolicy(combatRequest);if(errors.Count>0)EditorGUILayout.HelpBox(string.Join("\n",errors),MessageType.Warning);
        }
        void CombatLab()
        {
            Heading("HEADLESS COMBAT LAB","Event-driven full-production mode. Player policy is a simulation assumption and never changes gameplay controls.");CombatInputs();var errors=CombatLabAdapters.ValidatePolicy(combatRequest);using(new EditorGUI.DisabledScope(errors.Count>0))using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("RUN ONE FIGHT",GUILayout.Height(34)))Run("Single combat",_=>{combatRequest.config.retainTrace=true;combatSingle=CombatLabAdapters.Single(combatRequest);combatFingerprint=combatSingle.fingerprint;tab=Tab.CombatTimeline;});if(GUILayout.Button("RUN BATCH",GUILayout.Height(34)))Run("Combat batch",_=>{combatRequest.config.retainTrace=false;combatBatch=CombatLabAdapters.Batch(combatRequest,Progress("Combat fights"),()=>cancelled);combatFingerprint=combatBatch.fingerprint;});if(GUILayout.Button("COMPARE BUILT-IN POLICIES"))RunPolicyComparison();if(combatBatch!=null&&GUILayout.Button("STORE AS COMPARISON"))combatComparison=JsonUtility.FromJson<CombatBatchResult>(JsonUtility.ToJson(combatBatch));}using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("LOAD EXPERIMENT PRESET"))LoadCombatPreset();if(GUILayout.Button("LOAD TRACE JSON"))LoadCombatTrace();}
            if(combatBatch!=null)DrawBatch(combatBatch);if(combatBatch!=null&&combatComparison!=null){Heading("COMBAT RESULT COMPARISON");EditorGUILayout.LabelField("Win Rate Delta",(combatBatch.winRate-combatComparison.winRate).ToString("+0.00%;-0.00%;0.00%"));EditorGUILayout.LabelField("Median Duration Delta",(combatBatch.duration.p50-combatComparison.duration.p50).ToString("+0.###;-0.###;0"));EditorGUILayout.LabelField("P90 Duration Delta",(combatBatch.duration.p90-combatComparison.duration.p90).ToString("+0.###;-0.###;0"));EditorGUILayout.LabelField("Mana Starvation Delta",(combatBatch.manaStarvation.mean-combatComparison.manaStarvation.mean).ToString("+0.00%;-0.00%;0.00%"));}
            if(policyComparisons.Count>0){Heading("POLICY COMPARISON");foreach(var x in policyComparisons)EditorGUILayout.LabelField($"{x.request.config.actionPolicy} / {x.request.config.ragePolicy}",$"Win {x.winRate:P1} · DPS {x.playerDps.mean:0.##} · P50 {x.duration.p50:0.##}s · Starved {x.manaStarvation.mean:P1}");}
        }
        void DrawBatch(CombatBatchResult r)
        {
            Heading("BATCH OUTCOME");if(r.fingerprint!=ProductionBalanceAdapters.DataFingerprint())EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);EditorGUILayout.LabelField("Win / Loss / Timeout / Error",$"{r.winRate:P2} / {r.lossRate:P2} / {r.timeoutRate:P2} / {r.errors}");EditorGUILayout.LabelField("Duration",$"Mean {r.duration.mean:0.###} · P10 {r.duration.p10:0.###} · P50 {r.duration.p50:0.###} · P90 {r.duration.p90:0.###} · P95 {r.duration.p95:0.###} · P99 {r.duration.p99:0.###}");EditorGUILayout.LabelField("Remaining Life",$"Player win P50 {r.playerLifeOnWin.p50:0.##} · Enemy loss P50 {r.enemyLifeOnLoss.p50:0.##}");EditorGUILayout.LabelField("Player DPS / Mana Starvation",$"{r.playerDps.mean:0.##} / {r.manaStarvation.mean:P2}");
            Heading("DAMAGE CONTRIBUTION");double total=r.damage.Sum(x=>x.total);foreach(var x in r.damage.OrderByDescending(x=>x.total))EditorGUILayout.LabelField(x.id,$"{x.total:0.##} · {(total<=0?0:x.total/total):P1}");Heading("DAMAGE BY TYPE");foreach(var x in r.damageByType.OrderByDescending(x=>x.total))EditorGUILayout.LabelField(x.id,x.total.ToString("0.##"));Heading("HEALING / SUSTAIN");foreach(var x in r.healing.OrderByDescending(x=>x.effective))EditorGUILayout.LabelField(x.id,$"Effective {x.effective:0.##} · Overheal {x.overheal:0.##}");Heading("AILMENTS / SKILLS");foreach(var x in r.ailments)EditorGUILayout.LabelField(x.id,$"Applications {x.applications} · Damage {x.damage:0.##} · Uptime {x.uptime:0.##}s · Stack-time {x.stackTime:0.##} · Max stacks {x.maxStacks} · Max effect {x.maximumEffect:P1}");foreach(var x in r.skills)EditorGUILayout.LabelField(x.id,$"Activations {x.activations} · Resolves {x.resolves} · Damage {x.damage:0.##} · Mana delays {x.manaFailures} · Bypasses {x.cooldownBypasses}");foreach(var x in r.enemySkills)EditorGUILayout.LabelField("Enemy/"+x.id,$"Uses {x.resolves} · Damage {x.damage:0.##}");if(r.phaseTime.Count>0){Heading("BOSS PHASE TIME");foreach(var x in r.phaseTime)EditorGUILayout.LabelField(x.id,$"{x.total:0.##}s");}if(r.durationSamples.Count>0)DrawHistogram("Fight Duration Distribution",r.durationSamples);
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("REPLAY FASTEST WIN"))ReplaySeed(r.fastestWinSeed);if(GUILayout.Button("REPLAY SLOWEST WIN"))ReplaySeed(r.slowestWinSeed);if(GUILayout.Button("REPLAY CLOSEST WIN"))ReplaySeed(r.closestWinSeed);if(GUILayout.Button("REPLAY WORST LOSS"))ReplaySeed(r.worstLossSeed);if(GUILayout.Button("REPLAY RANDOM LOSS"))ReplaySeed(r.randomLossSeed);}using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("EXPORT BATCH CSV"))status=WorkbenchExports.SaveCombatBatchCsv(r);if(GUILayout.Button("EXPORT RESULT JSON"))status=WorkbenchExports.SaveJson("combat_batch",r);if(GUILayout.Button("SAVE EXPERIMENT PRESET"))status=WorkbenchExports.SaveJson("combat_experiment",combatRequest);}
        }
        void ReplaySeed(long seed){if(seed==0){status="No matching outlier seed.";return;}combatSingle=CombatLabAdapters.Replay(combatRequest,seed);combatFingerprint=combatSingle.fingerprint;tab=Tab.CombatTimeline;}
        void CombatTimeline()
        {
            Heading("COMBAT TIMELINE / FIGHT INSPECTOR");if(combatSingle==null){EditorGUILayout.HelpBox("Run one fight or replay a batch outlier first.",MessageType.Info);return;}if(combatSingle.fingerprint!=ProductionBalanceAdapters.DataFingerprint())EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);EditorGUILayout.LabelField("Outcome",$"{combatSingle.outcome} at {combatSingle.duration:0.###}s · Seed {combatSingle.seed} · Events {combatSingle.eventCount}");EditorGUILayout.LabelField("Final Player",$"Life {combatSingle.playerLife:0.##} · Mana {combatSingle.playerMana:0.##} · Rage {combatSingle.playerRage:0.##}");EditorGUILayout.LabelField("Final Enemy",$"Life {combatSingle.enemyLife:0.##}");combatFilter=(CombatTraceFilter)EditorGUILayout.EnumFlagsField("Event Filters",combatFilter);var filtered=combatSingle.trace.Where(x=>(x.category&combatFilter)!=0).ToList();int pages=Math.Max(1,(filtered.Count+199)/200);timelinePage=EditorGUILayout.IntSlider("Timeline Page",Mathf.Clamp(timelinePage,0,pages-1),0,pages-1);foreach(var x in filtered.Skip(timelinePage*200).Take(200))if(GUILayout.Button($"{x.time,7:0.000}s  {x.type,-18} {x.source} → {x.target}  {x.action}  {x.amount:0.##}")){EditorUtility.DisplayDialog("Why Did This Happen?",$"Reason: {x.reason}\nRule: {x.ruleId}\nPhase: {x.phase}\nRoll/Chance: {x.roll:0.####}/{x.chance:0.####}\nLife: {x.lifeBefore:0.##} → {x.lifeAfter:0.##}\nMana: {x.manaBefore:0.##} → {x.manaAfter:0.##}\nRage: {x.rageBefore:0.##} → {x.rageAfter:0.##}\nProjectile: {x.projectileIndex}\nStacks: {x.stackCount}","Close");}
            Heading("DEATH SUMMARY");foreach(var x in combatSingle.trace.Where(x=>(x.category&CombatTraceFilter.Damage)!=0).TakeLast(10))EditorGUILayout.LabelField($"{x.time:0.000}s {x.action}",$"{x.amount:0.##} ({x.lifeBefore:0.##} → {x.lifeAfter:0.##})");using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("RERUN SAME SEED"))combatSingle=CombatLabAdapters.Replay(combatRequest,combatSingle.seed);if(GUILayout.Button("LOAD TRACE"))LoadCombatTrace();if(GUILayout.Button("EXPORT TIMELINE CSV"))status=WorkbenchExports.SaveCombatTimelineCsv(combatSingle);if(GUILayout.Button("EXPORT TRACE JSON"))status=WorkbenchExports.SaveJson("combat_trace",combatSingle);}
            var life=new CurveSeries{name="Life events",color=Color.green};foreach(var x in combatSingle.trace.Where(x=>x.lifeBefore!=0||x.lifeAfter!=0))life.points.Add(new CurvePoint{x=x.time,mean=x.lifeAfter});if(life.points.Count>0){Rect rect=GUILayoutUtility.GetRect(200,320,GUILayout.ExpandWidth(true));chart.Draw(rect,new List<CurveSeries>{life},"Seconds","Life after event");}
        }
        void BatchMatchups()
        {
            EnsureCombat();Heading("BUILD-vs-ENEMY MATRIX");EditorGUILayout.HelpBox("Uses the current Tooling 2 build against selected production archetypes. Click a cell to open that exact matchup in Combat Lab.",MessageType.Info);combatRequest.fightCount=EditorGUILayout.IntSlider("Fights / Cell",combatRequest.fightCount,1,1000);matrixEnemyCount=EditorGUILayout.IntSlider("Enemy Columns",matrixEnemyCount,1,Mathf.Min(12,EnemyDb.enemyArchetypes.Count));if(GUILayout.Button("RUN SIMPLE MATCHUP MATRIX",GUILayout.Height(30)))Run("Matchup matrix",_=>{combatMatrix=new CombatMatrixResult{fingerprint=ProductionBalanceAdapters.DataFingerprint()};var ids=EnemyDb.enemyArchetypes.Take(matrixEnemyCount).ToList();for(int i=0;i<ids.Count;i++){var request=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));request.enemyArchetypeId=ids[i].stableId;request.useBoss=false;var batch=CombatLabAdapters.Batch(request,Progress("Matrix cells"),()=>cancelled);combatMatrix.cells.Add(new CombatMatrixCell{player=request.player.classId+"/"+request.player.weaponTypeId,enemy=ids[i].displayName,winRate=batch.winRate,medianDuration=batch.duration.p50,medianPlayerLife=batch.playerLifeOnWin.p50,timeoutRate=batch.timeoutRate,seed=request.seed});}});if(combatMatrix!=null){foreach(var cell in combatMatrix.cells){Color old=GUI.backgroundColor;GUI.backgroundColor=Color.Lerp(new Color(.8f,.2f,.2f),new Color(.2f,.8f,.3f),(float)cell.winRate);if(GUILayout.Button($"{cell.player} vs {cell.enemy}: Win {cell.winRate:P1} · P50 {cell.medianDuration:0.##}s")){combatRequest.enemyArchetypeId=EnemyDb.enemyArchetypes.First(x=>x.displayName==cell.enemy).stableId;tab=Tab.CombatLab;}GUI.backgroundColor=old;}if(GUILayout.Button("EXPORT MATCHUP MATRIX CSV"))status=WorkbenchExports.SaveCombatMatrixCsv(combatMatrix);}
        }
        void BossLab()
        {
            Heading("BOSS / CHALLENGE COMBAT LAB");CombatInputs(true);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("RUN BOSS FIGHT")){combatSingle=CombatLabAdapters.Single(combatRequest);tab=Tab.CombatTimeline;}if(GUILayout.Button("RUN BOSS BATCH"))Run("Boss batch",_=>combatBatch=CombatLabAdapters.Batch(combatRequest,Progress("Boss fights"),()=>cancelled));if(GUILayout.Button("CORRUPTION SWEEP"))RunCorruptionSweep();}if(combatBatch!=null)DrawBatch(combatBatch);
        }
        void CombatCurves()
        {
            EnsureCombat();Heading("COMBAT LEVEL / PROFILE SWEEPS");curveStart=EditorGUILayout.IntSlider("Start Level",curveStart,1,360);curveEnd=EditorGUILayout.IntSlider("End Level",curveEnd,curveStart,360);curveStep=EditorGUILayout.IntSlider("Step",curveStep,1,50);curveFightCount=EditorGUILayout.IntSlider("Fights / Point",curveFightCount,1,1000);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("RUN COMBAT CURVE",GUILayout.Height(30)))RunCombatLevelCurve();if(GUILayout.Button("RARITY SWEEP",GUILayout.Height(30)))RunRaritySweep();if(GUILayout.Button("LOW / MID / OPTIMIZED",GUILayout.Height(30)))RunGearProfileSweep();}if(combatCurve!=null){var series=new List<CurveSeries>{Series("Win Rate",Color.green,combatCurve.points,x=>x.winRate*100),Series("P50 Duration",Color.cyan,combatCurve.points,x=>x.p50Duration),Series("P90 Duration",Color.yellow,combatCurve.points,x=>x.p90Duration),Series("Mana Starvation",Color.magenta,combatCurve.points,x=>x.manaStarvation*100)};Rect r=GUILayoutUtility.GetRect(200,420,GUILayout.ExpandWidth(true));chart.Draw(r,series,"Level / Category","Metric (percent/seconds)");using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("EXPORT COMBAT CURVE CSV"))status=WorkbenchExports.SaveCombatCurveCsv(combatCurve);if(GUILayout.Button("EXPORT COMBAT CURVE JSON"))status=WorkbenchExports.SaveJson("combat_curve",combatCurve);if(GUILayout.Button("EXPORT CHART PNG"))status=chart.ExportPng(series,"combat_curve");}}
        }
        void RunCorruptionSweep(){Run("Corruption sweep",_=>{combatCurve=new CombatCurveResult{name="Corruption sweep",fingerprint=ProductionBalanceAdapters.DataFingerprint()};int i=0;foreach(int corruption in new[]{0,20,40,60,80,100}){var request=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));request.corruption=corruption;var b=CombatLabAdapters.Batch(request,null,()=>cancelled);combatCurve.points.Add(new CombatCurvePoint{level=corruption,winRate=b.winRate,p50Duration=b.duration.p50,p90Duration=b.duration.p90,remainingLife=b.playerLifeOnWin.p50,manaStarvation=b.manaStarvation.mean});Progress("Corruption tiers")(++i/6f);}tab=Tab.CombatCurves;});}
        void RunCombatLevelCurve(){Run("Combat curve",_=>{combatCurve=new CombatCurveResult{name=combatRequest.player.classId+" vs "+combatRequest.enemyArchetypeId,fingerprint=ProductionBalanceAdapters.DataFingerprint()};int count=(curveEnd-curveStart)/curveStep+1,index=0;for(int level=curveStart;level<=curveEnd;level+=curveStep){var request=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));request.player.playerLevel=level;request.player.combatLevel=level;request.enemyLevel=level;request.fightCount=curveFightCount;var batch=CombatLabAdapters.Batch(request,null,()=>cancelled);double damage=batch.damage.Sum(x=>x.total),ailment=batch.damage.Where(x=>x.id.Contains("Poison")||x.id.Contains("Bleed")||x.id.Contains("Ignite")).Sum(x=>x.total);combatCurve.points.Add(new CombatCurvePoint{level=level,winRate=batch.winRate,p50Duration=batch.duration.p50,p90Duration=batch.duration.p90,remainingLife=batch.playerLifeOnWin.p50,manaStarvation=batch.manaStarvation.mean,ailmentShare=damage<=0?0:ailment/damage});Progress("Combat curve")(++index/(float)count);}});}
        void RunRaritySweep(){Run("Rarity sweep",_=>{combatCurve=new CombatCurveResult{name="Enemy rarity sweep (0 Normal, 1 Magic, 2 Rare, 3 Legendary)",fingerprint=ProductionBalanceAdapters.DataFingerprint()};int i=0;foreach(EnemyAI.EnemyRarity rarity in Enum.GetValues(typeof(EnemyAI.EnemyRarity))){var request=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));request.useBoss=false;request.rarity=rarity;request.fightCount=curveFightCount;request.samplingMode=EnemySamplingMode.Population;var b=CombatLabAdapters.Batch(request,null,()=>cancelled);combatCurve.points.Add(new CombatCurvePoint{level=(int)rarity,winRate=b.winRate,p50Duration=b.duration.p50,p90Duration=b.duration.p90,remainingLife=b.playerLifeOnWin.p50,manaStarvation=b.manaStarvation.mean});Progress("Rarity sweep")(++i/4f);}});}
        void RunGearProfileSweep(){Run("Gear profile combat sweep",_=>{combatCurve=new CombatCurveResult{name="Player gear profiles (0 Low, 1 Mid, 2 Optimized)",fingerprint=ProductionBalanceAdapters.DataFingerprint()};var profiles=LoadProfiles();for(int i=0;i<profiles.Count;i++){var template=combatRequest.player.Clone();template.equipment.Clear();var optimized=PlayerGearsetOptimizer.Optimize(template,profiles[i],objective,profiles[i].selectionStrategy==PlayerGearSelectionStrategy.FullGearsetBeamSearch);var request=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));request.player=optimized.build;request.fightCount=curveFightCount;var b=CombatLabAdapters.Batch(request,null,()=>cancelled);combatCurve.points.Add(new CombatCurvePoint{level=i,winRate=b.winRate,p50Duration=b.duration.p50,p90Duration=b.duration.p90,remainingLife=b.playerLifeOnWin.p50,manaStarvation=b.manaStarvation.mean});Progress("Gear profiles")((i+1f)/profiles.Count);}});}
        void RunPolicyComparison(){Run("Policy comparison",_=>{policyComparisons.Clear();foreach(PlayerActionPolicy policy in Enum.GetValues(typeof(PlayerActionPolicy))){var request=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));request.config.actionPolicy=policy;request.fightCount=Mathf.Min(request.fightCount,1000);policyComparisons.Add(CombatLabAdapters.Batch(request,null,()=>cancelled));}});}
        void LoadCombatPreset(){string path=EditorUtility.OpenFilePanel("Load Combat Experiment","Logs","json");if(string.IsNullOrEmpty(path))return;try{combatRequest=JsonUtility.FromJson<CombatLabRequest>(File.ReadAllText(path))??new CombatLabRequest();status="Loaded combat experiment: "+path;}catch(Exception ex){status="Could not load combat experiment: "+ex.Message;}}
        void LoadCombatTrace(){string path=EditorUtility.OpenFilePanel("Load Combat Trace","Logs","json");if(string.IsNullOrEmpty(path))return;try{combatSingle=JsonUtility.FromJson<CombatSimulationResult>(File.ReadAllText(path));if(combatSingle==null)throw new InvalidDataException("File did not contain a combat trace.");combatFingerprint=combatSingle.fingerprint;timelinePage=0;tab=Tab.CombatTimeline;status="Loaded trace without rerunning: "+path;}catch(Exception ex){status="Could not load combat trace: "+ex.Message;}}
        static CurveSeries Series(string name,Color color,IEnumerable<CombatCurvePoint> points,Func<CombatCurvePoint,double> value)=>new(){name=name,color=color,points=points.Select(x=>new CurvePoint{x=x.level,mean=value(x)}).ToList()};
        void SaveCombatPolicy(){Directory.CreateDirectory("Assets/Balance/CombatPolicies");string path=AssetDatabase.GenerateUniqueAssetPath("Assets/Balance/CombatPolicies/SO_CombatPolicy.asset");var asset=CreateInstance<PlayerCombatPolicySO>();asset.actionPolicy=combatRequest.config.actionPolicy;asset.ragePolicy=combatRequest.config.ragePolicy;asset.minimumManaReserve=combatRequest.config.manaReserve;asset.finisherTargetLife=combatRequest.config.rageTargetThreshold;AssetDatabase.CreateAsset(asset,path);AssetDatabase.SaveAssets();combatPolicy=asset;Selection.activeObject=asset;status="Saved simulation policy: "+path;}
    }
}
