using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace BlackCube.BalanceWorkbench
{
    public sealed partial class BalanceWorkbenchWindow
    {
        SensitivityRequest sensitivity=new(); SensitivityResult sensitivityResult; List<SensitivityPair> sensitivityPairs=new();List<CurvePoint> sensitivityCurve=new();
        enum ImpactSort{Absolute,MostPositive,MostNegative}
        StatTypes curveStat=StatTypes.AttackSpeed; bool[] chosenStats;ImpactSort impactSort;
        BalanceSuite balanceSuite=new();BalanceSnapshot beforeSnapshot,afterSnapshot;List<BalanceDifference> differences=new();List<SnapshotWidgetDifference> widgetDifferences=new();double highlightPercent=.10;string snapshotName="Before";
        enum BreakSource{PlayerAnalytical,EnemyGear,Combat,Drops,LootProgression}
        int breakStart=1,breakEnd=100,breakStep=10;double breakThreshold=.70;BreakpointOperator breakOperator=BreakpointOperator.Less;string breakMetric="win_rate";BreakSource breakSource=BreakSource.Combat;bool breakAll,breakBatchClasses=true,breakBatchRarities;List<BreakpointResult> breakResults=new();List<BreakpointBatchRow> breakBatchResults=new();BreakpointSampleBudget breakBudget=new();
        string reportTitle="Balance review";string reportPath;BalanceReportPreset reportPreset=new();BalanceReportRun reportRun;bool useAfterSnapshot;
        AffixAnalysisRequest affixRequest=new();AffixAnalysisResult affixResult;List<AffixCombatRow> affixCombat=new();int affixCombatCount=5;
        LootProgressionRequest lootRequest=new();LootProgressionResult lootResult;FirstUpgradeDistribution firstUpgradeResult;ProgressiveIntervalDistribution intervalResult;List<LootProgressionResult> lootComparison=new();List<LootProgressionSweepRow> lootWorldSweep=new();int lootComparisonKills=1000,firstUpgradeTrials=100,firstUpgradeMaxKills=1000,firstUpgradeCustomThreshold=750,intervalTrials=100,intervalKills=1000,lootSweepStart=1,lootSweepEnd=360,sweepStep=10,sweepLoops=2,sweepFirstTrials=10;LootSweepBuildSource sweepBuildSource=LootSweepBuildSource.Mid;
        CraftingSimulationRequest craftingRequest=new();CraftingSimulationResult craftingResult;List<CraftingSimulationRequest> craftPolicies=new();List<CraftingSimulationResult> craftComparisons=new();CraftPolicySearchRequest craftSearch=new();CraftPolicySearchResult craftSearchResult;int craftValidationTrials=1000;

        void SensitivityTab()
        {
            Heading("PRODUCTION STAT SENSITIVITY");EditorGUILayout.HelpBox("Absolute inputs are flat points or fraction-of-one percentage points according to the selected stat. Relative inputs scale the current measured stat; a zero baseline uses a one-unit reference. Analytical mode evaluates the production build; combat mode uses common fight seeds.",MessageType.Info);
            sensitivity.mode=(SensitivityMode)EditorGUILayout.EnumPopup("Mode",sensitivity.mode);sensitivity.perturbation=(PerturbationMode)EditorGUILayout.EnumPopup("Change",sensitivity.perturbation);sensitivity.amount=EditorGUILayout.FloatField("Input change",sensitivity.amount);using(new EditorGUILayout.HorizontalScope()){foreach(float preset in new[]{-.1f,-.05f,.01f,.05f,.10f})if(GUILayout.Button(preset.ToString("+0%;-0%")))sensitivity.amount=preset;}
            string[] metrics=sensitivity.mode==SensitivityMode.Combat?new[]{"win_rate","p50_ttk","p90_ttk","mana_starvation","combat_dps"}:OptimizationMetricCatalog.All.Select(x=>x.Id).ToArray();sensitivity.metric=metrics[EditorGUILayout.Popup("Output metric",Mathf.Max(0,Array.IndexOf(metrics,sensitivity.metric)),metrics)];
            if(sensitivity.mode==SensitivityMode.Combat){EnsureCombat();combatRequest.fightCount=EditorGUILayout.IntField("Fights / variation",Mathf.Max(1,combatRequest.fightCount));combatRequest.seed=EditorGUILayout.LongField("Common seed",combatRequest.seed);}
            if(chosenStats==null||chosenStats.Length!=SensitivityAnalyzer.Catalog.Length){chosenStats=new bool[SensitivityAnalyzer.Catalog.Length];for(int i=0;i<chosenStats.Length;i++)chosenStats[i]=sensitivity.stats.Contains(SensitivityAnalyzer.Catalog[i]);}
            Heading("SELECT STATS");for(int i=0;i<SensitivityAnalyzer.Catalog.Length;i++){var stat=SensitivityAnalyzer.Catalog[i];chosenStats[i]=EditorGUILayout.ToggleLeft(stat+" ("+SensitivityAnalyzer.Unit(stat)+")",chosenStats[i]);}
            using(new EditorGUILayout.HorizontalScope())
            {
                if(GUILayout.Button("RUN SENSITIVITY",GUILayout.Height(30)))Run("Sensitivity",_=>{sensitivity.build=playerBuild.Clone();sensitivity.combat=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));sensitivity.stats=SensitivityAnalyzer.Catalog.Where((s,i)=>chosenStats[i]).ToList();sensitivityResult=SensitivityAnalyzer.Run(sensitivity,Progress("Stats"),()=>cancelled);});
                if(GUILayout.Button("PAIR ANALYSIS"))Run("Pair analysis",_=>{sensitivity.build=playerBuild.Clone();sensitivity.stats=SensitivityAnalyzer.Catalog.Where((s,i)=>chosenStats[i]).Take(12).ToList();sensitivityPairs=SensitivityAnalyzer.Pairs(sensitivity,sensitivity.stats,()=>cancelled);});
                if(GUILayout.Button("CURVE"))Run("Sensitivity curve",_=>{sensitivity.build=playerBuild.Clone();sensitivityCurve=SensitivityAnalyzer.Curve(sensitivity,curveStat,new[]{-.2f,-.1f,0f,.1f,.2f,.3f});});
            }
            curveStat=(StatTypes)EditorGUILayout.EnumPopup("Curve stat",curveStat);
            if(sensitivityResult!=null){if(sensitivityResult.Stale)EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);Heading("RANKED IMPACT");impactSort=(ImpactSort)EditorGUILayout.EnumPopup("Sort",impactSort);var ordered=impactSort switch{ImpactSort.MostPositive=>sensitivityResult.rows.OrderByDescending(x=>x.absoluteDelta),ImpactSort.MostNegative=>sensitivityResult.rows.OrderBy(x=>x.absoluteDelta),_=>sensitivityResult.rows.OrderByDescending(x=>Math.Abs(x.absoluteDelta))};foreach(var x in ordered)EditorGUILayout.LabelField(x.stat.ToString(),$"{x.baseline:0.###} → {x.modified:0.###}  Δ{x.absoluteDelta:+0.###;-0.###;0}  {x.percentDelta:+0.##%;-0.##%;0%}  elasticity {x.elasticity:0.###}");if(GUILayout.Button("EXPORT CSV"))status=SaveAdvancedCsv("sensitivity","Stat,InputDelta,Baseline,Modified,AbsoluteDelta,PercentDelta,Elasticity",sensitivityResult.rows.Select(x=>$"{x.stat},{x.inputDelta:R},{x.baseline:R},{x.modified:R},{x.absoluteDelta:R},{x.percentDelta:R},{x.elasticity:R}"));}
            if(sensitivityCurve.Count>0){Heading("MULTI-POINT CURVE");foreach(var x in sensitivityCurve)EditorGUILayout.LabelField(x.x.ToString("+0%;-0%;0%"),x.mean.ToString("0.####"));var series=new List<CurveSeries>{new(){name=curveStat.ToString(),color=Color.cyan,points=sensitivityCurve}};chart.Draw(GUILayoutUtility.GetRect(200,260,GUILayout.ExpandWidth(true)),series,"Stat change",sensitivity.metric);if(GUILayout.Button("EXPORT CURVE PNG"))status=chart.ExportPng(series,"sensitivity_curve");}
            if(sensitivityPairs.Count>0){Heading("PAIR INTERACTIONS (observed − A − B)");foreach(var x in sensitivityPairs)EditorGUILayout.LabelField(x.a+" × "+x.b,x.interaction.ToString("+0.####;-0.####;0"));if(GUILayout.Button("EXPORT PAIRS CSV"))status=SaveAdvancedCsv("sensitivity_pairs","StatA,StatB,GainA,GainB,Observed,Interaction",sensitivityPairs.Select(x=>$"{x.a},{x.b},{x.gainA:R},{x.gainB:R},{x.observed:R},{x.interaction:R}"));}
            if(GUILayout.Button("SEND TO COMBAT LAB"))tab=Tab.CombatLab;
        }

        void SnapshotTab()
        {
            Heading("USER-EDITABLE SCENARIO SUITE");balanceSuite.name=EditorGUILayout.TextField("Suite",balanceSuite.name);snapshotName=EditorGUILayout.TextField("Snapshot name",snapshotName);highlightPercent=EditorGUILayout.DoubleField("Highlight relative change",highlightPercent);
            if(GUILayout.Button("ADD CURRENT PLAYER SCENARIO"))balanceSuite.scenarios.Add(new BalanceScenario{name="Player "+playerBuild.classId+" L"+playerBuild.playerLevel,build=playerBuild.Clone(),metric=objective.primary});
            if(GUILayout.Button("ADD CURRENT COMBAT SCENARIO")){EnsureCombat();balanceSuite.scenarios.Add(new BalanceScenario{name="Combat L"+combatRequest.enemyLevel,source="Combat",metric="win_rate",combat=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest))});}
            if(GUILayout.Button("ADD CURRENT DROP SCENARIO"))balanceSuite.scenarios.Add(new BalanceScenario{name="Drops L"+drop.level,source="Drops",metric="currency_per_kill",drop=JsonUtility.FromJson<DropLabRequest>(JsonUtility.ToJson(drop))});
            if(GUILayout.Button("ADD SENSITIVITY SCENARIO")){var r=JsonUtility.FromJson<SensitivityRequest>(JsonUtility.ToJson(sensitivity));r.build=playerBuild.Clone();balanceSuite.scenarios.Add(new BalanceScenario{name="Sensitivity "+playerBuild.classId,source="Sensitivity",metric="max_absolute_impact",sensitivity=r});}
            if(GUILayout.Button("ADD AFFIX SCENARIO")){var r=JsonUtility.FromJson<AffixAnalysisRequest>(JsonUtility.ToJson(affixRequest));r.build=playerBuild.Clone();balanceSuite.scenarios.Add(new BalanceScenario{name="Affix "+r.slot,source="Affix",metric="best_objective_delta",affix=r});}
            if(GUILayout.Button("ADD LOOT SCENARIO")){var r=JsonUtility.FromJson<LootProgressionRequest>(JsonUtility.ToJson(lootRequest));r.build=playerBuild.Clone();balanceSuite.scenarios.Add(new BalanceScenario{name="Loot L"+r.combatLevel,source="Loot Progression",metric="upgrades_per_100",loot=r});}
            if(craftingRequest.item!=null&&GUILayout.Button("ADD CRAFTING SCENARIO"))balanceSuite.scenarios.Add(new BalanceScenario{name="Crafting "+craftingRequest.item.slot,source="Crafting",metric="success_rate",crafting=JsonUtility.FromJson<CraftingSimulationRequest>(JsonUtility.ToJson(craftingRequest))});
            for(int i=0;i<balanceSuite.scenarios.Count;i++){var s=balanceSuite.scenarios[i];using(new EditorGUILayout.HorizontalScope()){s.name=EditorGUILayout.TextField(s.name);s.metric=EditorGUILayout.TextField(s.metric);s.widgetKind=(BalanceWidgetKind)EditorGUILayout.EnumPopup(s.widgetKind,GUILayout.Width(110));if(GUILayout.Button("Remove",GUILayout.Width(70))){balanceSuite.scenarios.RemoveAt(i--);continue;}}if(s.widgetKind is BalanceWidgetKind.Curve or BalanceWidgetKind.Breakpoint or BalanceWidgetKind.Distribution){using(new EditorGUILayout.HorizontalScope()){s.startLevel=EditorGUILayout.IntField("Start",s.startLevel);s.endLevel=EditorGUILayout.IntField("End / limit",s.endLevel);s.increment=EditorGUILayout.IntField("Step",s.increment);}}if(s.widgetKind==BalanceWidgetKind.Distribution)s.sampleCount=EditorGUILayout.IntField("Trials",s.sampleCount);if(s.widgetKind==BalanceWidgetKind.Breakpoint){s.threshold=EditorGUILayout.DoubleField("Threshold",s.threshold);s.breakpointOperator=(BreakpointOperator)EditorGUILayout.EnumPopup("Operator",s.breakpointOperator);}}
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("CAPTURE BEFORE",GUILayout.Height(30)))Run("Snapshot before",_=>beforeSnapshot=BalanceSnapshotService.Capture(balanceSuite,snapshotName,Progress("Suite"),()=>cancelled));if(GUILayout.Button("CAPTURE AFTER"))Run("Snapshot after",_=>{afterSnapshot=BalanceSnapshotService.Capture(balanceSuite,snapshotName,Progress("Suite"),()=>cancelled);if(beforeSnapshot!=null){differences=BalanceSnapshotService.Compare(beforeSnapshot,afterSnapshot,highlightPercent);widgetDifferences=BalanceSnapshotWidgets.Compare(beforeSnapshot,afterSnapshot);}});if(GUILayout.Button("COMPARE TO CURRENT")&&beforeSnapshot!=null)Run("Compare current",_=>{afterSnapshot=BalanceSnapshotService.Capture(beforeSnapshot.suite,"Current production",Progress("Suite"),()=>cancelled);differences=BalanceSnapshotService.Compare(beforeSnapshot,afterSnapshot,highlightPercent);widgetDifferences=BalanceSnapshotWidgets.Compare(beforeSnapshot,afterSnapshot);});}
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SAVE SUITE JSON"))status=WorkbenchExports.SaveJson("balance_suite",balanceSuite);if(GUILayout.Button("LOAD SUITE JSON")){string path=EditorUtility.OpenFilePanel("Load balance suite",WorkbenchExports.Root,"json");if(!string.IsNullOrEmpty(path))balanceSuite=JsonUtility.FromJson<BalanceSuite>(File.ReadAllText(path));}if(GUILayout.Button("LOAD BEFORE JSON")){string path=EditorUtility.OpenFilePanel("Load balance snapshot",WorkbenchExports.Root,"json");if(!string.IsNullOrEmpty(path))beforeSnapshot=JsonUtility.FromJson<BalanceSnapshot>(File.ReadAllText(path));}}
            if(beforeSnapshot!=null){EditorGUILayout.LabelField("Before",beforeSnapshot.timestampUtc+" · "+beforeSnapshot.fingerprint);if(beforeSnapshot.fingerprint!=ProductionBalanceAdapters.DataFingerprint())EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);if(GUILayout.Button("EXPORT BEFORE JSON"))status=WorkbenchExports.SaveJson("snapshot_before",beforeSnapshot);}
            if(afterSnapshot!=null){EditorGUILayout.LabelField("After",afterSnapshot.timestampUtc+" · "+afterSnapshot.fingerprint);if(GUILayout.Button("EXPORT AFTER JSON"))status=WorkbenchExports.SaveJson("snapshot_after",afterSnapshot);}
            if(differences.Count>0){Heading("REGRESSION COMPARISON");foreach(var x in differences){using(new EditorGUILayout.HorizontalScope()){EditorGUILayout.LabelField((x.highlighted?"▲ ":"")+x.scenario+" / "+x.metric,$"{x.before:0.###} → {x.after:0.###} ({x.percent:+0.##%;-0.##%;0%})");if(GUILayout.Button("OPEN SOURCE",GUILayout.Width(105)))OpenBalanceScenario(afterSnapshot?.suite?.scenarios.FirstOrDefault(s=>s.name==x.scenario&&s.source==x.source&&s.metric==x.metric));}}if(GUILayout.Button("EXPORT COMPARISON CSV"))status=SaveAdvancedCsv("snapshot_comparison","Scenario,Source,Metric,Before,After,Delta,Percent,Highlighted",differences.Select(x=>$"{CsvQ(x.scenario)},{CsvQ(x.source)},{CsvQ(x.metric)},{x.before:R},{x.after:R},{x.delta:R},{x.percent:R},{x.highlighted}"));}
            if(widgetDifferences.Count>0){Heading("WIDGET REGRESSIONS");foreach(var w in widgetDifferences){using(new EditorGUILayout.HorizontalScope()){EditorGUILayout.LabelField(w.scenario+" / "+w.kind,$"{w.status} · max Δ {w.maximumAbsoluteDelta:0.####} · level {w.largestChangeLevel}");if(GUILayout.Button("OPEN SOURCE",GUILayout.Width(105)))OpenBalanceScenario(afterSnapshot?.suite?.scenarios.FirstOrDefault(s=>s.name==w.scenario));}if(w.kind==BalanceWidgetKind.Curve&&w.curve.Count>0)EditorGUILayout.LabelField("Curve",$"max {w.maximumAbsoluteDelta:0.####} · max % {w.maximumPercentDelta:P1} · mean {w.averageDelta:0.####} · area {w.areaDelta:0.####}");if(w.kind==BalanceWidgetKind.Matrix)foreach(var cell in w.matrix.Where(x=>Math.Abs(x.delta)>1e-9))EditorGUILayout.LabelField(cell.row+" × "+cell.column,$"{cell.before:P1} → {cell.after:P1} ({cell.delta:+0.##%;-0.##%;0%})");}if(GUILayout.Button("EXPORT WIDGET REGRESSION JSON"))status=WorkbenchExports.SaveJson("snapshot_widget_regression",new SnapshotWidgetComparisonExport{rows=widgetDifferences});}
        }
        void OpenBalanceScenario(BalanceScenario scenario)
        {
            if(scenario==null)return;switch(scenario.source){case "Combat":combatRequest=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(scenario.combat));playerBuild=combatRequest.player;tab=Tab.CombatLab;break;case "Drops":drop=JsonUtility.FromJson<DropLabRequest>(JsonUtility.ToJson(scenario.drop));tab=Tab.DropSimulator;break;case "Sensitivity":sensitivity=JsonUtility.FromJson<SensitivityRequest>(JsonUtility.ToJson(scenario.sensitivity));playerBuild=sensitivity.build;tab=Tab.Sensitivity;break;case "Affix":affixRequest=JsonUtility.FromJson<AffixAnalysisRequest>(JsonUtility.ToJson(scenario.affix));playerBuild=affixRequest.build;tab=Tab.AffixAnalyzer;break;case "Loot Progression":lootRequest=JsonUtility.FromJson<LootProgressionRequest>(JsonUtility.ToJson(scenario.loot));playerBuild=lootRequest.build;tab=Tab.LootProgression;break;case "Crafting":craftingRequest=JsonUtility.FromJson<CraftingSimulationRequest>(JsonUtility.ToJson(scenario.crafting));tab=Tab.CraftingSimulator;break;default:playerBuild=JsonUtility.FromJson<PlayerBuildSnapshot>(JsonUtility.ToJson(scenario.build));tab=Tab.PlayerBuildLab;break;}
        }

        void BreakpointTab()
        {
            Heading("SCAN THEN REFINE");breakSource=(BreakSource)EditorGUILayout.EnumPopup("Source",breakSource);breakStart=EditorGUILayout.IntField("Start level",breakStart);breakEnd=EditorGUILayout.IntField("End level",breakEnd);breakStep=EditorGUILayout.IntField("Coarse step",breakStep);breakMetric=EditorGUILayout.TextField("Metric ID",breakMetric);breakThreshold=EditorGUILayout.DoubleField("Threshold",breakThreshold);breakOperator=(BreakpointOperator)EditorGUILayout.EnumPopup("Rule",breakOperator);breakAll=EditorGUILayout.Toggle("All crossings",breakAll);
            EditorGUILayout.HelpBox("Metric IDs: Combat win_rate/p50_ttk/p90_ttk/mana_starvation; Enemy dps_p50/life_p50; Drops gear_per_kill/currency_per_kill; Loot upgrades_per_100; Player uses the Player Build metric catalog.",MessageType.None);
            if(GUILayout.Button("FIND BREAKPOINT",GUILayout.Height(30)))Run("Breakpoint scan",_=>{EnsureCombat();breakResults=BreakpointFinder.Find(level=>BreakMetricAt(level),Mathf.Max(1,breakStart),Mathf.Max(breakStart,breakEnd),Mathf.Max(1,breakStep),breakThreshold,breakOperator,breakAll);foreach(var r in breakResults){r.metric=breakMetric;r.seed=combatRequest.seed;r.samples=breakSource==BreakSource.Combat?combatRequest.fightCount:breakSource==BreakSource.Drops?drop.sampleCount:1;r.fingerprint=ProductionBalanceAdapters.DataFingerprint();if(breakSource==BreakSource.Combat&&breakMetric=="win_rate"){var interval=BlackCube.BalanceWorkbench.BreakpointFinder.WilsonInterval(r.at,r.samples);r.confidenceLow=interval.low;r.confidenceHigh=interval.high;}}});
            Heading("BATCH BREAKPOINTS");breakBatchClasses=EditorGUILayout.Toggle("Across classes",breakBatchClasses);breakBatchRarities=EditorGUILayout.Toggle("Across enemy rarities",breakBatchRarities);breakBudget.initial=EditorGUILayout.IntField("Initial fights / point",breakBudget.initial);breakBudget.refinement=EditorGUILayout.IntField("Refinement fights / point",breakBudget.refinement);breakBudget.maximum=EditorGUILayout.IntField("Maximum fights / point",breakBudget.maximum);if(GUILayout.Button("RUN BATCH BREAKPOINTS"))Run("Batch breakpoints",_=>{EnsureCombat();var classes=breakBatchClasses?PlayerClassCatalog.All.Select(x=>x.Id).ToArray():new[]{playerBuild.classId};var rarities=breakBatchRarities?Enum.GetValues(typeof(EnemyAI.EnemyRarity)).Cast<EnemyAI.EnemyRarity>().ToArray():new[]{combatRequest.rarity};var cases=(from cls in classes from rarity in rarities select new BreakpointBatchCase{name=cls+" × "+rarity,classId=cls,rarity=rarity}).ToList();breakBatchResults=BreakpointFinder.FindBatch(cases,(c,l)=>BreakMetricAtCase(c,l,breakBudget.initial),breakStart,breakEnd,breakStep,breakThreshold,breakOperator,breakSource==BreakSource.Combat&&breakMetric=="win_rate"?breakBudget:null,breakSource==BreakSource.Combat&&breakMetric=="win_rate"?(c,l,n)=>BreakMetricAtCase(c,l,n):null,Progress("Batch cases"),()=>cancelled);});
            if(breakBatchResults.Count>0){Heading("BATCH TABLE — EARLIEST CROSSING FIRST");foreach(var row in breakBatchResults)EditorGUILayout.LabelField(row.scenario,$"{(row.crossingFound?"L"+row.firstCrossing:"NONE")} · {row.allCrossings} crossings · {row.before:0.###} → {row.at:0.###} vs {row.threshold:0.###} · n={row.samples} · {row.confidence}");if(breakBatchClasses&&breakBatchRarities){Heading("CLASS × RARITY HEATMAP");foreach(var cls in PlayerClassCatalog.All)EditorGUILayout.LabelField(cls.DisplayName,string.Join(" | ",Enum.GetValues(typeof(EnemyAI.EnemyRarity)).Cast<EnemyAI.EnemyRarity>().Select(r=>r+":"+(breakBatchResults.FirstOrDefault(x=>x.scenario==cls.Id+" × "+r)?.firstCrossing is int level&&level>0?level.ToString():"NONE"))));}if(GUILayout.Button("EXPORT BATCH CSV"))status=SaveAdvancedCsv("batch_breakpoints","Scenario,CrossingFound,FirstCrossing,AllCrossings,Before,At,Threshold,Samples,CILow,CIHigh,Confidence",breakBatchResults.Select(x=>$"{CsvQ(x.scenario)},{x.crossingFound},{x.firstCrossing},{x.allCrossings},{x.before:R},{x.at:R},{x.threshold:R},{x.samples},{x.confidenceLow:R},{x.confidenceHigh:R},{CsvQ(x.confidence)}"));}
            if(breakResults.Count>0){Heading("CROSSINGS");foreach(var r in breakResults)EditorGUILayout.LabelField("Level "+r.level,$"{r.before:0.####} → {r.at:0.####}; threshold {r.threshold:0.####}"+(r.samples>1&&r.metric=="win_rate"?$" · 95% CI {r.confidenceLow:P1}–{r.confidenceHigh:P1}":""));var first=breakResults[0];var metricSeries=new CurveSeries{name=breakMetric,color=Color.cyan,points=first.curve.Select(x=>new CurvePoint{x=x.level,mean=x.value}).ToList()};var thresholdSeries=new CurveSeries{name="Threshold",color=Color.yellow,points=new(){new CurvePoint{x=breakStart,mean=breakThreshold},new CurvePoint{x=breakEnd,mean=breakThreshold}}};var plot=new List<CurveSeries>{metricSeries,thresholdSeries};chart.Draw(GUILayoutUtility.GetRect(200,280,GUILayout.ExpandWidth(true)),plot,"Level",breakMetric);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("EXPORT CSV"))status=SaveAdvancedCsv("breakpoints","Level,Metric,Before,At,After,Threshold,Samples,Seed,CI_Low,CI_High,Fingerprint",breakResults.Select(x=>$"{x.level},{x.metric},{x.before:R},{x.at:R},{x.after:R},{x.threshold:R},{x.samples},{x.seed},{x.confidenceLow:R},{x.confidenceHigh:R},{x.fingerprint}"));if(GUILayout.Button("EXPORT PNG"))status=chart.ExportPng(plot,"breakpoints");}}
        }

        double BreakMetricAt(int level)
        {
            switch(breakSource)
            {
                case BreakSource.Combat:{var request=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));request.enemyLevel=level;var r=CombatLabAdapters.Batch(request);return breakMetric switch{"p50_ttk"=>r.duration.p50,"p90_ttk"=>r.duration.p90,"mana_starvation"=>r.manaStarvation.mean,_=>r.winRate};}
                case BreakSource.EnemyGear:{var r=ProductionBalanceAdapters.RunEnemies(new EnemyLabRequest{level=level,sampleCount=64,seed=combatRequest.seed,archetypeId=combatRequest.enemyArchetypeId,rarity=combatRequest.rarity});return breakMetric=="life_p50"?r.life.p50:r.dps.p50;}
                case BreakSource.Drops:{var request=JsonUtility.FromJson<DropLabRequest>(JsonUtility.ToJson(drop));request.level=level;var r=ProductionBalanceAdapters.RunDrops(request);return breakMetric=="gear_per_kill"?r.averageGearItems:r.averageCurrencyRolls;}
                case BreakSource.LootProgression:{var request=JsonUtility.FromJson<LootProgressionRequest>(JsonUtility.ToJson(lootRequest));request.combatLevel=level;request.kills=Mathf.Min(1000,request.kills);var r=LootProgressionAnalyzer.Run(request);return r.upgrades.Count*100.0/Math.Max(1,r.kills);}
                default:{var b=playerBuild.Clone();b.playerLevel=level;return OptimizationMetricCatalog.Get(breakMetric).Value(PlayerBuildEvaluator.Evaluate(b));}
            }
        }
        double BreakMetricAtCase(BreakpointBatchCase scenario,int level,int fights)
        {
            var oldBuild=playerBuild;var oldCombat=combatRequest;
            try
            {
                playerBuild=oldBuild.Clone();playerBuild.classId=scenario.classId;
                combatRequest=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(oldCombat));combatRequest.player=playerBuild;combatRequest.rarity=scenario.rarity;combatRequest.fightCount=Math.Max(1,fights);
                return BreakMetricAt(level);
            }
            finally{playerBuild=oldBuild;combatRequest=oldCombat;}
        }

        void ReportTab()
        {
            Heading("DESIGNER BALANCE REPORT");reportTitle=EditorGUILayout.TextField("Title",reportTitle);reportPreset.title=reportTitle;reportPreset.designerNotes=EditorGUILayout.TextArea(reportPreset.designerNotes??"",GUILayout.MinHeight(45));EditorGUILayout.HelpBox("Widgets reference scenarios in the Balance Snapshot suite. Choose live current results or a saved snapshot per widget; no production balance data is edited.",MessageType.Info);if(GUILayout.Button("OPEN SNAPSHOT SUITE"))tab=Tab.BalanceSnapshots;
            for(int s=0;s<reportPreset.sections.Count;s++)
            {
                var section=reportPreset.sections[s];using(new EditorGUILayout.HorizontalScope()){section.title=EditorGUILayout.TextField("Section",section.title);if(GUILayout.Button("Remove section",GUILayout.Width(110))){reportPreset.sections.RemoveAt(s--);continue;}}section.notes=EditorGUILayout.TextField("Section notes",section.notes??"");
                for(int w=0;w<section.widgets.Count;w++){var widget=section.widgets[w];using(new EditorGUILayout.HorizontalScope()){widget.title=EditorGUILayout.TextField(widget.title);widget.type=(ReportWidgetType)EditorGUILayout.EnumPopup(widget.type,GUILayout.Width(145));if(GUILayout.Button("Remove",GUILayout.Width(65))){section.widgets.RemoveAt(w--);continue;}}widget.scenarioName=PopupValue("Saved scenario",widget.scenarioName,balanceSuite.scenarios.Select(x=>x.name).ToArray());widget.dataSource=(ReportDataSource)EditorGUILayout.EnumPopup("Source",widget.dataSource);widget.notes=EditorGUILayout.TextField("Notes",widget.notes??"");}if(GUILayout.Button("ADD WIDGET TO "+section.title))section.widgets.Add(new ReportWidgetPreset{scenarioName=balanceSuite.scenarios.FirstOrDefault()?.name});
            }
            if(GUILayout.Button("ADD REPORT SECTION"))reportPreset.sections.Add(new ReportSectionPreset());useAfterSnapshot=EditorGUILayout.Toggle("Use after snapshot",useAfterSnapshot);
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SAVE REPORT PRESET"))status=WorkbenchExports.SaveJson("report_preset",reportPreset);if(GUILayout.Button("LOAD REPORT PRESET")){string path=EditorUtility.OpenFilePanel("Load report preset",WorkbenchExports.Root,"json");if(!string.IsNullOrEmpty(path))reportPreset=JsonUtility.FromJson<BalanceReportPreset>(File.ReadAllText(path));}}
            if(GUILayout.Button("RUN REPORT",GUILayout.Height(32)))Run("Balance report",_=>{reportRun=BalanceReportService.Run(reportPreset,balanceSuite,useAfterSnapshot?afterSnapshot:beforeSnapshot,Progress("Report widgets"),()=>cancelled);reportPath=BalanceReportService.ExportBundle(reportRun);status=reportPath;});if(reportRun!=null)EditorGUILayout.LabelField("Widget results",$"{reportRun.widgets.Count} · {(reportRun.cancelled?"CANCELLED / PARTIAL":"Complete")}");if(!string.IsNullOrEmpty(reportPath))EditorGUILayout.SelectableLabel(reportPath,EditorStyles.textField,GUILayout.Height(20));
        }

        void AffixTab()
        {
            Heading("PRODUCTION MOD DATABASE");affixRequest.slot=(LootManager.GearType)EditorGUILayout.EnumPopup("Slot",affixRequest.slot);affixRequest.itemLevel=EditorGUILayout.IntSlider("Item level",affixRequest.itemLevel,1,100);affixRequest.rarity=(LootManager.GearRarity)EditorGUILayout.EnumPopup("Rarity",affixRequest.rarity);if(affixRequest.slot==LootManager.GearType.Weapons){affixRequest.weaponTypeId=PopupValue("Weapon",affixRequest.weaponTypeId,WeaponTypeCatalog.All.Select(x=>x.Id).ToArray());affixRequest.element=(Element)EditorGUILayout.EnumPopup("Element",affixRequest.element);}affixRequest.rollPercent=EditorGUILayout.Slider("Roll position",affixRequest.rollPercent,0,1);affixRequest.allTiers=EditorGUILayout.Toggle("Analyze all legal tiers",affixRequest.allTiers);affixRequest.pairTop=EditorGUILayout.IntSlider("Pair top N",affixRequest.pairTop,2,12);affixRequest.replaceCurrentMod=EditorGUILayout.Toggle("Replace current mod",affixRequest.replaceCurrentMod);if(affixRequest.replaceCurrentMod)affixRequest.replacedStat=(StatTypes)EditorGUILayout.EnumPopup("Mod to replace",affixRequest.replacedStat);
            EditorGUILayout.HelpBox("Scores legal additions from the production ModDatabase and build evaluator. A full item needs Replace Current Mod enabled. Combat shortlist validation is not yet available.",MessageType.Info);
            if(GUILayout.Button("ANALYZE LEGAL AFFIXES",GUILayout.Height(30)))Run("Affix analysis",_=>{affixRequest.build=playerBuild.Clone();affixRequest.objective=JsonUtility.FromJson<OptimizationObjective>(JsonUtility.ToJson(objective));affixResult=AffixAnalyzer.Run(affixRequest,()=>cancelled);});
            if(affixResult==null)return;if(affixResult.Stale)EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);Heading("RANKED AFFIXES");foreach(var row in affixResult.rows.Take(80))EditorGUILayout.LabelField($"{row.name} T{row.tier} ({row.side})",$"Roll {row.roll:0.###} · Primary {row.primaryDelta:+0.###;-0.###;0} · Objective {row.objectiveDelta:+0.####;-0.####;0}");
            if(GUILayout.Button("EXPORT AFFIX CSV"))status=SaveAdvancedCsv("affix_ranking","Stat,Name,Side,Tier,MinLevel,Roll,PrimaryDelta,SecondaryDelta,ObjectiveDelta",affixResult.rows.Select(x=>$"{x.stat},{CsvQ(x.name)},{x.side},{x.tier},{x.itemLevel},{x.roll:R},{x.primaryDelta:R},{x.secondaryDelta:R},{x.objectiveDelta:R}"));
            affixCombatCount=EditorGUILayout.IntSlider("Combat shortlist",affixCombatCount,1,10);if(GUILayout.Button("COMBAT TEST TOP N"))Run("Affix combat shortlist",_=>{EnsureCombat();affixCombat=AffixAnalyzer.CombatValidateTop(affixRequest,affixResult,combatRequest,affixCombatCount,Progress("Affixes"),()=>cancelled);});if(affixCombat.Count>0){Heading("COMBAT DELTAS VS CURRENT BUILD");foreach(var row in affixCombat)EditorGUILayout.LabelField(row.affix,$"Win {row.winRateDelta:+0.##%;-0.##%;0%} · P50 {row.p50DurationDelta:+0.##;-0.##;0}s · DPS {row.dpsDelta:+0.##;-0.##;0}");}
            Heading("TOP-PAIR INTERACTIONS");foreach(var pair in affixResult.pairs)EditorGUILayout.LabelField(pair.a+" × "+pair.b,pair.interaction.ToString("+0.####;-0.####;0"));if(affixResult.pairs.Count>0&&GUILayout.Button("EXPORT PAIR CSV"))status=SaveAdvancedCsv("affix_pairs","AffixA,AffixB,GainA,GainB,Combined,Interaction",affixResult.pairs.Select(x=>$"{x.a},{x.b},{x.gainA:R},{x.gainB:R},{x.combined:R},{x.interaction:R}"));
            if(GUILayout.Button("SELECT MOD DATABASE")){var db=AssetDatabase.LoadAssetAtPath<ModDatabase>("Assets/Prefabs/Scriptable Objects/ModDatabase.asset");Selection.activeObject=db;EditorGUIUtility.PingObject(db);}
        }

        void LootTab()
        {
            Heading("PER-KILL PRODUCTION LOOT / BUILD UPGRADES");lootRequest.combatLevel=EditorGUILayout.IntSlider("Combat level",lootRequest.combatLevel,1,360);lootRequest.sourceMode=(LootSourceMode)EditorGUILayout.EnumPopup("Encounter source",lootRequest.sourceMode);if(lootRequest.sourceMode is LootSourceMode.FixedRarity or LootSourceMode.SpecificEnemy){lootRequest.rarity=(EnemyAI.EnemyRarity)EditorGUILayout.EnumPopup("Enemy rarity",lootRequest.rarity);lootRequest.boss=EditorGUILayout.Toggle("Boss source",lootRequest.boss);}if(lootRequest.sourceMode is LootSourceMode.BiomePopulation or LootSourceMode.SpecificLocation){var world=WorldContentCatalog.Reference;lootRequest.biomeId=PopupValue("Biome",lootRequest.biomeId,world.biomes.Select(x=>x.stableId).ToArray());if(lootRequest.sourceMode==LootSourceMode.SpecificLocation){var biome=world.Biome(lootRequest.biomeId);if(biome!=null)lootRequest.locationId=PopupValue("Location",lootRequest.locationId,biome.locations.Select(x=>x.stableId).ToArray());}}if(lootRequest.sourceMode is LootSourceMode.StageRange or LootSourceMode.BiomePopulation or LootSourceMode.SpecificLocation or LootSourceMode.CustomWorldRange){lootRequest.firstStage=EditorGUILayout.IntSlider("First stage",lootRequest.firstStage,1,10);lootRequest.lastStage=EditorGUILayout.IntSlider("Last stage",lootRequest.lastStage,lootRequest.firstStage,10);}if(lootRequest.sourceMode==LootSourceMode.CustomWorldRange){lootRequest.firstCombatLevel=EditorGUILayout.IntSlider("First combat level",lootRequest.firstCombatLevel,1,360);lootRequest.lastCombatLevel=EditorGUILayout.IntSlider("Last combat level",lootRequest.lastCombatLevel,lootRequest.firstCombatLevel,360);}lootRequest.generateActualEnemyGear=EditorGUILayout.Toggle("Sample actual enemy gear",lootRequest.generateActualEnemyGear);if(lootRequest.sourceMode==LootSourceMode.SpecificEnemy){EnsureEnemySelection();lootRequest.archetypeId=PopupValue("Archetype",lootRequest.archetypeId,new[]{"Any"}.Concat(EnemyDb.enemyArchetypes.Select(x=>x.stableId)).ToArray());}lootRequest.progressive=EditorGUILayout.Toggle("Progressive auto-equip",lootRequest.progressive);lootRequest.minimumImprovement=EditorGUILayout.DoubleField("Minimum objective gain",lootRequest.minimumImprovement);lootRequest.kills=SampleCount(lootRequest.kills,100000);lootRequest.seed=EditorGUILayout.LongField("Seed",lootRequest.seed);EditorGUILayout.HelpBox("World modes resolve authored encounters via WorldProgression, then use production loot/item rolls. First-upgrade trials reset to the same starting build each time.",MessageType.Info);
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SIMULATE UPGRADES",GUILayout.Height(30)))Run("Loot progression",_=>{lootRequest.build=playerBuild.Clone();lootRequest.objective=JsonUtility.FromJson<OptimizationObjective>(JsonUtility.ToJson(objective));lootResult=LootProgressionAnalyzer.Run(lootRequest,Progress("Kills"),()=>cancelled);});if(GUILayout.Button("COMPARE RARITIES"))Run("Loot source comparison",_=>{lootComparison.Clear();foreach(EnemyAI.EnemyRarity rarity in Enum.GetValues(typeof(EnemyAI.EnemyRarity))){if(cancelled)break;var request=JsonUtility.FromJson<LootProgressionRequest>(JsonUtility.ToJson(lootRequest));request.build=playerBuild.Clone();request.objective=objective;request.rarity=rarity;request.kills=lootComparisonKills;var compared=LootProgressionAnalyzer.Run(request,Progress(rarity.ToString()),()=>cancelled);compared.metadata.scenario=rarity.ToString();lootComparison.Add(compared);}});}
            lootComparisonKills=EditorGUILayout.IntSlider("Comparison kills / source",lootComparisonKills,100,10000);
            Heading("INDEPENDENT FIRST-UPGRADE DISTRIBUTION");using(new EditorGUILayout.HorizontalScope()){foreach(int preset in new[]{100,1000,10000})if(GUILayout.Button(preset.ToString("N0")))firstUpgradeTrials=preset;}firstUpgradeTrials=EditorGUILayout.IntField("Trials (custom)",firstUpgradeTrials);firstUpgradeMaxKills=EditorGUILayout.IntField("Maximum kills / trial",firstUpgradeMaxKills);firstUpgradeCustomThreshold=EditorGUILayout.IntField("Custom probability threshold",firstUpgradeCustomThreshold);if(GUILayout.Button("RUN FIRST-UPGRADE TRIALS"))Run("First-upgrade trials",_=>{lootRequest.build=playerBuild.Clone();lootRequest.objective=JsonUtility.FromJson<OptimizationObjective>(JsonUtility.ToJson(objective));firstUpgradeResult=LootProgressionAnalyzer.RunFirstUpgradeTrials(lootRequest,firstUpgradeTrials,firstUpgradeMaxKills,new[]{firstUpgradeCustomThreshold},Progress("Independent trials"),()=>cancelled);});
            if(firstUpgradeResult!=null){EditorGUILayout.LabelField("Successes / censored",$"{firstUpgradeResult.successes} / {firstUpgradeResult.censored} ({firstUpgradeResult.trials} trials)");Summary("Kills to first upgrade (successes)",firstUpgradeResult.successfulKills);foreach(var p in firstUpgradeResult.curve)EditorGUILayout.LabelField($"By {p.kills} kills",$"{p.probabilityFound:P1} found · {p.censored} censored by limit");var survival=new CurveSeries{name="Still waiting",color=Color.yellow,points=firstUpgradeResult.curve.Select(x=>new CurvePoint{x=x.kills,mean=x.probabilityNotFound}).ToList()};chart.Draw(GUILayoutUtility.GetRect(200,240,GUILayout.ExpandWidth(true)),new[]{survival},"Kills","Probability still waiting");if(GUILayout.Button("EXPORT TRIAL CSV"))status=SaveAdvancedCsv("first_upgrade_trials","Trial,Kills,Censored,Magnitude",firstUpgradeResult.observations.Select(x=>$"{x.trial},{x.kills},{x.censored},{x.magnitude:R}"));}
            Heading("PROGRESSIVE UPGRADE INTERVALS");intervalTrials=EditorGUILayout.IntField("Independent trials",intervalTrials);intervalKills=EditorGUILayout.IntField("Kills per trial",intervalKills);if(GUILayout.Button("RUN INTERVAL TRIALS"))Run("Progressive interval trials",_=>{lootRequest.build=playerBuild.Clone();lootRequest.objective=JsonUtility.FromJson<OptimizationObjective>(JsonUtility.ToJson(objective));intervalResult=LootProgressionAnalyzer.RunProgressiveIntervalTrials(lootRequest,intervalTrials,intervalKills,Progress("Interval trials"),()=>cancelled);});
            if(intervalResult!=null){EditorGUILayout.LabelField("Completed trials",intervalResult.trials.ToString());EditorGUILayout.LabelField("Reached upgrade #1 / #2 / #3",$"{intervalResult.firstReached} / {intervalResult.secondReached} / {intervalResult.thirdReached}");Summary("First interval",intervalResult.first);Summary("Second interval",intervalResult.second);Summary("Third interval",intervalResult.third);Summary("Later intervals",intervalResult.later);if(GUILayout.Button("EXPORT INTERVAL JSON"))status=WorkbenchExports.SaveJson("progressive_upgrade_intervals",intervalResult);}
            Heading("WORLD PROGRESSION SWEEP");lootSweepStart=EditorGUILayout.IntSlider("Start combat level",lootSweepStart,1,360);lootSweepEnd=EditorGUILayout.IntSlider("End combat level",lootSweepEnd,lootSweepStart,360);sweepStep=EditorGUILayout.IntSlider("Level step",sweepStep,1,60);sweepLoops=EditorGUILayout.IntSlider("Encounter loops / level",sweepLoops,1,100);sweepFirstTrials=EditorGUILayout.IntSlider("First-upgrade trials / level",sweepFirstTrials,0,100);sweepBuildSource=(LootSweepBuildSource)EditorGUILayout.EnumPopup("Build source",sweepBuildSource);if(GUILayout.Button("RUN WORLD LOOT SWEEP"))Run("World loot sweep",_=>{var request=JsonUtility.FromJson<LootProgressionRequest>(JsonUtility.ToJson(lootRequest));request.build=playerBuild.Clone();request.objective=objective;lootWorldSweep=LootProgressionAnalyzer.RunWorldSweep(request,lootSweepStart,lootSweepEnd,sweepStep,sweepLoops,sweepFirstTrials,sweepBuildSource,gearProfile,Progress("World levels"),()=>cancelled);});
            if(lootComparison.Count>0){Heading("SOURCE COMPARISON");foreach(var r in lootComparison)EditorGUILayout.LabelField(r.metadata.scenario,$"{r.upgrades.Count} upgrades / {r.kills} kills");}
            if(lootWorldSweep.Count>0){Heading("WORLD SWEEP RESULTS");foreach(var row in lootWorldSweep)EditorGUILayout.LabelField("Level "+row.level,$"Gear {row.gearPerKill:0.##}/kill · Currency {row.currencyPerKill:0.##}/kill · Upgrade {row.upgradeChancePerKill:P1}/kill · Kills/upgrade {row.expectedKillsPerUpgrade:0.#} · First median {row.firstUpgradeMedian:0.#} · Boss {row.bossUpgradeContribution:P0}");if(GUILayout.Button("EXPORT WORLD SWEEP CSV"))status=SaveAdvancedCsv("world_loot_sweep","Level,Kills,GearPerKill,CurrencyPerKill,UpgradeChance,ExpectedKillsPerUpgrade,FirstUpgradeMedian,AverageUpgradeMagnitude,BossContribution,RareLegendaryContribution",lootWorldSweep.Select(x=>$"{x.level},{x.kills},{x.gearPerKill:R},{x.currencyPerKill:R},{x.upgradeChancePerKill:R},{x.expectedKillsPerUpgrade:R},{x.firstUpgradeMedian:R},{x.averageUpgradeMagnitude:R},{x.bossUpgradeContribution:R},{x.rareLegendaryContribution:R}"));}
            if(lootResult==null)return;if(lootResult.Stale)EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);
            EditorGUILayout.LabelField("Kills / drops / upgrades",$"{lootResult.kills} / {lootResult.drops} / {lootResult.upgrades.Count}");EditorGUILayout.LabelField("First upgrade kill",lootResult.firstUpgradeKill==0?"Not found":lootResult.firstUpgradeKill.ToString());EditorGUILayout.LabelField("Kills with ≥1 upgrade",$"{lootResult.killsWithUpgrade} ({lootResult.killsWithUpgrade/(double)Math.Max(1,lootResult.kills):P2})");EditorGUILayout.LabelField("Upgrades / 100 / 1,000 kills",$"{lootResult.upgrades.Count*100.0/Math.Max(1,lootResult.kills):0.##} / {lootResult.upgrades.Count*1000.0/Math.Max(1,lootResult.kills):0.##}");Summary("Kills between upgrades",lootResult.upgradeIntervals);if(lootRequest.progressive){Summary("First interval",lootResult.firstInterval);Summary("Second interval",lootResult.secondInterval);Summary("Third interval",lootResult.thirdInterval);Summary("Later intervals",lootResult.laterIntervals);}Summary("Upgrade magnitude",lootResult.upgradeMagnitudes);Heading("PER SLOT");foreach(var g in lootResult.upgrades.GroupBy(x=>x.slot))EditorGUILayout.LabelField(g.Key,$"{g.Count()} upgrades · {lootResult.kills/(double)g.Count():0.##} kills / upgrade");Heading("PER ITEM RARITY");foreach(var g in lootResult.upgrades.GroupBy(x=>x.rarity))EditorGUILayout.LabelField(g.Key,g.Count().ToString());Heading("SOURCE BREAKDOWN");foreach(var s in lootResult.sources.Where(x=>x.upgrades>0).OrderByDescending(x=>x.upgrades).Take(40))EditorGUILayout.LabelField($"{s.biome} / {s.location} / S{s.stage} / {s.archetype} / {s.rarity}",$"{s.upgrades} upgrades · {s.drops} drops · {s.kills} kills");Heading("CURRENCY ACCUMULATION");foreach(var c in lootResult.currency)EditorGUILayout.LabelField(c.type.ToString(),$"{c.amount} total · {c.amount*100.0/Math.Max(1,lootResult.kills):0.##} / 100 kills · {c.amount/(double)Math.Max(1,lootResult.upgrades.Count):0.##} / upgrade");
            if(GUILayout.Button("EXPORT SOURCE BREAKDOWN CSV"))status=SaveAdvancedCsv("loot_source_breakdown","Biome,Location,Stage,Archetype,EnemyRarity,Boss,Kills,Drops,Upgrades,Currency,Slots,ItemRarities",lootResult.sources.Select(x=>$"{CsvQ(x.biome)},{CsvQ(x.location)},{x.stage},{CsvQ(x.archetype)},{CsvQ(x.rarity)},{x.boss},{x.kills},{x.drops},{x.upgrades},{CsvQ(string.Join(";",x.currency.Select(c=>c.type+":"+c.amount)))},{CsvQ(string.Join(";",x.slots.Select(c=>c.name+":"+c.count)))},{CsvQ(string.Join(";",x.itemRarities.Select(c=>c.name+":"+c.count)))}"));
            if(lootResult.upgrades.Count>0){var best=lootResult.upgrades.OrderByDescending(x=>x.magnitude).First();if(GUILayout.Button("INSPECT BEST DROPPED ITEM"))EditorUtility.DisplayDialog($"Upgrade at kill {best.kill}",best.item.Description+"\nObjective gain "+best.magnitude.ToString("0.####"),"Close");}
            if(GUILayout.Button("EXPORT PROGRESSION CSV"))status=SaveAdvancedCsv("loot_progression","Kill,Slot,Rarity,ObjectiveGain,Item",lootResult.upgrades.Select(x=>$"{x.kill},{x.slot},{x.rarity},{x.magnitude:R},{CsvQ(x.item.Description)}"));
        }

        void CraftingTab()
        {
            Heading("PRODUCTION CRAFTING TRIALS");if(GUILayout.Button("USE CURRENT BUILD WEAPON")){craftingRequest.item=playerBuild.equipment.FirstOrDefault(x=>x.slot==LootManager.GearType.Weapons);if(craftingRequest.item==null)status="No equipped weapon in current build.";}if(craftingRequest.item!=null)EditorGUILayout.HelpBox(craftingRequest.item.Description,MessageType.None);
            craftingRequest.trials=SampleCount(craftingRequest.trials,100000);craftingRequest.maxActions=EditorGUILayout.IntSlider("Max actions / attempt",craftingRequest.maxActions,1,1000);craftingRequest.seed=EditorGUILayout.LongField("Seed",craftingRequest.seed);craftingRequest.combatLevel=EditorGUILayout.IntSlider("Combat progression level",craftingRequest.combatLevel,1,360);craftingRequest.targetGroupMode=(CraftTargetGroupMode)EditorGUILayout.EnumPopup("Target group",craftingRequest.targetGroupMode);if(craftingRequest.targetGroupMode==CraftTargetGroupMode.AtLeastN)craftingRequest.requiredMatches=EditorGUILayout.IntSlider("Required matching affixes",craftingRequest.requiredMatches,1,6);
            Heading("TARGET CONDITIONS");foreach(var t in craftingRequest.targets){using(new EditorGUILayout.HorizontalScope()){t.stat=(StatTypes)EditorGUILayout.EnumPopup(t.stat);t.maximumTier=EditorGUILayout.IntField("Tier ≤",t.maximumTier);t.minimumRoll=EditorGUILayout.FloatField("Roll ≥",t.minimumRoll);}}if(GUILayout.Button("ADD TARGET"))craftingRequest.targets.Add(new CraftTarget{stat=StatTypes.PhysDmg});craftingRequest.minimumEmpowered=EditorGUILayout.IntSlider("Minimum Empowered",craftingRequest.minimumEmpowered,0,6);craftingRequest.requireSpecificEmpowered=EditorGUILayout.Toggle("Specific Empowered stat",craftingRequest.requireSpecificEmpowered);if(craftingRequest.requireSpecificEmpowered)craftingRequest.targetEmpoweredStat=(StatTypes)EditorGUILayout.EnumPopup("Empowered stat",craftingRequest.targetEmpoweredStat);craftingRequest.targetBossSpecialId=EditorGUILayout.TextField("Boss-special ID",craftingRequest.targetBossSpecialId??"");craftingRequest.targetBossPoolId=EditorGUILayout.TextField("Boss-special pool/family ID",craftingRequest.targetBossPoolId??"");craftingRequest.targetImplicitStat=EditorGUILayout.TextField("Implicit stat name",craftingRequest.targetImplicitStat??"");int implicitLimit=EditorGUILayout.IntField("Implicit tier ≤ (0=any)",craftingRequest.maximumImplicitTier==int.MaxValue?0:craftingRequest.maximumImplicitTier);craftingRequest.maximumImplicitTier=implicitLimit<=0?int.MaxValue:implicitLimit;craftingRequest.minimumImplicitRoll=EditorGUILayout.FloatField("Implicit roll ≥",craftingRequest.minimumImplicitRoll);craftingRequest.maximumUndesirable=EditorGUILayout.IntField("Maximum undesirable",craftingRequest.maximumUndesirable==int.MaxValue?99:craftingRequest.maximumUndesirable);craftingRequest.minimumObjectiveImprovement=EditorGUILayout.DoubleField("Minimum build-objective gain",craftingRequest.minimumObjectiveImprovement);if(craftingRequest.minimumObjectiveImprovement>0&&GUILayout.Button("USE CURRENT BUILD AS OBJECTIVE BASELINE")){craftingRequest.objectiveBuild=playerBuild.Clone();craftingRequest.objective=JsonUtility.FromJson<OptimizationObjective>(JsonUtility.ToJson(objective));}
            Heading("ORDERED ACTION POLICY");foreach(var step in craftingRequest.policy){step.operation=(CraftOperation)EditorGUILayout.EnumPopup("Operation",step.operation);using(new EditorGUILayout.HorizontalScope()){if(step.operation==CraftOperation.Ordinary){var actions=BlackCube.BalanceWorkbench.CraftingSimulator.OrdinaryActions;int index=Mathf.Max(0,Array.IndexOf(actions,step.action));step.action=actions[EditorGUILayout.Popup("Action",index,actions.Select(x=>x.ToString()).ToArray())];}else if(step.operation is CraftOperation.Empowerment or CraftOperation.BossInfusion)step.targetStat=(StatTypes)EditorGUILayout.EnumPopup("Target mod",step.targetStat);step.repeats=EditorGUILayout.IntField("Repeats",step.repeats);}if(step.operation==CraftOperation.BossInfusion){var challenges=WorldContentCatalog.Reference.challengeEncounters.Select(x=>x.stableContentId).ToArray();step.challengeId=PopupValue("Challenge",step.challengeId,challenges);}}if(GUILayout.Button("ADD ACTION"))craftingRequest.policy.Add(new CraftPolicyStep{action=CraftingCurrencyType.RerollRareModifier});EditorGUILayout.HelpBox("Ordinary, Empowerment, boss-infusion, and implicit-reforge actions invoke production crafting mutations. Simulated resources are unlimited only when explicitly toggled; legacy ordinary budgets of zero remain unlimited.",MessageType.Info);
            Heading("CURRENCY BUDGETS (0 = unlimited)");for(int i=0;i<craftingRequest.budgets.Count;i++){var budget=craftingRequest.budgets[i];using(new EditorGUILayout.HorizontalScope()){budget.type=(CraftingCurrencyType)EditorGUILayout.EnumPopup(budget.type);budget.amount=EditorGUILayout.IntField(budget.amount);}craftingRequest.budgets[i]=budget;}if(GUILayout.Button("ADD BUDGET"))craftingRequest.budgets.Add(new CurrencyStackData(CraftingCurrencyType.RerollRareModifier,10));
            Heading("RESOURCE INVENTORY");foreach(var resource in craftingRequest.resources){using(new EditorGUILayout.HorizontalScope()){resource.id=EditorGUILayout.TextField("Resource ID",resource.id);resource.startingQuantity=EditorGUILayout.IntField("Start",resource.startingQuantity);resource.unlimited=EditorGUILayout.Toggle("Unlimited",resource.unlimited);}}if(GUILayout.Button("ADD RESOURCE"))craftingRequest.resources.Add(new SimulatedResourceQuantity{id=EndgameResourceIds.ImplicitReforger,startingQuantity=1});
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SAVE POLICY"))status=WorkbenchExports.SaveJson("craft_policy",craftingRequest);if(GUILayout.Button("LOAD POLICY")){string path=EditorUtility.OpenFilePanel("Load crafting policy",WorkbenchExports.Root,"json");if(!string.IsNullOrEmpty(path))craftingRequest=JsonUtility.FromJson<CraftingSimulationRequest>(File.ReadAllText(path));}if(GUILayout.Button("ADD POLICY TO COMPARISON"))craftPolicies.Add(JsonUtility.FromJson<CraftingSimulationRequest>(JsonUtility.ToJson(craftingRequest)));}
            if(craftPolicies.Count>=2&&GUILayout.Button("COMPARE SAVED POLICIES"))Run("Craft policy comparison",_=>{craftComparisons.Clear();foreach(var policy in craftPolicies.Take(5)){if(cancelled)break;craftComparisons.Add(CraftingSimulator.Run(policy,Progress("Policies"),()=>cancelled));}});
            if(craftComparisons.Count>0){Heading("POLICY COMPARISON");for(int i=0;i<craftComparisons.Count;i++){var r=craftComparisons[i];EditorGUILayout.LabelField("Policy "+(i+1),$"Success {(r.trials==0?0:r.successes/(double)r.trials):P1} · P50 actions {r.actions.p50:0.#} · P90 {r.actions.p90:0.#} · Potential failures {r.potentialFailures}");}}
            Heading("BOUNDED POLICY SEARCH");craftSearch.beamWidth=EditorGUILayout.IntSlider("Beam width",craftSearch.beamWidth,1,30);craftSearch.maxCraftActions=EditorGUILayout.IntSlider("Search depth",craftSearch.maxCraftActions,1,20);craftSearch.candidateOutcomesPerAction=EditorGUILayout.IntSlider("Random outcomes / candidate",craftSearch.candidateOutcomesPerAction,1,100);craftSearch.maximumStates=EditorGUILayout.IntSlider("Maximum states",craftSearch.maximumStates,1,500);craftSearch.seed=EditorGUILayout.LongField("Search seed",craftSearch.seed);if(GUILayout.Button("SEARCH BEST DISCOVERED POLICY"))Run("Craft policy search",_=>{craftSearch.simulation=JsonUtility.FromJson<CraftingSimulationRequest>(JsonUtility.ToJson(craftingRequest));craftSearch.allowedActions=craftingRequest.policy.Select(x=>JsonUtility.FromJson<CraftPolicyStep>(JsonUtility.ToJson(x))).ToList();craftSearchResult=CraftingPolicySearcher.Search(craftSearch,Progress("Search states"),()=>cancelled);});
            if(craftSearchResult!=null){EditorGUILayout.HelpBox(craftSearchResult.label+$" · {craftSearchResult.evaluatedStates}/{craftSearchResult.stateCap} states",MessageType.Info);foreach(var discovered in craftSearchResult.topPolicies.Take(10)){using(new EditorGUILayout.HorizontalScope()){EditorGUILayout.LabelField(string.Join(" → ",discovered.steps.Select(x=>x.operation==CraftOperation.Ordinary?x.action.ToString():x.operation.ToString())),$"Estimated {discovered.estimatedSuccessRate:P1} · P50 cost {discovered.medianCost:0.#} · P90 {discovered.p90Cost:0.#}");if(GUILayout.Button("VALIDATE POLICY",GUILayout.Width(130)))Run("Policy validation",_=>craftingResult=CraftingPolicySearcher.Validate(craftSearch,discovered,craftValidationTrials,Progress("Independent crafts"),()=>cancelled));}}craftValidationTrials=EditorGUILayout.IntPopup("Validation trials",craftValidationTrials,new[]{"1,000","10,000"},new[]{1000,10000});}
            if(GUILayout.Button("RUN CRAFTING SIMULATOR",GUILayout.Height(30)))Run("Crafting trials",_=>craftingResult=CraftingSimulator.Run(craftingRequest,Progress("Crafts"),()=>cancelled));if(craftingResult==null)return;if(craftingResult.Stale)EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);EditorGUILayout.LabelField("Success rate",craftingResult.trials==0?"n/a":$"{craftingResult.successes} / {craftingResult.trials} ({craftingResult.successes/(double)craftingResult.trials:P2})");if(craftingResult.successes==0&&craftingResult.trials>0)EditorGUILayout.LabelField("95% success upper bound",BreakpointFinder.WilsonInterval(0,craftingResult.trials).high.ToString("P2"));EditorGUILayout.LabelField("Potential / resource / progression failures",$"{craftingResult.potentialFailures} / {craftingResult.budgetFailures} / {craftingResult.progressionFailures}");Summary("Action count",craftingResult.actions);Summary("Final target matches",craftingResult.finalMatches);Summary("Potential at failed stop",craftingResult.failurePotential);foreach(var c in craftingResult.costs)EditorGUILayout.LabelField(c.currency.ToString(),$"Mean {c.mean:0.##} · P50 {c.p50:0.##} · P90 {c.p90:0.##} · P95 {c.p95:0.##} · P99 {c.p99:0.##}");foreach(var c in craftingResult.resourceCosts)EditorGUILayout.LabelField(c.resourceId,c.amount+" consumed");if(craftingResult.bestFailure?.finalItem!=null){if(GUILayout.Button("INSPECT BEST FAILURE"))EditorUtility.DisplayDialog("Best partial item",craftingResult.bestFailure.finalItem.Description,"Close");if(GUILayout.Button("REPLAY FAILURE"))status=WorkbenchExports.SaveJson("craft_best_failure_replay",craftingResult.bestFailure);}if(GUILayout.Button("SEND TARGET TO POLICY SEARCH")){craftSearch.simulation=JsonUtility.FromJson<CraftingSimulationRequest>(JsonUtility.ToJson(craftingRequest));status="Target copied to bounded policy search.";}if(craftingResult.replay!=null){Heading("REPLAY ATTEMPT");foreach(var step in craftingResult.replay.trace)EditorGUILayout.LabelField($"{step.number}. {step.operation} {step.action}",$"Potential {step.potentialBefore} → {step.potentialAfter} {step.failureReason}");if(GUILayout.Button("EXPORT TRACE JSON"))status=WorkbenchExports.SaveJson("craft_trace",craftingResult.replay);}
            if(GUILayout.Button("EXPORT CRAFTING CSV"))status=SaveAdvancedCsv("crafting_result","Trials,Successes,PotentialFailures,BudgetFailures,MedianActions,P90Actions",new[]{$"{craftingResult.trials},{craftingResult.successes},{craftingResult.potentialFailures},{craftingResult.budgetFailures},{craftingResult.actions.p50:R},{craftingResult.actions.p90:R}"});
        }

        static string CsvQ(string value)=>"\""+(value??"").Replace("\"","\"\"")+"\"";
        static string SaveAdvancedCsv(string name,string header,IEnumerable<string> rows){Directory.CreateDirectory(WorkbenchExports.Root);string path=Path.Combine(WorkbenchExports.Root,name+"_"+DateTime.UtcNow.ToString("yyyyMMdd_HHmmss")+".csv");File.WriteAllLines(path,new[]{header}.Concat(rows));AssetDatabase.Refresh();return path;}
    }
}
