using System;
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace BlackCube.BalanceWorkbench
{
    [Serializable] public sealed class OptimizationConstraints
    {
        public bool minimumLifeEnabled,minimumArmourEnabled,minimumFireResistanceEnabled,minimumColdResistanceEnabled,minimumLightningResistanceEnabled,minimumVoidResistanceEnabled;
        public float minimumLife,minimumArmour,minimumFireResistance,minimumColdResistance,minimumLightningResistance,minimumVoidResistance;
        public List<string> lockedPassiveIds=new(),excludedPassiveIds=new();public List<LootManager.GearType> lockedSlots=new();public int maximumOffClassPoints=-1;
        public bool Accept(PlayerBuildMetrics m)=>m!=null&&(!minimumLifeEnabled||m.life>=minimumLife)&&(!minimumArmourEnabled||m.armour>=minimumArmour)&&(!minimumFireResistanceEnabled||m.fireResistance>=minimumFireResistance)&&(!minimumColdResistanceEnabled||m.coldResistance>=minimumColdResistance)&&(!minimumLightningResistanceEnabled||m.lightningResistance>=minimumLightningResistance)&&(!minimumVoidResistanceEnabled||m.voidResistance>=minimumVoidResistance);
    }

    [Serializable] public sealed class GearCandidateResult{public GearSnapshot item;public double primaryDelta,secondaryDelta,score;}
    [Serializable] public sealed class GearOptimizationDebug{public int generated,retained,statesEvaluated,statesPruned,beamWidth;}
    [Serializable] public sealed class GearOptimizationResult
    {
        public PlayerBuildSnapshot build;public PlayerBuildMetrics baseline,metrics;public double score;public List<GearCandidateResult> selected=new(),candidates=new();public GearOptimizationDebug debug=new();public string profileName,profileGuid;public int profileVersion;
    }

    public static class PlayerGearsetOptimizer
    {
        static readonly LootManager.GearType[] Slots=(LootManager.GearType[])Enum.GetValues(typeof(LootManager.GearType));
        public static GearOptimizationResult Optimize(PlayerBuildSnapshot source,PlayerGearProfileSO profile,OptimizationObjective objective,bool thorough,OptimizationConstraints constraints=null,Action<float> progress=null,Func<bool> cancelled=null)
        {
            if(source==null||profile==null)throw new ArgumentNullException();constraints??=new();var baselineBuild=source.Clone();baselineBuild.equipment??=new();var baseline=PlayerBuildEvaluator.Evaluate(baselineBuild);var result=new GearOptimizationResult{baseline=baseline,profileName=profile.name,profileVersion=profile.version,profileGuid=AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(profile))};var rng=new SeededSimulationRandomSource(source.seed);using var session=new WorkbenchSession();var bySlot=new Dictionary<LootManager.GearType,List<GearCandidateResult>>();int itemLevel=profile.ResolveItemLevel(source.playerLevel,source.combatLevel);
            for(int si=0;si<Slots.Length;si++)
            {
                var slot=Slots[si];if(constraints.lockedSlots.Contains(slot)&&source.equipment.Any(x=>x.slot==slot)){bySlot[slot]=new(){new GearCandidateResult{item=source.equipment.First(x=>x.slot==slot)}};continue;}var list=new List<GearCandidateResult>();for(int i=0;i<Math.Max(1,profile.candidatesPerSlot);i++){if(cancelled?.Invoke()==true)break;var item=Generate(slot,itemLevel,source.weaponTypeId,profile,rng,session);var b=source.Clone();b.equipment.RemoveAll(x=>x.slot==slot);b.equipment.Add(item);var metrics=PlayerBuildEvaluator.Evaluate(b);list.Add(new GearCandidateResult{item=item,primaryDelta=OptimizationMetricCatalog.Get(objective.primary).Value(metrics)-OptimizationMetricCatalog.Get(objective.primary).Value(baseline),secondaryDelta=OptimizationMetricCatalog.Get(objective.secondary).Value(metrics)-OptimizationMetricCatalog.Get(objective.secondary).Value(baseline),score=OptimizationMetricCatalog.Score(metrics,baseline,objective)});result.debug.generated++;}var generated=list.ToList();var ordered=list.OrderByDescending(x=>x.score).ThenBy(x=>x.item.Description,StringComparer.Ordinal).ToList();list=profile.selectionStrategy switch{PlayerGearSelectionStrategy.RandomLegal=>generated.Take(1).ToList(),PlayerGearSelectionStrategy.PercentileTarget=>new(){ordered[Mathf.Clamp(Mathf.RoundToInt((1-profile.targetObjectivePercentile)*(ordered.Count-1)),0,ordered.Count-1)]},_=>ordered.Take(Math.Max(1,profile.candidateRetention)).ToList()};result.debug.retained+=list.Count;bySlot[slot]=list;result.candidates.AddRange(ordered);progress?.Invoke((si+1f)/(Slots.Length+1));}
            var states=new List<List<GearSnapshot>>{source.equipment.Where(x=>constraints.lockedSlots.Contains(x.slot)).ToList()};int beam=thorough||profile.selectionStrategy==PlayerGearSelectionStrategy.FullGearsetBeamSearch?Math.Max(1,profile.gearsetBeamWidth):1;result.debug.beamWidth=beam;
            for(int si=0;si<Slots.Length&&cancelled?.Invoke()!=true;si++)
            {
                var slot=Slots[si];var expanded=new List<(List<GearSnapshot> gear,double score,string key)>();foreach(var state in states)foreach(var c in bySlot[slot]){var next=new List<GearSnapshot>(state);next.RemoveAll(x=>x.slot==slot);next.Add(c.item);var b=source.Clone();b.equipment=next;var m=PlayerBuildEvaluator.Evaluate(b);result.debug.statesEvaluated++;if(!constraints.Accept(m))continue;expanded.Add((next,OptimizationMetricCatalog.Score(m,baseline,objective),Signature(next)));}states=expanded.GroupBy(x=>x.key).Select(x=>x.OrderByDescending(y=>y.score).First()).OrderByDescending(x=>x.score).ThenBy(x=>x.key,StringComparer.Ordinal).Take(beam).Select(x=>x.gear).ToList();result.debug.statesPruned+=Math.Max(0,expanded.Count-states.Count);if(states.Count==0)states.Add(new List<GearSnapshot>());progress?.Invoke((si+1f)/Slots.Length);}
            result.build=source.Clone();result.build.equipment=states[0];result.build.gearProfileGuid=result.profileGuid;result.build.gearProfileVersion=profile.version;result.build.dataFingerprint=ProductionBalanceAdapters.DataFingerprint();result.metrics=PlayerBuildEvaluator.Evaluate(result.build);result.score=OptimizationMetricCatalog.Score(result.metrics,baseline,objective);
            foreach(var item in result.build.equipment){var without=result.build.Clone();without.equipment.RemoveAll(x=>x.slot==item.slot);var wm=PlayerBuildEvaluator.Evaluate(without);result.selected.Add(new GearCandidateResult{item=item,primaryDelta=OptimizationMetricCatalog.Get(objective.primary).Value(result.metrics)-OptimizationMetricCatalog.Get(objective.primary).Value(wm),secondaryDelta=OptimizationMetricCatalog.Get(objective.secondary).Value(result.metrics)-OptimizationMetricCatalog.Get(objective.secondary).Value(wm),score=result.score-OptimizationMetricCatalog.Score(wm,baseline,objective)});}return result;
        }
        static GearSnapshot Generate(LootManager.GearType slot,int itemLevel,string weapon,PlayerGearProfileSO p,ILootRandomSource rng,WorkbenchSession session)
        {
            for(int outer=0;outer<128;outer++)
            {
                LootManager.GearRarity rarity=p.useNaturalRarity?NaturalRarity(itemLevel,rng):(LootManager.GearRarity)rng.Range((int)p.minimumRarity,(int)p.maximumRarity+1);if(!p.allowNaturalLegendaries&&rarity==LootManager.GearRarity.Legendary)rarity=LootManager.GearRarity.Rare;Element element=slot==LootManager.GearType.Weapons?RandomElement(rng):Element.Phys;var g=session.ReusableItem;g.Initialize(slot,rarity,itemLevel,element,slot==LootManager.GearType.Weapons?weapon:null);List<RolledMod> mods=null;for(int attempt=0;attempt<64&&mods==null;attempt++)mods=session.Roller.RollEquipmentModsForItem(slot,rarity,itemLevel,element,g.WeaponTypeId,rng);if(mods==null)continue;if(!p.allowEmpoweredModifiers&&mods.Any(x=>x.isEmpowered)||!p.allowBossSpecialModifiers&&mods.Any(x=>x.isBossSpecial))continue;g.ApplyMods(mods);if(slot==LootManager.GearType.Weapons)LootManager.ApplyNaturalWeaponProfile(g);return GearSnapshot.Capture(g);
            }throw new InvalidOperationException("Production item generation exhausted its bounded retry budget.");
        }
        static LootManager.GearRarity NaturalRarity(int level,ILootRandomSource rng){Vector4 r=LootManager.RarityRatesForLevel(level);float x=rng.Value()*100;return x<r.x?LootManager.GearRarity.Normal:x<r.x+r.y?LootManager.GearRarity.Magic:x<r.x+r.y+r.z?LootManager.GearRarity.Rare:LootManager.GearRarity.Legendary;}static Element RandomElement(ILootRandomSource r){int x=r.Range(0,5);return x<(int)Element.Poison?(Element)x:Element.Void;}static string Signature(IEnumerable<GearSnapshot> gear)=>string.Join("|",gear.OrderBy(x=>x.slot).Select(x=>$"{x.slot}:{x.rarity}:{string.Join(",",x.mods.Select(m=>$"{(int)m.stat}:{m.tier}:{m.value:R}"))}"));
    }

    [Serializable] public sealed class PassivePointResult{public int point,nodeId;public string stableId,name,branch,effect,alternative;public double primaryDelta,secondaryDelta,scoreDelta,scorePercent;}
    [Serializable] public sealed class PassiveSearchDebug{public int depth,candidateStates,uniqueStates,retainedStates,diversityGroups,statesEvaluated;public double bestScore;}
    [Serializable] public sealed class PassiveOptimizationResult
    {public PlayerBuildSnapshot build;public PlayerBuildMetrics baseline,metrics;public double score;public List<PassivePointResult> sequence=new();public List<PassiveSearchDebug> debug=new();public string algorithm;}
    [Serializable] public sealed class PassiveMarginalResult{public int nodeId,pathCost;public string stableId,name,branch,effect;public bool immediatelyLegal;public double primaryDelta,secondaryDelta,objectiveDelta,pathAdjustedValue,totalPackageGain;}

    public static class PassiveTreeOptimizer
    {
        sealed class State{public int[] ranks;public double score;public List<PassivePointResult> sequence;public PlayerBuildMetrics metrics;public string Key=>string.Join(",",Enumerable.Range(0,ranks.Length).Where(i=>ranks[i]!=0));}
        public static PassiveOptimizationResult Optimize(PlayerBuildSnapshot source,int points,OptimizationObjective objective,bool beamSearch,int beamWidth=500,OptimizationConstraints constraints=null,Action<float> progress=null,Func<bool> cancelled=null)
        {
            constraints??=new();points=Mathf.Clamp(points,0,100);var initial=source.Clone();foreach(string id in constraints.lockedPassiveIds)if(!initial.passiveStableIds.Contains(id))initial.passiveStableIds.Add(id);var baseline=PlayerBuildEvaluator.Evaluate(initial);var firstRanks=initial.AllocationRanks();if(!PlayerProgression.ValidateAllocationState(firstRanks,initial.classId,initial.subclassId))throw new InvalidOperationException("Initial/locked passive allocation is not production-legal.");var states=new List<State>{new(){ranks=firstRanks,metrics=baseline,sequence=new(),score=0}};var output=new PassiveOptimizationResult{baseline=baseline,algorithm=beamSearch?$"Beam {beamWidth}":"Greedy"};int target=Math.Max(firstRanks.Sum(),points);
            for(int depth=firstRanks.Sum();depth<target&&cancelled?.Invoke()!=true;depth++)
            {
                var expanded=new List<State>();foreach(var state in states)foreach(int node in LegalNext(state.ranks,initial.classId,initial.subclassId,constraints)){var ranks=(int[])state.ranks.Clone();ranks[node]=1;var b=initial.Clone();b.passiveStableIds=Ids(ranks);var metrics=PlayerBuildEvaluator.Evaluate(b);double score=OptimizationMetricCatalog.Score(metrics,baseline,objective);var n=PassiveTreeDefinition.Node(node);var step=new PassivePointResult{point=depth+1,nodeId=node,stableId=n.StableId,name=n.DisplayName,branch=n.IsWeaponRoute?n.RouteWeaponId:n.RouteClassId,effect=n.Description,primaryDelta=OptimizationMetricCatalog.Get(objective.primary).Value(metrics)-OptimizationMetricCatalog.Get(objective.primary).Value(state.metrics),secondaryDelta=OptimizationMetricCatalog.Get(objective.secondary).Value(metrics)-OptimizationMetricCatalog.Get(objective.secondary).Value(state.metrics),scoreDelta=score-state.score,scorePercent=state.score==0?score*100:(score-state.score)/Math.Max(.000001,Math.Abs(state.score))*100};var seq=new List<PassivePointResult>(state.sequence){step};expanded.Add(new State{ranks=ranks,metrics=metrics,score=score,sequence=seq});}
                var unique=expanded.GroupBy(x=>x.Key).Select(x=>x.OrderByDescending(y=>y.score).First()).ToList();int keep=beamSearch?Math.Max(1,beamWidth):1;var retained=DiverseRetain(unique,keep);output.debug.Add(new PassiveSearchDebug{depth=depth+1,candidateStates=expanded.Count,uniqueStates=unique.Count,retainedStates=retained.Count,diversityGroups=retained.Select(x=>Diversity(x.ranks)).Distinct().Count(),statesEvaluated=expanded.Count,bestScore=retained.Count>0?retained.Max(x=>x.score):0});states=retained;if(states.Count==0)break;progress?.Invoke((depth+1f)/Math.Max(1,target));
            }
            var best=states.OrderByDescending(x=>x.score).ThenBy(x=>x.Key,StringComparer.Ordinal).First();output.build=initial.Clone();output.build.passiveStableIds=Ids(best.ranks);output.metrics=best.metrics;output.score=best.score;output.sequence=best.sequence;return output;
        }
        public static List<int> LegalNext(int[] ranks,string classId,string subclassId,OptimizationConstraints constraints=null)
        {constraints??=new();var excluded=new HashSet<string>(constraints.excludedPassiveIds??new());var result=new List<int>();for(int id=0;id<ranks.Length;id++){var node=PassiveTreeDefinition.Node(id);if(ranks[id]!=0||excluded.Contains(node.StableId))continue;var copy=(int[])ranks.Clone();copy[id]=1;if(constraints.maximumOffClassPoints>=0){int off=0;foreach(var n in PassiveTreeDefinition.Nodes)if(copy[n.Id]!=0&&(n.IsClassRoute&&n.RouteClassId!=classId||n.IsWeaponRoute&&PassiveTreeDefinition.WeaponClass(n.RouteWeaponId)!=classId))off++;if(off>constraints.maximumOffClassPoints)continue;}if(PlayerProgression.ValidateAllocationState(copy,classId,subclassId))result.Add(id);}return result;}
        public static List<PassiveMarginalResult> Analyze(PlayerBuildSnapshot build,OptimizationObjective objective,OptimizationConstraints constraints=null,bool includeLocked=true)
        {
            constraints??=new();var baseline=PlayerBuildEvaluator.Evaluate(build);var ranks=build.AllocationRanks();var results=new List<PassiveMarginalResult>();foreach(var n in PassiveTreeDefinition.Nodes){if(ranks[n.Id]!=0||constraints.excludedPassiveIds.Contains(n.StableId))continue;var package=MinimumLegalPackage(ranks,n.Id,build.classId,build.subclassId);if(package==null||(package.Count>1&&!includeLocked))continue;var b=build.Clone();var next=(int[])ranks.Clone();foreach(int x in package)next[x]=1;b.passiveStableIds=Ids(next);var m=PlayerBuildEvaluator.Evaluate(b);double score=OptimizationMetricCatalog.Score(m,baseline,objective);results.Add(new PassiveMarginalResult{nodeId=n.Id,stableId=n.StableId,name=n.DisplayName,branch=n.IsWeaponRoute?n.RouteWeaponId:n.RouteClassId,effect=n.Description,immediatelyLegal=package.Count==1,pathCost=package.Count,primaryDelta=OptimizationMetricCatalog.Get(objective.primary).Value(m)-OptimizationMetricCatalog.Get(objective.primary).Value(baseline),secondaryDelta=OptimizationMetricCatalog.Get(objective.secondary).Value(m)-OptimizationMetricCatalog.Get(objective.secondary).Value(baseline),objectiveDelta=score,totalPackageGain=score,pathAdjustedValue=score/package.Count});}return results.OrderByDescending(x=>x.pathAdjustedValue).ThenBy(x=>x.stableId,StringComparer.Ordinal).ToList();
        }
        public static List<int> MinimumLegalPackage(int[] current,int target,string classId,string subclassId)
        {
            if(target<0||target>=current.Length||current[target]!=0)return new();var next=(int[])current.Clone();var add=new HashSet<int>();void AddClass(string c,int tier){if(c!=classId&&!PassiveTreeDefinition.IsClassSpineComplete(classId,i=>next[i]!=0||add.Contains(i)))for(int t=1;t<=10;t++)add.Add(PassiveTreeDefinition.ClassSpineNode(classId,t));for(int t=1;t<=tier;t++)add.Add(PassiveTreeDefinition.ClassSpineNode(c,t));}
            var n=PassiveTreeDefinition.Node(target);if(n.IsClassRoute)AddClass(n.RouteClassId,n.Tier);if(n.IsWeaponRoute){string owner=PassiveTreeDefinition.WeaponClass(n.RouteWeaponId);AddClass(owner,10);for(int t=1;t<=n.Tier;t++)add.Add(PassiveTreeDefinition.WeaponSpineNode(n.RouteWeaponId,t));}add.Add(target);foreach(int id in add)next[id]=1;if(!PlayerProgression.ValidateAllocationState(next,classId,subclassId))return null;return add.Where(x=>current[x]==0).OrderBy(x=>PassiveTreeDefinition.Node(x).Tier).ThenBy(x=>x).ToList();
        }
        static List<State> DiverseRetain(List<State> states,int width){var ordered=states.OrderByDescending(x=>x.score).ThenBy(x=>x.Key,StringComparer.Ordinal).ToList();if(ordered.Count<=width)return ordered;var result=new List<State>();foreach(var group in ordered.GroupBy(x=>Diversity(x.ranks)).OrderByDescending(g=>g.Max(x=>x.score)))if(result.Count<width)result.Add(group.First());foreach(var s in ordered)if(result.Count<width&&!result.Contains(s))result.Add(s);return result;}
        static string Diversity(int[] ranks){var classes=PassiveTreeDefinition.ClassIds.Select(c=>Enumerable.Range(1,10).Where(t=>ranks[PassiveTreeDefinition.ClassSpineNode(c,t)]!=0).DefaultIfEmpty(0).Max());var weapons=PassiveTreeDefinition.WeaponIds.Select(w=>Enumerable.Range(1,5).Where(t=>ranks[PassiveTreeDefinition.WeaponSpineNode(w,t)]!=0).DefaultIfEmpty(0).Max());return string.Join(".",classes.Concat(weapons));}static List<string> Ids(int[] ranks)=>Enumerable.Range(0,ranks.Length).Where(i=>ranks[i]!=0).Select(i=>PassiveTreeDefinition.Node(i).StableId).ToList();
    }

    [Serializable] public sealed class PlayerCurvePoint{public int playerLevel,combatLevel;public string profile;public PlayerBuildSnapshot build;public PlayerBuildMetrics metrics;public double objectiveScore;public long seed;}
    [Serializable] public sealed class ScenarioSweepResult{public List<PlayerCurvePoint> points=new();public string dataFingerprint;public List<CurveSeries> Curves(string metricId){var groups=points.GroupBy(x=>x.profile);return groups.Select((g,i)=>new CurveSeries{name=g.Key,color=Color.HSVToRGB((i*.23f)%1,.7f,.95f),points=g.OrderBy(x=>x.playerLevel).Select(x=>new CurvePoint{x=x.playerLevel,mean=OptimizationMetricCatalog.Get(metricId).Value(x.metrics)}).ToList()}).ToList();}}
    public static class PlayerScenarioSweep
    {
        public static ScenarioSweepResult Run(PlayerBuildSnapshot template,IEnumerable<PlayerGearProfileSO> profiles,OptimizationObjective objective,int start,int end,int step,bool optimizePassives,bool progressive,bool freeRespec,int passiveBeamWidth=100,Action<float> progress=null,Func<bool> cancelled=null)
        {var result=new ScenarioSweepResult{dataFingerprint=ProductionBalanceAdapters.DataFingerprint()};var list=profiles.Where(x=>x!=null).ToList();int total=Math.Max(1,list.Count*((end-start)/Math.Max(1,step)+1)),done=0;foreach(var profile in list){PlayerBuildSnapshot previous=null;for(int level=start;level<=end&&cancelled?.Invoke()!=true;level+=Math.Max(1,step)){var b=progressive&&previous!=null?previous.Clone():template.Clone();b.playerLevel=level;b.combatLevel=Mathf.Clamp(template.combatLevel+(level-start),1,360);b.seed=template.seed+level*7919+profile.version*101;var gear=PlayerGearsetOptimizer.Optimize(b,profile,objective,profile.selectionStrategy==PlayerGearSelectionStrategy.FullGearsetBeamSearch);b=gear.build;if(optimizePassives){if(freeRespec||!progressive)b.passiveStableIds.Clear();b=PassiveTreeOptimizer.Optimize(b,level,objective,passiveBeamWidth>1,passiveBeamWidth).build;}var metrics=PlayerBuildEvaluator.Evaluate(b);result.points.Add(new PlayerCurvePoint{playerLevel=level,combatLevel=b.combatLevel,profile=profile.name,build=b,metrics=metrics,objectiveScore=OptimizationMetricCatalog.Score(metrics,gear.baseline,objective),seed=b.seed});previous=b;progress?.Invoke(++done/(float)total);}}return result;}
        public static double AnalyticalTtk(PlayerBuildMetrics player,EnemySample enemy)=>enemy==null||player==null||player.basicDps<=0?double.PositiveInfinity:enemy.life/player.basicDps;public static double AnalyticalTtd(PlayerBuildMetrics player,EnemySample enemy)=>enemy==null||player==null||enemy.dps<=0?double.PositiveInfinity:player.life/enemy.dps;
    }
}
