using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace BlackCube.BalanceWorkbench
{
    public sealed partial class BalanceWorkbenchWindow
    {
        SensitivityRequest sensitivity=new(); SensitivityResult sensitivityResult; List<SensitivityPair> sensitivityPairs=new();List<CurvePoint> sensitivityCurve=new();
        enum ImpactSort{Absolute,MostPositive,MostNegative}
        StatTypes curveStat=StatTypes.AttackSpeed; bool[] chosenStats;ImpactSort impactSort;
        BalanceSuite balanceSuite=new();BalanceSnapshot beforeSnapshot,afterSnapshot;List<BalanceDifference> differences=new();double highlightPercent=.10;string snapshotName="Before";
        enum BreakSource{PlayerAnalytical,EnemyGear,Combat,Drops,LootProgression}
        int breakStart=1,breakEnd=100,breakStep=10;double breakThreshold=.70;BreakpointOperator breakOperator=BreakpointOperator.Less;string breakMetric="win_rate";BreakSource breakSource=BreakSource.Combat;bool breakAll;List<BreakpointResult> breakResults=new();
        string reportTitle="Balance review";string reportPath;
        AffixAnalysisRequest affixRequest=new();AffixAnalysisResult affixResult;List<AffixCombatRow> affixCombat=new();int affixCombatCount=5;
        LootProgressionRequest lootRequest=new();LootProgressionResult lootResult;List<LootProgressionResult> lootComparison=new();List<CurvePoint> lootSweep=new();int lootComparisonKills=1000;
        CraftingSimulationRequest craftingRequest=new();CraftingSimulationResult craftingResult;List<CraftingSimulationRequest> craftPolicies=new();List<CraftingSimulationResult> craftComparisons=new();

        void SensitivityTab()
        {
            Heading("PRODUCTION STAT SENSITIVITY");EditorGUILayout.HelpBox("Absolute inputs are flat points or fraction-of-one percentage points according to the selected stat. Relative inputs scale the current measured stat; a zero baseline uses a one-unit reference. Analytical mode evaluates the production build; combat mode uses common fight seeds.",MessageType.Info);
            sensitivity.mode=(SensitivityMode)EditorGUILayout.EnumPopup("Mode",sensitivity.mode);sensitivity.perturbation=(PerturbationMode)EditorGUILayout.EnumPopup("Change",sensitivity.perturbation);sensitivity.amount=EditorGUILayout.FloatField("Input change",sensitivity.amount);using(new EditorGUILayout.HorizontalScope()){foreach(float preset in new[]{-.1f,-.05f,.01f,.05f,.10f})if(GUILayout.Button(preset.ToString("+0%;-0%")))sensitivity.amount=preset;}
            string[] metrics=sensitivity.mode==SensitivityMode.Combat?new[]{"win_rate","p50_ttk","p90_ttk","mana_starvation","combat_dps"}:OptimizationMetricCatalog.All.Select(x=>x.Id).ToArray();sensitivity.metric=metrics[EditorGUILayout.Popup("Output metric",Mathf.Max(0,Array.IndexOf(metrics,sensitivity.metric)),metrics)];
            if(sensitivity.mode==SensitivityMode.Combat){EnsureCombat();combatRequest.fightCount=EditorGUILayout.IntField("Fights / variation",Mathf.Max(1,combatRequest.fightCount));combatRequest.seed=EditorGUILayout.LongField("Common seed",combatRequest.seed);}
            if(chosenStats==null||chosenStats.Length!=SensitivityAnalyzer.Catalog.Length){chosenStats=new bool[SensitivityAnalyzer.Catalog.Length];for(int i=0;i<chosenStats.Length;i++)chosenStats[i]=sensitivity.stats.Contains(SensitivityAnalyzer.Catalog[i]);}
            Heading("SELECT STATS");for(int i=0;i<SensitivityAnalyzer.Catalog.Length;i++){var stat=SensitivityAnalyzer.Catalog[i];chosenStats[i]=EditorGUILayout.ToggleLeft(stat+" ("+SensitivityAnalyzer.Unit(stat)+")",chosenStats[i]);}
            using(new EditorGUILayout.HorizontalScope())
            {
                if(GUILayout.Button("RUN SENSITIVITY",GUILayout.Height(30)))Run("Sensitivity",_=>{sensitivity.build=playerBuild.Clone();sensitivity.combat=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));sensitivity.stats=SensitivityAnalyzer.Catalog.Where((s,i)=>chosenStats[i]).ToList();sensitivityResult=SensitivityAnalyzer.Run(sensitivity,Progress("Stats"),()=>cancelled);});
                if(GUILayout.Button("PAIR ANALYSIS"))Run("Pair analysis",_=>{sensitivity.build=playerBuild.Clone();sensitivity.stats=SensitivityAnalyzer.Catalog.Where((s,i)=>chosenStats[i]).Take(12).ToList();sensitivityPairs=SensitivityAnalyzer.Pairs(sensitivity,sensitivity.stats,()=>cancelled);});
                if(GUILayout.Button("CURVE"))Run("Sensitivity curve",_=>{sensitivity.build=playerBuild.Clone();sensitivityCurve=SensitivityAnalyzer.Curve(sensitivity,curveStat,new[]{-.2f,-.1f,0f,.1f,.2f,.3f});});
            }
            curveStat=(StatTypes)EditorGUILayout.EnumPopup("Curve stat",curveStat);
            if(sensitivityResult!=null){if(sensitivityResult.Stale)EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);Heading("RANKED IMPACT");impactSort=(ImpactSort)EditorGUILayout.EnumPopup("Sort",impactSort);var ordered=impactSort switch{ImpactSort.MostPositive=>sensitivityResult.rows.OrderByDescending(x=>x.absoluteDelta),ImpactSort.MostNegative=>sensitivityResult.rows.OrderBy(x=>x.absoluteDelta),_=>sensitivityResult.rows.OrderByDescending(x=>Math.Abs(x.absoluteDelta))};foreach(var x in ordered)EditorGUILayout.LabelField(x.stat.ToString(),$"{x.baseline:0.###} → {x.modified:0.###}  Δ{x.absoluteDelta:+0.###;-0.###;0}  {x.percentDelta:+0.##%;-0.##%;0%}  elasticity {x.elasticity:0.###}");if(GUILayout.Button("EXPORT CSV"))status=SaveAdvancedCsv("sensitivity","Stat,InputDelta,Baseline,Modified,AbsoluteDelta,PercentDelta,Elasticity",sensitivityResult.rows.Select(x=>$"{x.stat},{x.inputDelta:R},{x.baseline:R},{x.modified:R},{x.absoluteDelta:R},{x.percentDelta:R},{x.elasticity:R}"));}
            if(sensitivityCurve.Count>0){Heading("MULTI-POINT CURVE");foreach(var x in sensitivityCurve)EditorGUILayout.LabelField(x.x.ToString("+0%;-0%;0%"),x.mean.ToString("0.####"));var series=new List<CurveSeries>{new(){name=curveStat.ToString(),color=Color.cyan,points=sensitivityCurve}};chart.Draw(GUILayoutUtility.GetRect(200,260,GUILayout.ExpandWidth(true)),series,"Stat change",sensitivity.metric);if(GUILayout.Button("EXPORT CURVE PNG"))status=chart.ExportPng(series,"sensitivity_curve");}
            if(sensitivityPairs.Count>0){Heading("PAIR INTERACTIONS (observed − A − B)");foreach(var x in sensitivityPairs)EditorGUILayout.LabelField(x.a+" × "+x.b,x.interaction.ToString("+0.####;-0.####;0"));if(GUILayout.Button("EXPORT PAIRS CSV"))status=SaveAdvancedCsv("sensitivity_pairs","StatA,StatB,GainA,GainB,Observed,Interaction",sensitivityPairs.Select(x=>$"{x.a},{x.b},{x.gainA:R},{x.gainB:R},{x.observed:R},{x.interaction:R}"));}
            if(GUILayout.Button("SEND TO COMBAT LAB"))tab=Tab.CombatLab;
        }

        void SnapshotTab()
        {
            Heading("USER-EDITABLE SCENARIO SUITE");balanceSuite.name=EditorGUILayout.TextField("Suite",balanceSuite.name);snapshotName=EditorGUILayout.TextField("Snapshot name",snapshotName);highlightPercent=EditorGUILayout.DoubleField("Highlight relative change",highlightPercent);
            if(GUILayout.Button("ADD CURRENT PLAYER SCENARIO"))balanceSuite.scenarios.Add(new BalanceScenario{name="Player "+playerBuild.classId+" L"+playerBuild.playerLevel,build=playerBuild.Clone(),metric=objective.primary});
            if(GUILayout.Button("ADD CURRENT COMBAT SCENARIO")){EnsureCombat();balanceSuite.scenarios.Add(new BalanceScenario{name="Combat L"+combatRequest.enemyLevel,source="Combat",metric="win_rate",combat=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest))});}
            if(GUILayout.Button("ADD CURRENT DROP SCENARIO"))balanceSuite.scenarios.Add(new BalanceScenario{name="Drops L"+drop.level,source="Drops",metric="currency_per_kill",drop=JsonUtility.FromJson<DropLabRequest>(JsonUtility.ToJson(drop))});
            if(GUILayout.Button("ADD SENSITIVITY SCENARIO")){var r=JsonUtility.FromJson<SensitivityRequest>(JsonUtility.ToJson(sensitivity));r.build=playerBuild.Clone();balanceSuite.scenarios.Add(new BalanceScenario{name="Sensitivity "+playerBuild.classId,source="Sensitivity",metric="max_absolute_impact",sensitivity=r});}
            if(GUILayout.Button("ADD AFFIX SCENARIO")){var r=JsonUtility.FromJson<AffixAnalysisRequest>(JsonUtility.ToJson(affixRequest));r.build=playerBuild.Clone();balanceSuite.scenarios.Add(new BalanceScenario{name="Affix "+r.slot,source="Affix",metric="best_objective_delta",affix=r});}
            if(GUILayout.Button("ADD LOOT SCENARIO")){var r=JsonUtility.FromJson<LootProgressionRequest>(JsonUtility.ToJson(lootRequest));r.build=playerBuild.Clone();balanceSuite.scenarios.Add(new BalanceScenario{name="Loot L"+r.combatLevel,source="Loot Progression",metric="upgrades_per_100",loot=r});}
            if(craftingRequest.item!=null&&GUILayout.Button("ADD CRAFTING SCENARIO"))balanceSuite.scenarios.Add(new BalanceScenario{name="Crafting "+craftingRequest.item.slot,source="Crafting",metric="success_rate",crafting=JsonUtility.FromJson<CraftingSimulationRequest>(JsonUtility.ToJson(craftingRequest))});
            for(int i=0;i<balanceSuite.scenarios.Count;i++){var s=balanceSuite.scenarios[i];using(new EditorGUILayout.HorizontalScope()){s.name=EditorGUILayout.TextField(s.name);s.metric=EditorGUILayout.TextField(s.metric);if(GUILayout.Button("Remove",GUILayout.Width(70))){balanceSuite.scenarios.RemoveAt(i--);continue;}}}
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("CAPTURE BEFORE",GUILayout.Height(30)))Run("Snapshot before",_=>beforeSnapshot=BalanceSnapshotService.Capture(balanceSuite,snapshotName,Progress("Suite"),()=>cancelled));if(GUILayout.Button("CAPTURE AFTER"))Run("Snapshot after",_=>{afterSnapshot=BalanceSnapshotService.Capture(balanceSuite,snapshotName,Progress("Suite"),()=>cancelled);if(beforeSnapshot!=null)differences=BalanceSnapshotService.Compare(beforeSnapshot,afterSnapshot,highlightPercent);});if(GUILayout.Button("COMPARE TO CURRENT")&&beforeSnapshot!=null)Run("Compare current",_=>{afterSnapshot=BalanceSnapshotService.Capture(beforeSnapshot.suite,"Current production",Progress("Suite"),()=>cancelled);differences=BalanceSnapshotService.Compare(beforeSnapshot,afterSnapshot,highlightPercent);});}
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SAVE SUITE JSON"))status=WorkbenchExports.SaveJson("balance_suite",balanceSuite);if(GUILayout.Button("LOAD SUITE JSON")){string path=EditorUtility.OpenFilePanel("Load balance suite",WorkbenchExports.Root,"json");if(!string.IsNullOrEmpty(path))balanceSuite=JsonUtility.FromJson<BalanceSuite>(File.ReadAllText(path));}if(GUILayout.Button("LOAD BEFORE JSON")){string path=EditorUtility.OpenFilePanel("Load balance snapshot",WorkbenchExports.Root,"json");if(!string.IsNullOrEmpty(path))beforeSnapshot=JsonUtility.FromJson<BalanceSnapshot>(File.ReadAllText(path));}}
            if(beforeSnapshot!=null){EditorGUILayout.LabelField("Before",beforeSnapshot.timestampUtc+" · "+beforeSnapshot.fingerprint);if(beforeSnapshot.fingerprint!=ProductionBalanceAdapters.DataFingerprint())EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);if(GUILayout.Button("EXPORT BEFORE JSON"))status=WorkbenchExports.SaveJson("snapshot_before",beforeSnapshot);}
            if(afterSnapshot!=null){EditorGUILayout.LabelField("After",afterSnapshot.timestampUtc+" · "+afterSnapshot.fingerprint);if(GUILayout.Button("EXPORT AFTER JSON"))status=WorkbenchExports.SaveJson("snapshot_after",afterSnapshot);}
            if(differences.Count>0){Heading("REGRESSION COMPARISON");foreach(var x in differences){EditorGUILayout.LabelField((x.highlighted?"▲ ":"")+x.scenario+" / "+x.metric,$"{x.before:0.###} → {x.after:0.###} ({x.percent:+0.##%;-0.##%;0%})");}if(GUILayout.Button("EXPORT COMPARISON CSV"))status=SaveAdvancedCsv("snapshot_comparison","Scenario,Source,Metric,Before,After,Delta,Percent,Highlighted",differences.Select(x=>$"{CsvQ(x.scenario)},{CsvQ(x.source)},{CsvQ(x.metric)},{x.before:R},{x.after:R},{x.delta:R},{x.percent:R},{x.highlighted}"));}
        }

        void BreakpointTab()
        {
            Heading("SCAN THEN REFINE");breakSource=(BreakSource)EditorGUILayout.EnumPopup("Source",breakSource);breakStart=EditorGUILayout.IntField("Start level",breakStart);breakEnd=EditorGUILayout.IntField("End level",breakEnd);breakStep=EditorGUILayout.IntField("Coarse step",breakStep);breakMetric=EditorGUILayout.TextField("Metric ID",breakMetric);breakThreshold=EditorGUILayout.DoubleField("Threshold",breakThreshold);breakOperator=(BreakpointOperator)EditorGUILayout.EnumPopup("Rule",breakOperator);breakAll=EditorGUILayout.Toggle("All crossings",breakAll);
            EditorGUILayout.HelpBox("Metric IDs: Combat win_rate/p50_ttk/p90_ttk/mana_starvation; Enemy dps_p50/life_p50; Drops gear_per_kill/currency_per_kill; Loot upgrades_per_100; Player uses the Player Build metric catalog.",MessageType.None);
            if(GUILayout.Button("FIND BREAKPOINT",GUILayout.Height(30)))Run("Breakpoint scan",_=>{EnsureCombat();breakResults=BreakpointFinder.Find(level=>BreakMetricAt(level),Mathf.Max(1,breakStart),Mathf.Max(breakStart,breakEnd),Mathf.Max(1,breakStep),breakThreshold,breakOperator,breakAll);foreach(var r in breakResults){r.metric=breakMetric;r.seed=combatRequest.seed;r.samples=breakSource==BreakSource.Combat?combatRequest.fightCount:breakSource==BreakSource.Drops?drop.sampleCount:1;r.fingerprint=ProductionBalanceAdapters.DataFingerprint();}});
            if(breakResults.Count>0){Heading("CROSSINGS");foreach(var r in breakResults)EditorGUILayout.LabelField("Level "+r.level,$"{r.before:0.####} → {r.at:0.####}; threshold {r.threshold:0.####}");var first=breakResults[0];var metricSeries=new CurveSeries{name=breakMetric,color=Color.cyan,points=first.curve.Select(x=>new CurvePoint{x=x.level,mean=x.value}).ToList()};var thresholdSeries=new CurveSeries{name="Threshold",color=Color.yellow,points=new(){new CurvePoint{x=breakStart,mean=breakThreshold},new CurvePoint{x=breakEnd,mean=breakThreshold}}};var plot=new List<CurveSeries>{metricSeries,thresholdSeries};chart.Draw(GUILayoutUtility.GetRect(200,280,GUILayout.ExpandWidth(true)),plot,"Level",breakMetric);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("EXPORT CSV"))status=SaveAdvancedCsv("breakpoints","Level,Metric,Before,At,After,Threshold,Samples,Seed,Fingerprint",breakResults.Select(x=>$"{x.level},{x.metric},{x.before:R},{x.at:R},{x.after:R},{x.threshold:R},{x.samples},{x.seed},{x.fingerprint}"));if(GUILayout.Button("EXPORT PNG"))status=chart.ExportPng(plot,"breakpoints");}}
        }

        double BreakMetricAt(int level)
        {
            switch(breakSource)
            {
                case BreakSource.Combat:{var request=JsonUtility.FromJson<CombatLabRequest>(JsonUtility.ToJson(combatRequest));request.enemyLevel=level;var r=CombatLabAdapters.Batch(request);return breakMetric switch{"p50_ttk"=>r.duration.p50,"p90_ttk"=>r.duration.p90,"mana_starvation"=>r.manaStarvation.mean,_=>r.winRate};}
                case BreakSource.EnemyGear:{var r=ProductionBalanceAdapters.RunEnemies(new EnemyLabRequest{level=level,sampleCount=64,seed=combatRequest.seed,archetypeId=combatRequest.enemyArchetypeId,rarity=combatRequest.rarity});return breakMetric=="life_p50"?r.life.p50:r.dps.p50;}
                case BreakSource.Drops:{var request=JsonUtility.FromJson<DropLabRequest>(JsonUtility.ToJson(drop));request.level=level;var r=ProductionBalanceAdapters.RunDrops(request);return breakMetric=="gear_per_kill"?r.averageGearItems:r.averageCurrencyRolls;}
                case BreakSource.LootProgression:{var request=JsonUtility.FromJson<LootProgressionRequest>(JsonUtility.ToJson(lootRequest));request.combatLevel=level;request.kills=Mathf.Min(1000,request.kills);var r=LootProgressionAnalyzer.Run(request);return r.upgrades.Count*100.0/Math.Max(1,r.kills);}
                default:{var b=playerBuild.Clone();b.playerLevel=level;return OptimizationMetricCatalog.Get(breakMetric).Value(PlayerBuildEvaluator.Evaluate(b));}
            }
        }

        void ReportTab()
        {
            Heading("DESIGNER BALANCE REPORT");reportTitle=EditorGUILayout.TextField("Title",reportTitle);EditorGUILayout.HelpBox("Uses the user-editable suite configured in Balance Snapshots. No universal balance score or automatic production edits.",MessageType.Info);if(GUILayout.Button("OPEN SNAPSHOT SUITE"))tab=Tab.BalanceSnapshots;
            if(GUILayout.Button("RUN REPORT",GUILayout.Height(32)))Run("Balance report",_=>{var snapshot=BalanceSnapshotService.Capture(balanceSuite,reportTitle,Progress("Report"),()=>cancelled);reportPath=BalanceSnapshotService.ExportMarkdown(snapshot,differences);WorkbenchExports.SaveJson("report_metadata",snapshot);status=reportPath;});if(!string.IsNullOrEmpty(reportPath))EditorGUILayout.SelectableLabel(reportPath,EditorStyles.textField,GUILayout.Height(20));
        }

        void AffixTab()
        {
            Heading("PRODUCTION MOD DATABASE");affixRequest.slot=(LootManager.GearType)EditorGUILayout.EnumPopup("Slot",affixRequest.slot);affixRequest.itemLevel=EditorGUILayout.IntSlider("Item level",affixRequest.itemLevel,1,100);affixRequest.rarity=(LootManager.GearRarity)EditorGUILayout.EnumPopup("Rarity",affixRequest.rarity);if(affixRequest.slot==LootManager.GearType.Weapons){affixRequest.weaponTypeId=PopupValue("Weapon",affixRequest.weaponTypeId,WeaponTypeCatalog.All.Select(x=>x.Id).ToArray());affixRequest.element=(Element)EditorGUILayout.EnumPopup("Element",affixRequest.element);}affixRequest.rollPercent=EditorGUILayout.Slider("Roll position",affixRequest.rollPercent,0,1);affixRequest.allTiers=EditorGUILayout.Toggle("Analyze all legal tiers",affixRequest.allTiers);affixRequest.pairTop=EditorGUILayout.IntSlider("Pair top N",affixRequest.pairTop,2,12);affixRequest.replaceCurrentMod=EditorGUILayout.Toggle("Replace current mod",affixRequest.replaceCurrentMod);if(affixRequest.replaceCurrentMod)affixRequest.replacedStat=(StatTypes)EditorGUILayout.EnumPopup("Mod to replace",affixRequest.replacedStat);
            EditorGUILayout.HelpBox("Scores legal additions from the production ModDatabase and build evaluator. A full item needs Replace Current Mod enabled. Combat shortlist validation is not yet available.",MessageType.Info);
            if(GUILayout.Button("ANALYZE LEGAL AFFIXES",GUILayout.Height(30)))Run("Affix analysis",_=>{affixRequest.build=playerBuild.Clone();affixRequest.objective=JsonUtility.FromJson<OptimizationObjective>(JsonUtility.ToJson(objective));affixResult=AffixAnalyzer.Run(affixRequest,()=>cancelled);});
            if(affixResult==null)return;if(affixResult.Stale)EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);Heading("RANKED AFFIXES");foreach(var row in affixResult.rows.Take(80))EditorGUILayout.LabelField($"{row.name} T{row.tier} ({row.side})",$"Roll {row.roll:0.###} · Primary {row.primaryDelta:+0.###;-0.###;0} · Objective {row.objectiveDelta:+0.####;-0.####;0}");
            if(GUILayout.Button("EXPORT AFFIX CSV"))status=SaveAdvancedCsv("affix_ranking","Stat,Name,Side,Tier,MinLevel,Roll,PrimaryDelta,SecondaryDelta,ObjectiveDelta",affixResult.rows.Select(x=>$"{x.stat},{CsvQ(x.name)},{x.side},{x.tier},{x.itemLevel},{x.roll:R},{x.primaryDelta:R},{x.secondaryDelta:R},{x.objectiveDelta:R}"));
            affixCombatCount=EditorGUILayout.IntSlider("Combat shortlist",affixCombatCount,1,10);if(GUILayout.Button("COMBAT TEST TOP N"))Run("Affix combat shortlist",_=>{EnsureCombat();affixCombat=AffixAnalyzer.CombatValidateTop(affixRequest,affixResult,combatRequest,affixCombatCount,Progress("Affixes"),()=>cancelled);});if(affixCombat.Count>0){Heading("COMBAT DELTAS VS CURRENT BUILD");foreach(var row in affixCombat)EditorGUILayout.LabelField(row.affix,$"Win {row.winRateDelta:+0.##%;-0.##%;0%} · P50 {row.p50DurationDelta:+0.##;-0.##;0}s · DPS {row.dpsDelta:+0.##;-0.##;0}");}
            Heading("TOP-PAIR INTERACTIONS");foreach(var pair in affixResult.pairs)EditorGUILayout.LabelField(pair.a+" × "+pair.b,pair.interaction.ToString("+0.####;-0.####;0"));if(affixResult.pairs.Count>0&&GUILayout.Button("EXPORT PAIR CSV"))status=SaveAdvancedCsv("affix_pairs","AffixA,AffixB,GainA,GainB,Combined,Interaction",affixResult.pairs.Select(x=>$"{x.a},{x.b},{x.gainA:R},{x.gainB:R},{x.combined:R},{x.interaction:R}"));
            if(GUILayout.Button("SELECT MOD DATABASE")){var db=AssetDatabase.LoadAssetAtPath<ModDatabase>("Assets/Prefabs/Scriptable Objects/ModDatabase.asset");Selection.activeObject=db;EditorGUIUtility.PingObject(db);}
        }

        void LootTab()
        {
            Heading("PER-KILL PRODUCTION LOOT / BUILD UPGRADES");lootRequest.combatLevel=EditorGUILayout.IntSlider("Combat level",lootRequest.combatLevel,1,360);lootRequest.rarity=(EnemyAI.EnemyRarity)EditorGUILayout.EnumPopup("Enemy rarity",lootRequest.rarity);lootRequest.boss=EditorGUILayout.Toggle("Boss source",lootRequest.boss);lootRequest.generateActualEnemyGear=EditorGUILayout.Toggle("Sample actual enemy gear",lootRequest.generateActualEnemyGear);if(lootRequest.generateActualEnemyGear){EnsureEnemySelection();lootRequest.archetypeId=PopupValue("Archetype",lootRequest.archetypeId,new[]{"Any"}.Concat(EnemyDb.enemyArchetypes.Select(x=>x.stableId)).ToArray());}lootRequest.progressive=EditorGUILayout.Toggle("Progressive auto-equip",lootRequest.progressive);lootRequest.minimumImprovement=EditorGUILayout.DoubleField("Minimum objective gain",lootRequest.minimumImprovement);lootRequest.kills=SampleCount(lootRequest.kills,100000);lootRequest.seed=EditorGUILayout.LongField("Seed",lootRequest.seed);EditorGUILayout.HelpBox("Each kill rolls production loot budgets, currency selection, item slots, rarity and affixes. Actual enemy gear sampling reuses the Enemy Gear Lab population path (up to 1,000 samples).",MessageType.Info);
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SIMULATE UPGRADES",GUILayout.Height(30)))Run("Loot progression",_=>{lootRequest.build=playerBuild.Clone();lootRequest.objective=JsonUtility.FromJson<OptimizationObjective>(JsonUtility.ToJson(objective));lootResult=LootProgressionAnalyzer.Run(lootRequest,Progress("Kills"),()=>cancelled);});if(GUILayout.Button("COMPARE RARITIES"))Run("Loot source comparison",_=>{lootComparison.Clear();foreach(EnemyAI.EnemyRarity rarity in Enum.GetValues(typeof(EnemyAI.EnemyRarity))){if(cancelled)break;var request=JsonUtility.FromJson<LootProgressionRequest>(JsonUtility.ToJson(lootRequest));request.build=playerBuild.Clone();request.objective=objective;request.rarity=rarity;request.kills=lootComparisonKills;var compared=LootProgressionAnalyzer.Run(request,Progress(rarity.ToString()),()=>cancelled);compared.metadata.scenario=rarity.ToString();lootComparison.Add(compared);}});}
            lootComparisonKills=EditorGUILayout.IntSlider("Comparison kills / source",lootComparisonKills,100,10000);
            if(gearProfile!=null&&GUILayout.Button("LEVEL SWEEP WITH SELECTED GEAR PROFILE"))Run("Loot level sweep",_=>{lootSweep.Clear();for(int level=10;level<=100&&!cancelled;level+=10){var seedBuild=playerBuild.Clone();seedBuild.playerLevel=level;seedBuild.combatLevel=level;var optimized=PlayerGearsetOptimizer.Optimize(seedBuild,gearProfile,objective,false);var request=JsonUtility.FromJson<LootProgressionRequest>(JsonUtility.ToJson(lootRequest));request.build=optimized.build;request.combatLevel=level;request.kills=lootComparisonKills;var result=LootProgressionAnalyzer.Run(request,Progress("Level "+level),()=>cancelled);lootSweep.Add(new CurvePoint{x=level,mean=result.upgrades.Count==0?double.PositiveInfinity:result.kills/(double)result.upgrades.Count});}});
            if(lootComparison.Count>0){Heading("SOURCE COMPARISON");foreach(var r in lootComparison)EditorGUILayout.LabelField(r.metadata.scenario,$"{r.upgrades.Count} upgrades / {r.kills} kills");}
            if(lootSweep.Count>0){Heading("KILLS PER UPGRADE BY LEVEL");foreach(var point in lootSweep)EditorGUILayout.LabelField("Level "+point.x,point.mean.ToString("0.##"));}
            if(lootResult==null)return;if(lootResult.Stale)EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);
            EditorGUILayout.LabelField("Kills / drops / upgrades",$"{lootResult.kills} / {lootResult.drops} / {lootResult.upgrades.Count}");EditorGUILayout.LabelField("First upgrade kill",lootResult.firstUpgradeKill==0?"Not found":lootResult.firstUpgradeKill.ToString());EditorGUILayout.LabelField("Kills with ≥1 upgrade",$"{lootResult.killsWithUpgrade} ({lootResult.killsWithUpgrade/(double)Math.Max(1,lootResult.kills):P2})");EditorGUILayout.LabelField("Upgrades / 100 / 1,000 kills",$"{lootResult.upgrades.Count*100.0/Math.Max(1,lootResult.kills):0.##} / {lootResult.upgrades.Count*1000.0/Math.Max(1,lootResult.kills):0.##}");Summary("Kills between upgrades",lootResult.upgradeIntervals);Summary("Upgrade magnitude",lootResult.upgradeMagnitudes);Heading("PER SLOT");foreach(var g in lootResult.upgrades.GroupBy(x=>x.slot))EditorGUILayout.LabelField(g.Key,$"{g.Count()} upgrades · {lootResult.kills/(double)g.Count():0.##} kills / upgrade");Heading("PER RARITY");foreach(var g in lootResult.upgrades.GroupBy(x=>x.rarity))EditorGUILayout.LabelField(g.Key,g.Count().ToString());Heading("CURRENCY ACCUMULATION");foreach(var c in lootResult.currency)EditorGUILayout.LabelField(c.type.ToString(),$"{c.amount} total · {c.amount*100.0/Math.Max(1,lootResult.kills):0.##} / 100 kills · {c.amount/(double)Math.Max(1,lootResult.upgrades.Count):0.##} / upgrade");
            if(lootResult.upgrades.Count>0){var best=lootResult.upgrades.OrderByDescending(x=>x.magnitude).First();if(GUILayout.Button("INSPECT BEST DROPPED ITEM"))EditorUtility.DisplayDialog($"Upgrade at kill {best.kill}",best.item.Description+"\nObjective gain "+best.magnitude.ToString("0.####"),"Close");}
            if(GUILayout.Button("EXPORT PROGRESSION CSV"))status=SaveAdvancedCsv("loot_progression","Kill,Slot,Rarity,ObjectiveGain,Item",lootResult.upgrades.Select(x=>$"{x.kill},{x.slot},{x.rarity},{x.magnitude:R},{CsvQ(x.item.Description)}"));
        }

        void CraftingTab()
        {
            Heading("PRODUCTION CRAFTING TRIALS");if(GUILayout.Button("USE CURRENT BUILD WEAPON")){craftingRequest.item=playerBuild.equipment.FirstOrDefault(x=>x.slot==LootManager.GearType.Weapons);if(craftingRequest.item==null)status="No equipped weapon in current build.";}if(craftingRequest.item!=null)EditorGUILayout.HelpBox(craftingRequest.item.Description,MessageType.None);
            craftingRequest.trials=SampleCount(craftingRequest.trials,100000);craftingRequest.maxActions=EditorGUILayout.IntSlider("Max actions / attempt",craftingRequest.maxActions,1,1000);craftingRequest.seed=EditorGUILayout.LongField("Seed",craftingRequest.seed);craftingRequest.requiredMatches=EditorGUILayout.IntSlider("Required matching affixes",craftingRequest.requiredMatches,1,6);
            Heading("TARGET CONDITIONS");foreach(var t in craftingRequest.targets){using(new EditorGUILayout.HorizontalScope()){t.stat=(StatTypes)EditorGUILayout.EnumPopup(t.stat);t.maximumTier=EditorGUILayout.IntField("Tier ≤",t.maximumTier);t.minimumRoll=EditorGUILayout.FloatField("Roll ≥",t.minimumRoll);}}if(GUILayout.Button("ADD TARGET"))craftingRequest.targets.Add(new CraftTarget{stat=StatTypes.PhysDmg});
            Heading("ORDERED ACTION POLICY");foreach(var step in craftingRequest.policy){using(new EditorGUILayout.HorizontalScope()){step.action=(CraftingCurrencyType)EditorGUILayout.EnumPopup(step.action);step.repeats=EditorGUILayout.IntField("Repeats",step.repeats);}}if(GUILayout.Button("ADD ACTION"))craftingRequest.policy.Add(new CraftPolicyStep{action=CraftingCurrencyType.RerollRareModifier});EditorGUILayout.HelpBox("Only ordinary production gear-crafting operations are currently supported. A positive currency budget limits that action; zero means unlimited.",MessageType.Info);
            Heading("CURRENCY BUDGETS (0 = unlimited)");for(int i=0;i<craftingRequest.budgets.Count;i++){var budget=craftingRequest.budgets[i];using(new EditorGUILayout.HorizontalScope()){budget.type=(CraftingCurrencyType)EditorGUILayout.EnumPopup(budget.type);budget.amount=EditorGUILayout.IntField(budget.amount);}craftingRequest.budgets[i]=budget;}if(GUILayout.Button("ADD BUDGET"))craftingRequest.budgets.Add(new CurrencyStackData(CraftingCurrencyType.RerollRareModifier,10));
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SAVE POLICY"))status=WorkbenchExports.SaveJson("craft_policy",craftingRequest);if(GUILayout.Button("LOAD POLICY")){string path=EditorUtility.OpenFilePanel("Load crafting policy",WorkbenchExports.Root,"json");if(!string.IsNullOrEmpty(path))craftingRequest=JsonUtility.FromJson<CraftingSimulationRequest>(File.ReadAllText(path));}if(GUILayout.Button("ADD POLICY TO COMPARISON"))craftPolicies.Add(JsonUtility.FromJson<CraftingSimulationRequest>(JsonUtility.ToJson(craftingRequest)));}
            if(craftPolicies.Count>=2&&GUILayout.Button("COMPARE SAVED POLICIES"))Run("Craft policy comparison",_=>{craftComparisons.Clear();foreach(var policy in craftPolicies.Take(5)){if(cancelled)break;craftComparisons.Add(CraftingSimulator.Run(policy,Progress("Policies"),()=>cancelled));}});
            if(craftComparisons.Count>0){Heading("POLICY COMPARISON");for(int i=0;i<craftComparisons.Count;i++){var r=craftComparisons[i];EditorGUILayout.LabelField("Policy "+(i+1),$"Success {(r.trials==0?0:r.successes/(double)r.trials):P1} · P50 actions {r.actions.p50:0.#} · P90 {r.actions.p90:0.#} · Potential failures {r.potentialFailures}");}}
            if(GUILayout.Button("RUN CRAFTING SIMULATOR",GUILayout.Height(30)))Run("Crafting trials",_=>craftingResult=CraftingSimulator.Run(craftingRequest,Progress("Crafts"),()=>cancelled));if(craftingResult==null)return;if(craftingResult.Stale)EditorGUILayout.HelpBox("STALE — PRODUCTION DATA CHANGED",MessageType.Warning);EditorGUILayout.LabelField("Success rate",craftingResult.trials==0?"n/a":(craftingResult.successes/(double)craftingResult.trials).ToString("P2"));EditorGUILayout.LabelField("Potential / budget failures",$"{craftingResult.potentialFailures} / {craftingResult.budgetFailures}");Summary("Action count",craftingResult.actions);Summary("Final target matches",craftingResult.finalMatches);foreach(var c in craftingResult.costs)EditorGUILayout.LabelField(c.currency.ToString(),$"Mean {c.mean:0.##} · P50 {c.p50:0.##} · P90 {c.p90:0.##} · P95 {c.p95:0.##} · P99 {c.p99:0.##}");if(craftingResult.replay!=null){Heading("REPLAY ATTEMPT");foreach(var step in craftingResult.replay.trace)EditorGUILayout.LabelField($"{step.number}. {step.action}",$"Potential {step.potentialBefore} → {step.potentialAfter}");if(GUILayout.Button("EXPORT TRACE JSON"))status=WorkbenchExports.SaveJson("craft_trace",craftingResult.replay);}
            if(GUILayout.Button("EXPORT CRAFTING CSV"))status=SaveAdvancedCsv("crafting_result","Trials,Successes,PotentialFailures,BudgetFailures,MedianActions,P90Actions",new[]{$"{craftingResult.trials},{craftingResult.successes},{craftingResult.potentialFailures},{craftingResult.budgetFailures},{craftingResult.actions.p50:R},{craftingResult.actions.p90:R}"});
        }

        static string CsvQ(string value)=>"\""+(value??"").Replace("\"","\"\"")+"\"";
        static string SaveAdvancedCsv(string name,string header,IEnumerable<string> rows){Directory.CreateDirectory(WorkbenchExports.Root);string path=Path.Combine(WorkbenchExports.Root,name+"_"+DateTime.UtcNow.ToString("yyyyMMdd_HHmmss")+".csv");File.WriteAllLines(path,new[]{header}.Concat(rows));AssetDatabase.Refresh();return path;}
    }
}
