using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace BlackCube.BalanceWorkbench
{
    public sealed class BalanceWorkbenchWindow:EditorWindow
    {
        enum Tab{Dashboard,WeaponItemLab,EnemyGearLab,DropSimulator,CurveExplorer,Experiments,SettingsValidation}
        Tab tab;Vector2 scroll;readonly BalanceWorkbenchChart chart=new();ItemLabRequest item=new();EnemyLabRequest enemy=new();DropLabRequest drop=new();ItemLabResult itemResult;EnemyLabResult enemyResult;DropLabResult dropResult;List<DropLabResult> dropMatrix=new();List<CurveSeries> curves=new();string status="Ready";bool cancelled;int sweepStart=1,sweepEnd=100,sweepIncrement=10,sweepSamples=100;
        static readonly string[] labels={"DASHBOARD","WEAPON / ITEM LAB","ENEMY GEAR LAB","DROP SIMULATOR","CURVE EXPLORER","EXPERIMENTS","SETTINGS / VALIDATION"};
        [MenuItem("Black-Cube/Balance Workbench")]
        public static void Open()=>GetWindow<BalanceWorkbenchWindow>("Balance Workbench");
        void OnGUI()
        {
            DrawHeader();tab=(Tab)GUILayout.Toolbar((int)tab,labels,GUILayout.Height(28));scroll=EditorGUILayout.BeginScrollView(scroll);GUILayout.Space(8);switch(tab){case Tab.Dashboard:Dashboard();break;case Tab.WeaponItemLab:ItemLab();break;case Tab.EnemyGearLab:EnemyLab();break;case Tab.DropSimulator:DropLab();break;case Tab.CurveExplorer:CurveExplorer();break;case Tab.Experiments:Experiments();break;default:Validation();break;}EditorGUILayout.EndScrollView();DrawFooter();
        }
        void DrawHeader(){using(new EditorGUILayout.HorizontalScope(EditorStyles.toolbar)){GUILayout.Label("BLACK-CUBE BALANCE WORKBENCH",EditorStyles.boldLabel);GUILayout.FlexibleSpace();GUILayout.Label($"Data {ProductionBalanceAdapters.DataFingerprint()}  Git {ProductionBalanceAdapters.GitCommit()}");}}
        void DrawFooter(){EditorGUILayout.Space();using(new EditorGUILayout.HorizontalScope(EditorStyles.helpBox)){GUILayout.Label(status);GUILayout.FlexibleSpace();if(GUILayout.Button("Cancel Simulation",GUILayout.Width(120)))cancelled=true;}}
        static void Heading(string text,string tooltip=null){GUILayout.Space(6);GUILayout.Label(new GUIContent(text,tooltip),EditorStyles.boldLabel);}
        void Dashboard(){Heading("ENEMY METRICS");if(enemyResult!=null)Summary("Generated Enemy DPS",enemyResult.dps);else EditorGUILayout.HelpBox("Run Enemy Gear Lab to overlay gear-realized metrics.",MessageType.Info);Heading("ITEM METRICS");if(itemResult!=null)Summary("Weapon DPS",itemResult.weaponDps);else EditorGUILayout.HelpBox("Run Weapon / Item Lab to populate item metrics.",MessageType.Info);Heading("LOOT METRICS");if(dropResult!=null){EditorGUILayout.LabelField("Average gear / kill",dropResult.averageGearItems.ToString("0.###"));EditorGUILayout.LabelField("Currency rolls / kill",dropResult.averageCurrencyRolls.ToString("0.###"));}else EditorGUILayout.HelpBox("Run Drop Simulator to populate loot metrics.",MessageType.Info);}
        void ItemLab()
        {
            Heading("GENERATION INPUTS","Samples call ModManager's production affix/tier/value rolls with an injected deterministic stream.");item.mode=(ItemLabMode)EditorGUILayout.EnumPopup("Mode",item.mode);if(item.mode==ItemLabMode.SpecificSlot)item.slot=(LootManager.GearType)EditorGUILayout.EnumPopup("Slot",item.slot);if(item.mode==ItemLabMode.Weapon){string[] weapons=new[]{"Any"}.Concat(WeaponTypeCatalog.All.Select(x=>x.Id)).ToArray();item.weaponTypeId=weapons[Mathf.Max(0,Array.IndexOf(weapons,item.weaponTypeId))];item.weaponTypeId=weapons[EditorGUILayout.Popup("Weapon Type",Array.IndexOf(weapons,item.weaponTypeId),weapons)];}item.itemLevel=EditorGUILayout.IntSlider("Item Level",item.itemLevel,1,100);item.naturalRarity=EditorGUILayout.Toggle("Natural Rarity",item.naturalRarity);if(!item.naturalRarity)item.rarity=(LootManager.GearRarity)EditorGUILayout.EnumPopup("Rarity",item.rarity);item.sampleCount=SampleCount(item.sampleCount);item.seed=EditorGUILayout.LongField("Simulation Seed",item.seed);
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("GENERATE ITEMS",GUILayout.Height(30)))Run("Generating production items",p=>itemResult=ProductionBalanceAdapters.RunItems(item,Progress("Items"),()=>cancelled));if(GUILayout.Button("RUN LEVEL SWEEP",GUILayout.Height(30)))RunItemSweep();}SweepInputs(100);if(itemResult==null)return;Heading("RESULTS");Summary("Weapon DPS",itemResult.weaponDps);Summary("Gear Score",itemResult.gearScore);Summary("Attack Speed",itemResult.attackSpeed);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("Min"))ShowItem(itemResult.samples.OrderBy(x=>x.weaponDps).First());foreach(double p in new[]{.10,.25,.50,.75,.90,.99})if(GUILayout.Button($"P{p*100:0}"))ShowItem(Representative(itemResult.samples,p,x=>x.weaponDps));if(GUILayout.Button("Max"))ShowItem(itemResult.samples.OrderBy(x=>x.weaponDps).Last());}using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("Export CSV"))status=WorkbenchExports.SaveItemCsv(itemResult);if(GUILayout.Button("Copy CSV")){GUIUtility.systemCopyBuffer=WorkbenchExports.ItemCsv(itemResult);status="Item CSV copied to clipboard.";}}DrawHistogram("Weapon DPS distribution",itemResult.samples.Select(x=>x.weaponDps));
        }
        void EnemyLab()
        {
            Heading("PRODUCTION ENEMY GENERATION","Each sample instantiates one isolated production enemy, runs its real candidate generation and EnemyBuildOptimizer, captures results, then destroys it.");var db=WorldContentCatalog.Reference;string[] ids=new[]{"Any"}.Concat(db.enemyArchetypes.Select(x=>x.stableId)).ToArray();int idx=Mathf.Max(0,Array.IndexOf(ids,enemy.archetypeId));enemy.archetypeId=ids[EditorGUILayout.Popup("Enemy Archetype",idx,ids)];enemy.level=EditorGUILayout.IntSlider("Enemy Level",enemy.level,1,360);enemy.productionRarity=EditorGUILayout.Toggle("Production Rarity",enemy.productionRarity);if(!enemy.productionRarity)enemy.rarity=(EnemyAI.EnemyRarity)EditorGUILayout.EnumPopup("Rarity",enemy.rarity);enemy.forcePrimaryDamage=EditorGUILayout.Toggle("Force Primary Damage",enemy.forcePrimaryDamage);if(enemy.forcePrimaryDamage)enemy.primaryDamage=(Element)EditorGUILayout.EnumPopup("Primary Damage",enemy.primaryDamage);enemy.sampleCount=SampleCount(enemy.sampleCount);enemy.seed=EditorGUILayout.LongField("Simulation Seed",enemy.seed);
            using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("GENERATE ENEMIES",GUILayout.Height(30)))Run("Generating production enemies",p=>enemyResult=ProductionBalanceAdapters.RunEnemies(enemy,Progress("Enemies"),()=>cancelled));if(GUILayout.Button("RUN LEVEL SWEEP",GUILayout.Height(30)))RunEnemySweep();}SweepInputs(360);if(enemyResult==null)return;Heading("RESULTS");Summary("Final Life",enemyResult.life);Summary("Expected Basic DPS",enemyResult.dps);Summary("Actual Enemy GearScore",enemyResult.gearScore);Summary("Armour",enemyResult.armour);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("Weakest"))ShowEnemy(enemyResult.samples.OrderBy(x=>x.gearScore).First());foreach(double p in new[]{.10,.50,.90,.99})if(GUILayout.Button($"P{p*100:0}"))ShowEnemy(Representative(enemyResult.samples,p,x=>x.gearScore));if(GUILayout.Button("Strongest"))ShowEnemy(enemyResult.samples.OrderBy(x=>x.gearScore).Last());}using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("Export CSV"))status=WorkbenchExports.SaveEnemyCsv(enemyResult);if(GUILayout.Button("Copy CSV")){GUIUtility.systemCopyBuffer=WorkbenchExports.EnemyCsv(enemyResult);status="Enemy CSV copied to clipboard.";}}DrawHistogram("Enemy GearScore distribution",enemyResult.samples.Select(x=>x.gearScore));
        }
        void DropLab()
        {
            Heading("SIMULATION INPUTS","Uses EnemyLootProfile and CurrencyLootTable directly. Fixed Gear Quality is a PREVIEW ONLY override.");drop.level=EditorGUILayout.IntSlider("Enemy Level",drop.level,1,360);drop.rarity=(EnemyAI.EnemyRarity)EditorGUILayout.EnumPopup("Enemy Rarity",drop.rarity);drop.boss=EditorGUILayout.Toggle("Boss Source",drop.boss);drop.generateActualEnemyGear=EditorGUILayout.Toggle("Generate Actual Enemy Gear",drop.generateActualEnemyGear);if(!drop.generateActualEnemyGear)drop.fixedGearQuality=EditorGUILayout.Slider("Fixed Gear Quality (PREVIEW ONLY)",drop.fixedGearQuality,.6f,3f);drop.sampleCount=SampleCount(drop.sampleCount,100000);drop.seed=EditorGUILayout.LongField("Simulation Seed",drop.seed);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("SIMULATE DROPS",GUILayout.Height(30)))Run("Simulating production drops",p=>dropResult=ProductionBalanceAdapters.RunDrops(drop,Progress("Kills"),()=>cancelled));if(GUILayout.Button("COMPARE ALL RARITIES",GUILayout.Height(30)))RunRarityMatrix();if(GUILayout.Button("RUN LEVEL SWEEP",GUILayout.Height(30)))RunDropSweep();}SweepInputs(360);if(dropResult==null)return;Heading("RESULTS");EditorGUILayout.LabelField("Average gear items / kill",dropResult.averageGearItems.ToString("0.####"));EditorGUILayout.LabelField("P50 / P90 gear",$"{dropResult.gearCount.p50:0.##} / {dropResult.gearCount.p90:0.##}");EditorGUILayout.LabelField("Average currency rolls / kill",dropResult.averageCurrencyRolls.ToString("0.####"));EditorGUILayout.LabelField("Chance of any currency",dropResult.chanceAnyCurrency.ToString("P3"));using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("Export CSV"))status=WorkbenchExports.SaveDropCsv(dropResult);if(GUILayout.Button("Copy CSV")){GUIUtility.systemCopyBuffer=WorkbenchExports.DropCsv(dropResult);status="Drop CSV copied to clipboard.";}}if(dropMatrix.Count>0){Heading("RARITY MATRIX");foreach(var r in dropMatrix)EditorGUILayout.LabelField(r.metadata.scenario,$"Any {r.chanceAnyCurrency:P3} · Gear {r.averageGearItems:0.###} · Currency rolls {r.averageCurrencyRolls:0.###}");}Heading("PER-CURRENCY TABLE");foreach(var c in dropResult.currencies)using(new EditorGUILayout.HorizontalScope()){GUILayout.Label(c.name,GUILayout.Width(180));GUILayout.Label(c.stableId,GUILayout.Width(230));GUILayout.Label($"W {c.weight:0.##}",GUILayout.Width(60));GUILayout.Label($"Chance {c.chancePerKill:P3}",GUILayout.Width(110));GUILayout.Label($"/1000 {c.perThousand:0.###}");}
        }
        void CurveExplorer(){Heading("INTRINSIC BASELINE CURVES");using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("Generate Levels 1–360")){curves=ProductionBalanceAdapters.IntrinsicCurves(1,360,5);status="Intrinsic production curves generated.";}if(GUILayout.Button("Reset View"))chart.Reset();if(GUILayout.Button("Export PNG"))status=chart.ExportPng(curves,"intrinsic_curves");}Rect rect=GUILayoutUtility.GetRect(200,440,GUILayout.ExpandWidth(true));chart.Draw(rect,curves,"Combat Level","Production value");Heading("TABLE VIEW");if(curves.Count>0)foreach(var p in curves[0].points)EditorGUILayout.LabelField($"Level {p.x:0}",$"{curves[0].name}: {p.mean:0.###}");}
        void Experiments(){Heading("SAVED EXPERIMENTS");EditorGUILayout.HelpBox("Presets are version-controlled JSON in Assets/Balance/Presets. Result runs export to ReviewCaptures/BalanceWorkbench.",MessageType.Info);using(new EditorGUILayout.HorizontalScope()){if(GUILayout.Button("Save"))SavePreset();if(GUILayout.Button("Load / Rerun"))LoadPreset();if(GUILayout.Button("Duplicate"))DuplicatePreset();if(GUILayout.Button("Rename"))RenamePreset();if(GUILayout.Button("Delete"))DeletePreset();if(GUILayout.Button("Open Exports")){Directory.CreateDirectory(WorkbenchExports.Root);EditorUtility.RevealInFinder(WorkbenchExports.Root);}}if(itemResult!=null&&GUILayout.Button("Save Item Result JSON"))status=WorkbenchExports.SaveJson("item_result",itemResult);if(enemyResult!=null&&GUILayout.Button("Save Enemy Result JSON"))status=WorkbenchExports.SaveJson("enemy_result",enemyResult);if(dropResult!=null&&GUILayout.Button("Save Drop Result JSON"))status=WorkbenchExports.SaveJson("drop_result",dropResult);}
        void Validation()
        {
            Heading("PRODUCTION VALUES");var profile=LootBalanceProfileSO.Current;var so=new SerializedObject(profile);so.Update();EditorGUILayout.PropertyField(so.FindProperty("levelFactorMinimum"));EditorGUILayout.PropertyField(so.FindProperty("levelFactorMaximum"));EditorGUILayout.PropertyField(so.FindProperty("currencyRollCoefficient"));EditorGUILayout.PropertyField(so.FindProperty("extraGearCoefficient"));EditorGUILayout.PropertyField(so.FindProperty("maximumCurrencyRolls"));EditorGUILayout.PropertyField(so.FindProperty("currencies"),true);if(so.hasModifiedProperties){EditorGUILayout.HelpBox("Pending changes are not applied until the explicit button below.",MessageType.Warning);if(GUILayout.Button("APPLY TO PRODUCTION")&&EditorUtility.DisplayDialog("Apply loot production values?","This writes the authoritative LootBalanceProfile asset. Undo is available.","Apply","Cancel")){Undo.RecordObject(profile,"Apply loot balance values");so.ApplyModifiedProperties();EditorUtility.SetDirty(profile);AssetDatabase.SaveAssets();status="Production loot profile updated.";}}
            Heading("VALIDATION");if(GUILayout.Button("VALIDATE BALANCE TOOLING")){string[] errors=BalanceWorkbenchValidation.Validate();status=errors.Length==0?"PASS: all balance tooling adapters validated.":string.Join(" | ",errors);EditorUtility.DisplayDialog(errors.Length==0?"Validation Passed":"Validation Failed",status,"OK");}EditorGUILayout.LabelField("Production RNG",LootRandomSourceFactory.CreateProduction().GetType().Name);EditorGUILayout.LabelField("Save schema",GamePersistence.SchemaVersion.ToString());EditorGUILayout.LabelField("Data fingerprint",ProductionBalanceAdapters.DataFingerprint());Heading("FUTURE EXTENSION POINTS");GUILayout.Label("Player Builds · Passive Optimizer · Enemy Authoring · Combat Lab · Sensitivity · Affix Analyzer · Crafting · Regression · Breakpoints",EditorStyles.wordWrappedLabel);
        }
        void Run(string title,Action<float> action){cancelled=false;try{action(0);status=cancelled?"Simulation cancelled; partial result retained.":title+" complete.";}catch(Exception ex){status=ex.Message;Debug.LogException(ex);}finally{EditorUtility.ClearProgressBar();Repaint();}}
        Action<float> Progress(string label)=>p=>{if(EditorUtility.DisplayCancelableProgressBar("Black-Cube Balance Workbench",$"{label}: {p:P1}",p))cancelled=true;};
        static int SampleCount(int value,int max=10000){using(new EditorGUILayout.HorizontalScope()){value=EditorGUILayout.IntField("Sample Count",value);if(GUILayout.Button("100",GUILayout.Width(48)))value=100;if(GUILayout.Button("1,000",GUILayout.Width(52)))value=1000;if(GUILayout.Button("10,000",GUILayout.Width(58)))value=10000;}return Mathf.Clamp(value,1,max);}
        void SweepInputs(int max){using(new EditorGUILayout.HorizontalScope()){sweepStart=EditorGUILayout.IntField("Sweep Start",sweepStart);sweepEnd=EditorGUILayout.IntField("End",sweepEnd);sweepIncrement=EditorGUILayout.IntField("Step",sweepIncrement);sweepSamples=EditorGUILayout.IntField("Samples / Level",sweepSamples);}sweepStart=Mathf.Clamp(sweepStart,1,max);sweepEnd=Mathf.Clamp(sweepEnd,sweepStart,max);sweepIncrement=Mathf.Max(1,sweepIncrement);sweepSamples=Mathf.Clamp(sweepSamples,1,10000);}
        void RunItemSweep(){cancelled=false;var mean=new CurveSeries{name="Mean",color=Color.cyan};var p10=new CurveSeries{name="P10",color=Color.gray};var p50=new CurveSeries{name="P50",color=Color.green};var p90=new CurveSeries{name="P90",color=Color.yellow};int original=item.itemLevel,count=item.sampleCount;try{item.sampleCount=sweepSamples;for(int l=sweepStart;l<=sweepEnd&&!cancelled;l+=sweepIncrement){item.itemLevel=l;var r=ProductionBalanceAdapters.RunItems(item);mean.points.Add(new CurvePoint{x=l,mean=r.weaponDps.mean});p10.points.Add(new CurvePoint{x=l,mean=r.weaponDps.p10});p50.points.Add(new CurvePoint{x=l,mean=r.weaponDps.p50});p90.points.Add(new CurvePoint{x=l,mean=r.weaponDps.p90});cancelled=EditorUtility.DisplayCancelableProgressBar("Item Level Sweep",$"Level {l}",(l-sweepStart+1f)/(sweepEnd-sweepStart+1f));}curves=new(){mean,p10,p50,p90};tab=Tab.CurveExplorer;status="Item DPS level sweep complete.";}finally{item.itemLevel=original;item.sampleCount=count;EditorUtility.ClearProgressBar();}}
        void RunEnemySweep(){cancelled=false;var life=new CurveSeries{name="Enemy P50 Life",color=Color.green};var dps=new CurveSeries{name="Enemy P50 DPS",color=Color.red};var p90=new CurveSeries{name="Enemy P90 DPS",color=Color.yellow};int original=enemy.level,count=enemy.sampleCount;try{enemy.sampleCount=sweepSamples;for(int l=sweepStart;l<=sweepEnd&&!cancelled;l+=sweepIncrement){enemy.level=l;var r=ProductionBalanceAdapters.RunEnemies(enemy);life.points.Add(new CurvePoint{x=l,mean=r.life.p50});dps.points.Add(new CurvePoint{x=l,mean=r.dps.p50});p90.points.Add(new CurvePoint{x=l,mean=r.dps.p90});cancelled=EditorUtility.DisplayCancelableProgressBar("Enemy Gear Sweep",$"Level {l}",(l-sweepStart+1f)/(sweepEnd-sweepStart+1f));}curves=new(){life,dps,p90};tab=Tab.CurveExplorer;status="Enemy gear level sweep complete.";}finally{enemy.level=original;enemy.sampleCount=count;EditorUtility.ClearProgressBar();}}
        void RunDropSweep(){cancelled=false;var chance=new CurveSeries{name="Any Currency Chance",color=Color.cyan};var rolls=new CurveSeries{name="Currency Rolls / Kill",color=Color.yellow};int original=drop.level,count=drop.sampleCount;try{drop.sampleCount=sweepSamples;for(int l=sweepStart;l<=sweepEnd&&!cancelled;l+=sweepIncrement){drop.level=l;var r=ProductionBalanceAdapters.RunDrops(drop);chance.points.Add(new CurvePoint{x=l,mean=r.chanceAnyCurrency});rolls.points.Add(new CurvePoint{x=l,mean=r.averageCurrencyRolls});cancelled=EditorUtility.DisplayCancelableProgressBar("Drop Sweep",$"Level {l}",(l-sweepStart+1f)/(sweepEnd-sweepStart+1f));}curves=new(){chance,rolls};tab=Tab.CurveExplorer;status="Drop level sweep complete.";}finally{drop.level=original;drop.sampleCount=count;EditorUtility.ClearProgressBar();}}
        void RunRarityMatrix(){dropMatrix.Clear();var original=drop.rarity;bool boss=drop.boss;try{foreach(EnemyAI.EnemyRarity rarity in Enum.GetValues(typeof(EnemyAI.EnemyRarity))){drop.rarity=rarity;drop.boss=false;var r=ProductionBalanceAdapters.RunDrops(drop);r.metadata.scenario=rarity.ToString();dropMatrix.Add(r);}drop.rarity=EnemyAI.EnemyRarity.Legendary;drop.boss=true;var br=ProductionBalanceAdapters.RunDrops(drop);br.metadata.scenario="Boss";dropMatrix.Add(br);status="Rarity matrix complete.";}finally{drop.rarity=original;drop.boss=boss;}}
        static void Summary(string label,MetricSummary m){if(m==null)return;EditorGUILayout.LabelField(label,$"Mean {m.mean:0.###}  P10 {m.p10:0.###}  P25 {m.p25:0.###}  P50 {m.p50:0.###}  P75 {m.p75:0.###}  P90 {m.p90:0.###}  P95 {m.p95:0.###}  P99 {m.p99:0.###}");}
        static T Representative<T>(List<T> list,double p,Func<T,double> f)=>list.OrderBy(f).ElementAt(Mathf.Clamp((int)Math.Round((list.Count-1)*p),0,list.Count-1));
        static void ShowItem(ItemSample x)=>EditorUtility.DisplayDialog($"Representative item #{x.index}",x.detail+$"\nDPS {x.weaponDps:0.###}\nGearScore {x.gearScore:0.###}","Close");
        static void ShowEnemy(EnemySample x)=>EditorUtility.DisplayDialog($"{x.archetype} L{x.level}",$"Rarity {(EnemyAI.EnemyRarity)x.rarity}\nPrimary {x.primaryDamage}\nLife {x.life:0.##}\nHit {x.damagePerHit:0.##} @ {x.attackSpeed:0.###} APS\nDPS {x.dps:0.##}\nGearScore {x.gearScore:0.##}\nSlots {x.slotCount}; candidates/slot {x.candidateCount}\n{x.equipment}","Close");
        static void DrawHistogram(string label,IEnumerable<double> values){Heading(label);var bins=WorkbenchStatistics.Histogram(values);int max=bins.Count==0?1:bins.Max(x=>x.count);foreach(var b in bins){Rect r=GUILayoutUtility.GetRect(40,12,GUILayout.ExpandWidth(true));EditorGUI.ProgressBar(r,b.count/(float)max,$"{b.minimum:0.#}–{b.maximum:0.#}: {b.count}");}}
        void SavePreset(){Directory.CreateDirectory("Assets/Balance/Presets");string path=EditorUtility.SaveFilePanelInProject("Save Workbench Preset","BalancePreset","json","Choose a preset name","Assets/Balance/Presets");if(string.IsNullOrEmpty(path))return;File.WriteAllText(path,JsonUtility.ToJson(new Preset{item=item,enemy=enemy,drop=drop},true));AssetDatabase.Refresh();status="Saved "+path;}
        void LoadPreset(){string path=EditorUtility.OpenFilePanel("Load Workbench Preset",Path.GetFullPath("Assets/Balance/Presets"),"json");if(string.IsNullOrEmpty(path))return;var p=JsonUtility.FromJson<Preset>(File.ReadAllText(path));if(p!=null){item=p.item??item;enemy=p.enemy??enemy;drop=p.drop??drop;status="Loaded "+path;}}
        string ChoosePreset(string title)=>EditorUtility.OpenFilePanel(title,Path.GetFullPath("Assets/Balance/Presets"),"json");
        void DuplicatePreset(){string source=ChoosePreset("Duplicate Workbench Preset");if(string.IsNullOrEmpty(source))return;string target=EditorUtility.SaveFilePanelInProject("Duplicate Preset",Path.GetFileNameWithoutExtension(source)+" Copy","json","Choose the duplicate name","Assets/Balance/Presets");if(string.IsNullOrEmpty(target))return;File.Copy(source,target,true);AssetDatabase.Refresh();status="Duplicated preset to "+target;}
        void RenamePreset(){string source=ChoosePreset("Rename Workbench Preset");if(string.IsNullOrEmpty(source))return;string relative="Assets"+source.Replace('\\','/').Split(new[]{"/Assets"},StringSplitOptions.None).Last();string target=EditorUtility.SaveFilePanelInProject("Rename Preset",Path.GetFileNameWithoutExtension(source),"json","Choose the new name","Assets/Balance/Presets");if(string.IsNullOrEmpty(target))return;string error=AssetDatabase.MoveAsset(relative,target);status=string.IsNullOrEmpty(error)?"Renamed preset to "+target:error;}
        void DeletePreset(){string source=ChoosePreset("Delete Workbench Preset");if(string.IsNullOrEmpty(source)||!EditorUtility.DisplayDialog("Delete preset?",source,"Delete","Cancel"))return;string relative="Assets"+source.Replace('\\','/').Split(new[]{"/Assets"},StringSplitOptions.None).Last();status=AssetDatabase.DeleteAsset(relative)?"Deleted "+relative:"Could not delete "+relative;}
        [Serializable] sealed class Preset{public ItemLabRequest item;public EnemyLabRequest enemy;public DropLabRequest drop;}
    }

    public static class BalanceWorkbenchValidation
    {
        public static string[] Validate(){var errors=new List<string>();try{using var s=new WorkbenchSession();if(s.Roller.Database==null)errors.Add("Affix database missing");}catch(Exception e){errors.Add(e.Message);}if(WeaponTypeCatalog.All.Count!=6)errors.Add("Expected six weapon profiles");if(WorldContentCatalog.Reference?.enemyArchetypes?.Count<1)errors.Add("Enemy archetypes missing");try{_ = EnemyScalingProfile.Default;}catch(Exception e){errors.Add(e.Message);}if(LootBalanceProfileSO.Current.currencies.Count==0)errors.Add("Loot config missing currencies");var a=new SeededSimulationRandomSource(17);var b=new SeededSimulationRandomSource(17);for(int i=0;i<32;i++)if(a.Value()!=b.Value()){errors.Add("Simulation RNG is not deterministic");break;}if(LootRandomSourceFactory.CreateProduction() is not ProductionLootRandomSource)errors.Add("Production RNG factory changed");foreach(var s in ProductionBalanceAdapters.IntrinsicCurves(1,360,1).SelectMany(x=>x.points))if(!double.IsFinite(s.mean))errors.Add("Curve contains non-finite value");return errors.Distinct().ToArray();}
    }
}
