using System;
using System.IO;
using System.Linq;
using BlackCube.BalanceWorkbench;
using UnityEditor;
using UnityEngine;

public static class Tooling5ValidationRunner
{
    static PlayerBuildSnapshot Build()=>new(){playerLevel=60,combatLevel=60,classId=PlayerClassIds.Warrior,weaponTypeId=WeaponTypeIds.Sword,seed=59001,equipment=new(){new GearSnapshot{slot=LootManager.GearType.Weapons,rarity=LootManager.GearRarity.Rare,itemLevel=60,element=Element.Phys,weaponTypeId=WeaponTypeIds.Sword,baseMin=40,baseMax=60,baseSpeed=1.2f,baseCrit=.05f}}};
    public static void RunFocused()=>Run(()=>
    {
        var lines=new System.Collections.Generic.List<string>{"TOOLING 5 FOCUSED VALIDATION"};var build=Build();
        var sensitivity=new SensitivityRequest{build=build,metric="basic_dps",stats=new(){StatTypes.PhysDmg,StatTypes.AttackSpeed,StatTypes.CritChance,StatTypes.CritMult},amount=.1f};var a=SensitivityAnalyzer.Run(sensitivity);var b=SensitivityAnalyzer.Run(sensitivity);if(a.rows.Count!=4||a.rows.Zip(b.rows,(x,y)=>x.stat==y.stat&&x.modified==y.modified).Any(equal=>!equal))throw new Exception("Sensitivity was not deterministic.");lines.Add("PASS analytical sensitivity reproducibility");
        var pairs=SensitivityAnalyzer.Pairs(sensitivity,new[]{StatTypes.CritChance,StatTypes.CritMult});if(pairs.Count!=1||!double.IsFinite(pairs[0].interaction))throw new Exception("Pair sensitivity failed.");lines.Add("PASS pair interaction");
        var bp=BreakpointFinder.Find(x=>x-37,1,100,10,0,BreakpointOperator.GreaterOrEqual);if(bp.Count!=1||bp[0].level!=37)throw new Exception("Monotonic breakpoint fixture failed.");var multi=BreakpointFinder.Find(x=>Math.Sin(x),1,30,5,0,BreakpointOperator.CrossUp,true);if(multi.Count<2)throw new Exception("Non-monotonic crossings failed.");lines.Add("PASS monotonic and non-monotonic breakpoints");
        var affix=AffixAnalyzer.Run(new AffixAnalysisRequest{build=build,itemLevel=60,element=Element.Phys,weaponTypeId=WeaponTypeIds.Sword});if(affix.rows.Count==0)throw new Exception("No legal production affixes found.");lines.Add("PASS production affix catalog: "+affix.rows.Count);
        var loot=LootProgressionAnalyzer.Run(new LootProgressionRequest{build=build,kills=25,combatLevel=60});if(loot.kills!=25||loot.drops<25)throw new Exception("Loot progression did not process every kill.");lines.Add("PASS per-kill loot: "+loot.drops+" drops");
        using(var session=new WorkbenchSession()){var item=session.ReusableItem;item.Initialize(LootManager.GearType.Weapons,LootManager.GearRarity.Rare,60,Element.Phys,WeaponTypeIds.Sword);var rng=new SeededSimulationRandomSource(501);var mods=session.Roller.RollEquipmentModsForItem(item.ItemType,item.ItemRarity,item.ItemLevel,item.BaseElement,item.WeaponTypeId,rng);if(mods==null)throw new Exception("Craft fixture item generation failed.");item.ApplyMods(mods);var target=GearSnapshot.Capture(item);var craft=CraftingSimulator.Run(new CraftingSimulationRequest{item=target,targets=new(){new CraftTarget{stat=StatTypes.CritChance,maximumTier=1}},policy=new(){new CraftPolicyStep{action=CraftingCurrencyType.RerollRareModifier}},trials=10,maxActions=4,seed=302});if(craft.trials!=10||craft.actions==null)throw new Exception("Craft simulation failed.");lines.Add("PASS deterministic production crafting trials");}
        var suite=new BalanceSuite{name="Fixture",scenarios=new(){new BalanceScenario{name="Warrior",build=build,metric="basic_dps"}}};var before=BalanceSnapshotService.Capture(suite,"Before");var after=BalanceSnapshotService.Capture(suite,"After");if(BalanceSnapshotService.Compare(before,after,.1).Any(x=>x.delta!=0))throw new Exception("Snapshot did not reproduce.");lines.Add("PASS snapshot reproduction");
        Directory.CreateDirectory("Logs");File.WriteAllLines("Logs/Tooling5Focused.txt",lines);Debug.Log(string.Join("\n",lines));
    });
    public static void RunSmoke()=>Run(()=>
    {
        var build=Build();var lines=new System.Collections.Generic.List<string>{"TOOLING 5 EDITOR SMOKE"};var sensitivity=new SensitivityRequest{build=build,metric="basic_dps",stats=new(){StatTypes.PhysDmg,StatTypes.AttackSpeed,StatTypes.CritChance,StatTypes.CritMult}};var result=SensitivityAnalyzer.Run(sensitivity);lines.Add("Sensitivity: "+result.rows.Count+" ranked stats");
        var affix=AffixAnalyzer.Run(new AffixAnalysisRequest{build=build,itemLevel=60,element=Element.Phys,weaponTypeId=WeaponTypeIds.Sword,allTiers=true,pairTop=5});lines.Add("Affix: "+affix.rows.Count+" tiers, "+affix.pairs.Count+" pairs");
        var loot=LootProgressionAnalyzer.Run(new LootProgressionRequest{build=build,kills=100,combatLevel=60});lines.Add("Loot: "+loot.drops+" drops, "+loot.upgrades.Count+" upgrades");
        var suit=new BalanceSuite{scenarios=new(){new BalanceScenario{name="Warrior",build=build}}};var before=BalanceSnapshotService.Capture(suit,"Before");var after=BalanceSnapshotService.Capture(suit,"After");string report=BalanceSnapshotService.ExportMarkdown(after,BalanceSnapshotService.Compare(before,after,.1));if(!File.Exists(report))throw new Exception("Report missing");lines.Add("Snapshot + report: "+report);
        Directory.CreateDirectory("Logs");File.WriteAllLines("Logs/Tooling5Smoke.txt",lines);Debug.Log(string.Join("\n",lines));
    });
    public static void RunRequiredSmoke()=>Run(()=>
    {
        var build=Build();var lines=new System.Collections.Generic.List<string>{"TOOLING 5 REQUIRED WORKFLOW SMOKE"};
        var world=WorldContentCatalog.Reference;var combat=new CombatLabRequest{player=build,enemyArchetypeId=world.enemyArchetypes[0].stableId,enemyLevel=60,rarity=EnemyAI.EnemyRarity.Rare,seed=96001,fightCount=20};
        var sensitivity=new SensitivityRequest{build=build,combat=combat,mode=SensitivityMode.Combat,metric="win_rate",stats=new(){StatTypes.AttackSpeed},amount=.1f};var first=SensitivityAnalyzer.Run(sensitivity);var repeated=SensitivityAnalyzer.Run(sensitivity);if(first.rows.Single().modified!=repeated.rows.Single().modified)throw new Exception("Combat sensitivity did not repeat.");lines.Add("PASS combat sensitivity common-seed repeat");
        var affix=AffixAnalyzer.Run(new AffixAnalysisRequest{build=build,itemLevel=60,element=Element.Phys,weaponTypeId=WeaponTypeIds.Sword,allTiers=true,pairTop=5});if(affix.rows.Count<5||affix.pairs.Count==0)throw new Exception("Affix tier/pair smoke failed.");lines.Add($"PASS Sword tier/pair analysis: {affix.rows.Count} rows / {affix.pairs.Count} pairs");
        var lootRequest=new LootProgressionRequest{build=build,combatLevel=60,kills=10000,seed=96002,generateActualEnemyGear=true};var staticRun=LootProgressionAnalyzer.Run(lootRequest);lootRequest.progressive=true;var progressive=LootProgressionAnalyzer.Run(lootRequest);if(staticRun.kills!=10000||progressive.kills!=10000)throw new Exception("10,000-kill loot runs incomplete.");lines.Add($"PASS 10,000-kill static/progressive: {staticRun.upgrades.Count}/{progressive.upgrades.Count} upgrades");
        using(var session=new WorkbenchSession()){var item=session.ReusableItem;item.Initialize(LootManager.GearType.Weapons,LootManager.GearRarity.Rare,60,Element.Phys,WeaponTypeIds.Sword);var rng=new SeededSimulationRandomSource(96003);var mods=session.Roller.RollEquipmentModsForItem(item.ItemType,item.ItemRarity,item.ItemLevel,item.BaseElement,item.WeaponTypeId,rng);if(mods==null)throw new Exception("Craft fixture generation failed.");item.ApplyMods(mods);var craft=CraftingSimulator.Run(new CraftingSimulationRequest{item=GearSnapshot.Capture(item),targets=new(){new CraftTarget{stat=StatTypes.CritChance,maximumTier=1}},policy=new(){new CraftPolicyStep{action=CraftingCurrencyType.RerollRareModifier}},trials=1000,maxActions=20,seed=96004});if(craft.trials!=1000)throw new Exception("Crafting smoke incomplete.");lines.Add($"PASS 1,000 crafting trials: {craft.successes} successes, {craft.potentialFailures} Potential failures");}
        var suite=new BalanceSuite{scenarios=new(){new BalanceScenario{name="Warrior DPS",build=build,metric="basic_dps"}}};var before=BalanceSnapshotService.Capture(suite,"Before");suite.scenarios[0].build.analysisDeltas.Add(new AnalysisStatDelta{stat=StatTypes.AttackSpeed,amount=.1f});var after=BalanceSnapshotService.Capture(suite,"Fixture after");var difference=BalanceSnapshotService.Compare(before,after,.05).Single();if(difference.delta<=0)throw new Exception("Snapshot fixture change not detected.");var report=BalanceSnapshotService.ExportMarkdown(after,new[]{difference});if(!File.Exists(report))throw new Exception("Markdown report missing.");lines.Add("PASS snapshot change and report export: "+report);
        var breakpoints=BreakpointFinder.Find(x=>x,30,80,10,60,BreakpointOperator.GreaterOrEqual);if(breakpoints.Single().level!=60)throw new Exception("Breakpoint smoke failed.");lines.Add("PASS breakpoint marker at level 60");
        Directory.CreateDirectory("Logs");File.WriteAllLines("Logs/Tooling5RequiredSmoke.txt",lines);Debug.Log(string.Join("\n",lines));
    });
    public static void BuildWindows()=>Run(BaselineVerificationRunner.BuildTooling5Windows);
    static void Run(Action action){try{action();EditorApplication.Exit(0);}catch(Exception ex){Debug.LogException(ex);EditorApplication.Exit(1);}}
}
